# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_host_pb2 as grpc__host__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_host_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcWorkerAgentRuntimeHostStub(object):
    """Worker registration and management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/RegisterWorker',
                request_serializer=grpc__host__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.UnregisterWorker = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/UnregisterWorker',
                request_serializer=grpc__host__pb2.UnregisterWorkerRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.UnregisterWorkerResponse.FromString,
                _registered_method=True)
        self.DistributeTask = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/DistributeTask',
                request_serializer=grpc__host__pb2.DistributeTaskRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.DistributeTaskResponse.FromString,
                _registered_method=True)
        self.CollectTaskResult = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/CollectTaskResult',
                request_serializer=grpc__host__pb2.CollectTaskResultRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.CollectTaskResultResponse.FromString,
                _registered_method=True)
        self.GetWorkerStatus = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/GetWorkerStatus',
                request_serializer=grpc__host__pb2.GetWorkerStatusRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.GetWorkerStatusResponse.FromString,
                _registered_method=True)
        self.GetAllWorkers = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/GetAllWorkers',
                request_serializer=grpc__host__pb2.GetAllWorkersRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.GetAllWorkersResponse.FromString,
                _registered_method=True)
        self.GetTaskStatistics = channel.unary_unary(
                '/grpc_host.GrpcWorkerAgentRuntimeHost/GetTaskStatistics',
                request_serializer=grpc__host__pb2.GetTaskStatisticsRequest.SerializeToString,
                response_deserializer=grpc__host__pb2.GetTaskStatisticsResponse.FromString,
                _registered_method=True)


class GrpcWorkerAgentRuntimeHostServicer(object):
    """Worker registration and management
    """

    def RegisterWorker(self, request, context):
        """Register a worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterWorker(self, request, context):
        """Unregister a worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributeTask(self, request, context):
        """Distribute a task to a worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectTaskResult(self, request, context):
        """Collect task result from worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerStatus(self, request, context):
        """Get worker status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllWorkers(self, request, context):
        """Get all workers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatistics(self, request, context):
        """Get task statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcWorkerAgentRuntimeHostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=grpc__host__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=grpc__host__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'UnregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterWorker,
                    request_deserializer=grpc__host__pb2.UnregisterWorkerRequest.FromString,
                    response_serializer=grpc__host__pb2.UnregisterWorkerResponse.SerializeToString,
            ),
            'DistributeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributeTask,
                    request_deserializer=grpc__host__pb2.DistributeTaskRequest.FromString,
                    response_serializer=grpc__host__pb2.DistributeTaskResponse.SerializeToString,
            ),
            'CollectTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectTaskResult,
                    request_deserializer=grpc__host__pb2.CollectTaskResultRequest.FromString,
                    response_serializer=grpc__host__pb2.CollectTaskResultResponse.SerializeToString,
            ),
            'GetWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerStatus,
                    request_deserializer=grpc__host__pb2.GetWorkerStatusRequest.FromString,
                    response_serializer=grpc__host__pb2.GetWorkerStatusResponse.SerializeToString,
            ),
            'GetAllWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllWorkers,
                    request_deserializer=grpc__host__pb2.GetAllWorkersRequest.FromString,
                    response_serializer=grpc__host__pb2.GetAllWorkersResponse.SerializeToString,
            ),
            'GetTaskStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatistics,
                    request_deserializer=grpc__host__pb2.GetTaskStatisticsRequest.FromString,
                    response_serializer=grpc__host__pb2.GetTaskStatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_host.GrpcWorkerAgentRuntimeHost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_host.GrpcWorkerAgentRuntimeHost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcWorkerAgentRuntimeHost(object):
    """Worker registration and management
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/RegisterWorker',
            grpc__host__pb2.RegisterWorkerRequest.SerializeToString,
            grpc__host__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/UnregisterWorker',
            grpc__host__pb2.UnregisterWorkerRequest.SerializeToString,
            grpc__host__pb2.UnregisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DistributeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/DistributeTask',
            grpc__host__pb2.DistributeTaskRequest.SerializeToString,
            grpc__host__pb2.DistributeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/CollectTaskResult',
            grpc__host__pb2.CollectTaskResultRequest.SerializeToString,
            grpc__host__pb2.CollectTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/GetWorkerStatus',
            grpc__host__pb2.GetWorkerStatusRequest.SerializeToString,
            grpc__host__pb2.GetWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/GetAllWorkers',
            grpc__host__pb2.GetAllWorkersRequest.SerializeToString,
            grpc__host__pb2.GetAllWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_host.GrpcWorkerAgentRuntimeHost/GetTaskStatistics',
            grpc__host__pb2.GetTaskStatisticsRequest.SerializeToString,
            grpc__host__pb2.GetTaskStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
