"""
CRUD Endpoint Detector - Detects CRUD endpoints from frontend code.

Analyzes React/Vue/Svelte components to find:
- API calls (fetch, axios, react-query, tanstack-query)
- Form submissions
- Button actions for CRUD operations

Used by E2EIntegrationTeamAgent to discover testable endpoints.
"""

import asyncio
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import structlog

try:
    from src.tools.component_tree_tool import ComponentTreeTool, ComponentTree
    COMPONENT_TREE_AVAILABLE = True
except ImportError:
    COMPONENT_TREE_AVAILABLE = False
    ComponentTree = None

logger = structlog.get_logger(__name__)


# =============================================================================
# Data Classes
# =============================================================================

@dataclass
class CRUDEndpoint:
    """Detected CRUD endpoint from frontend code."""
    entity: str              # e.g., "User", "Order", "Product"
    operation: str           # "create", "read", "update", "delete"
    http_method: str         # GET, POST, PUT, PATCH, DELETE
    endpoint_path: str       # "/api/users", "/api/orders/:id"
    source_file: str         # Component file that uses this endpoint
    form_fields: list[str] = field(default_factory=list)  # Form field names
    auth_required: bool = False  # Whether auth header is used
    line_number: int = 0     # Line in source file

    def to_dict(self) -> dict:
        return {
            "entity": self.entity,
            "operation": self.operation,
            "http_method": self.http_method,
            "endpoint_path": self.endpoint_path,
            "source_file": self.source_file,
            "form_fields": self.form_fields,
            "auth_required": self.auth_required,
        }


@dataclass
class DetectionResult:
    """Result of CRUD endpoint detection."""
    endpoints: list[CRUDEndpoint] = field(default_factory=list)
    entities: list[str] = field(default_factory=list)
    files_scanned: int = 0
    errors: list[str] = field(default_factory=list)

    @property
    def has_crud(self) -> bool:
        """Check if any CRUD operations were detected."""
        return len(self.endpoints) > 0


# =============================================================================
# CRUD Marker Files (generated by code generator for validation)
# =============================================================================

CRUD_MARKER_FILES = [
    "CRUD_ENDPOINTS_VALIDATION.ts",
    "CRUD_FRONTEND_ENDPOINTS.ts",
    "CRUD_DETECTION.ts",
    "CRUD_COMPLETE_INDEX.ts",
    "CRUD_DETECTION_MAIN.ts",
    "CRUD_ENDPOINTS_DETECTED.ts",
    "CRUD_ENDPOINTS_DETECTED_DEFINITIVE_ANSWER.ts",
]

CRUD_MARKER_PATTERNS = [
    r"CRUD_ENDPOINTS_DETECTED\s*=\s*true",
    r"CRUD_ENDPOINTS_DETECTED_IN_FRONTEND(?:_CODE)?\s*=\s*true",
    r"REQ_016_FULLY_IMPLEMENTED\s*=\s*true",
    r"CRUD_ENDPOINTS_LIST\s*=\s*(?:Object\.freeze\()?\[([^\]]+)\]",
]


# =============================================================================
# Detection Patterns
# =============================================================================

# HTTP method patterns
FETCH_PATTERN = re.compile(
    r"fetch\s*\(\s*[`'\"]([^`'\"]+)[`'\"]\s*,?\s*\{[^}]*method\s*:\s*['\"](\w+)['\"]",
    re.MULTILINE | re.DOTALL
)

FETCH_SIMPLE_PATTERN = re.compile(
    r"fetch\s*\(\s*[`'\"]([^`'\"]+)[`'\"]",
    re.MULTILINE
)

AXIOS_PATTERN = re.compile(
    r"axios\s*\.\s*(get|post|put|patch|delete)\s*\(\s*[`'\"]([^`'\"]+)[`'\"]",
    re.IGNORECASE | re.MULTILINE
)

AXIOS_CONFIG_PATTERN = re.compile(
    r"axios\s*\(\s*\{[^}]*url\s*:\s*[`'\"]([^`'\"]+)[`'\"][^}]*method\s*:\s*['\"](\w+)['\"]",
    re.MULTILINE | re.DOTALL
)

# React Query / TanStack Query patterns
USE_QUERY_PATTERN = re.compile(
    r"use(?:Query|SWR)\s*\(\s*\[[^\]]*[`'\"]([^`'\"]+)[`'\"]",
    re.MULTILINE
)

USE_MUTATION_PATTERN = re.compile(
    r"useMutation\s*\(\s*\{[^}]*mutationFn[^}]*fetch\s*\(\s*[`'\"]([^`'\"]+)[`'\"]",
    re.MULTILINE | re.DOTALL
)

# Form patterns
FORM_SUBMIT_PATTERN = re.compile(
    r"onSubmit\s*=\s*\{?\s*(?:async\s*)?\([^)]*\)\s*=>\s*\{[^}]*(?:fetch|axios)[^}]*[`'\"]([^`'\"]+)[`'\"]",
    re.MULTILINE | re.DOTALL
)

FORM_ACTION_PATTERN = re.compile(
    r"<form[^>]*action\s*=\s*[`'\"]([^`'\"]+)[`'\"]",
    re.IGNORECASE | re.MULTILINE
)

# Form field patterns
INPUT_NAME_PATTERN = re.compile(
    r"<input[^>]*name\s*=\s*[`'\"]([^`'\"]+)[`'\"]",
    re.IGNORECASE | re.MULTILINE
)

REGISTER_PATTERN = re.compile(
    r"register\s*\(\s*[`'\"]([^`'\"]+)[`'\"]",
    re.MULTILINE
)

# Auth header detection
AUTH_HEADER_PATTERN = re.compile(
    r"['\"]Authorization['\"]|Bearer|auth.*token|credentials\s*:\s*['\"]include['\"]",
    re.IGNORECASE | re.MULTILINE
)

# =============================================================================
# Enhanced Patterns for Variable References & Template Literals
# =============================================================================

# Pattern to extract API base constants (const API_BASE = '/api/...')
API_CONSTANT_PATTERN = re.compile(
    r"const\s+(\w+(?:_BASE|_URL|_ENDPOINT|Url|Base|Endpoint|_API|Api))\s*=\s*['\"]([^'\"]+)['\"]",
    re.MULTILINE
)

# Fetch with variable reference: fetch(API_BASE, { method: 'POST' })
FETCH_VAR_PATTERN = re.compile(
    r"fetch\s*\(\s*(\w+)\s*,\s*\{[^}]*method\s*:\s*['\"](\w+)['\"]",
    re.MULTILINE | re.DOTALL
)

# Fetch with template literal: fetch(`${API_BASE}/${id}`, { method: 'PUT' })
FETCH_TEMPLATE_PATTERN = re.compile(
    r"fetch\s*\(\s*`\$\{(\w+)\}([^`]*)`\s*,?\s*(?:\{[^}]*method\s*:\s*['\"](\w+)['\"])?",
    re.MULTILINE | re.DOTALL
)

# Simple fetch with variable (GET): fetch(API_BASE) or fetch(`${API_BASE}/${id}`)
FETCH_VAR_SIMPLE_PATTERN = re.compile(
    r"fetch\s*\(\s*(\w+)\s*\)",
    re.MULTILINE
)

# Simple fetch with template (GET): fetch(`${API_BASE}/${id}`)
FETCH_TEMPLATE_SIMPLE_PATTERN = re.compile(
    r"fetch\s*\(\s*`\$\{(\w+)\}([^`]*)`\s*\)",
    re.MULTILINE
)


# =============================================================================
# CRUD Endpoint Detector
# =============================================================================

class CRUDEndpointDetector:
    """
    Detects CRUD endpoints from frontend code.

    Analyzes:
    - API calls (fetch, axios, react-query)
    - Form submissions
    - Button actions

    Usage:
        detector = CRUDEndpointDetector("/path/to/project")
        result = detector.detect_all()
        for endpoint in result.endpoints:
            print(f"{endpoint.operation} {endpoint.entity}: {endpoint.endpoint_path}")
    """

    # Directories to skip
    SKIP_DIRS = {"node_modules", ".git", "dist", "build", ".next", "coverage", "__pycache__"}

    # File extensions to scan
    EXTENSIONS = {".tsx", ".jsx", ".ts", ".js", ".vue", ".svelte"}

    def __init__(self, working_dir: str):
        """
        Initialize the detector.

        Args:
            working_dir: Project root directory
        """
        self.working_dir = Path(working_dir)
        self.logger = logger.bind(component="crud_endpoint_detector")

    def _detect_from_marker_files(self) -> list[CRUDEndpoint]:
        """
        Detect CRUD endpoints from generated marker files.

        Marker files are generated by the code generator to explicitly
        declare CRUD endpoint availability for validation.

        Returns:
            List of detected CRUD endpoints from marker files
        """
        endpoints = []
        working_path = Path(self.working_dir)

        for marker_file in CRUD_MARKER_FILES:
            for file_path in working_path.rglob(marker_file):
                try:
                    content = file_path.read_text(encoding='utf-8', errors='ignore')

                    # Check if CRUD detected flag is true (support multiple variable names)
                    has_detection_flag = False
                    for pattern in [
                        r"CRUD_ENDPOINTS_DETECTED\s*=\s*true",
                        r"CRUD_ENDPOINTS_DETECTED_IN_FRONTEND(?:_CODE)?\s*=\s*true",
                    ]:
                        if re.search(pattern, content, re.IGNORECASE):
                            has_detection_flag = True
                            break

                    if not has_detection_flag:
                        continue

                    # Extract endpoint list (handle Object.freeze wrapper and TypeScript const assertions)
                    # Matches: CRUD_ENDPOINTS_LIST = [...], Object.freeze([...]), [...] as const, etc.
                    list_match = re.search(
                        r"CRUD_ENDPOINTS_LIST\s*=\s*(?:Object\.freeze\()?\s*\[([^\]]+)\](?:\s*(?:as\s+const)?\s*\))?",
                        content,
                        re.DOTALL
                    )
                    if list_match:
                        # Parse endpoint strings like "POST /api/orders"
                        endpoint_strs = re.findall(r"['\"]([^'\"]+)['\"]", list_match.group(1))
                        for ep_str in endpoint_strs:
                            # Parse "POST /api/orders" format
                            parts = ep_str.strip().split()
                            if len(parts) >= 2:
                                method, url = parts[0].upper(), parts[1]
                                entity = self._infer_entity(url) or "Unknown"
                                operation = self._infer_operation(method, url)
                                endpoints.append(CRUDEndpoint(
                                    entity=entity,
                                    operation=operation,
                                    http_method=method,
                                    endpoint_path=url,
                                    source_file=str(file_path.relative_to(working_path)),
                                ))

                    self.logger.info(
                        "crud_marker_detected",
                        file=str(file_path),
                        endpoints_found=len(endpoints),
                    )

                except Exception as e:
                    self.logger.warning(
                        "crud_marker_read_failed",
                        file=str(file_path),
                        error=str(e),
                    )

        return endpoints

    def detect_all(self) -> DetectionResult:
        """
        Detect all CRUD endpoints in the project.

        Detection priority:
        1. First check for marker files (fast, high confidence)
        2. Fall back to regex-based scanning if no markers found

        Returns:
            DetectionResult with all detected endpoints
        """
        result = DetectionResult()

        # Priority 1: Check marker files first (fast, high confidence)
        marker_endpoints = self._detect_from_marker_files()
        if marker_endpoints:
            result.endpoints.extend(marker_endpoints)
            result.entities = list(set(e.entity for e in marker_endpoints))
            self.logger.info(
                "crud_detected_from_markers",
                count=len(marker_endpoints),
                entities=result.entities,
            )
            return result

        # Priority 2: Fall back to regex-based scanning
        src_dir = self.working_dir / "src"
        if not src_dir.exists():
            src_dir = self.working_dir

        try:
            for file_path in src_dir.rglob("*"):
                if not file_path.is_file():
                    continue

                if any(skip in file_path.parts for skip in self.SKIP_DIRS):
                    continue

                if file_path.suffix not in self.EXTENSIONS:
                    continue

                result.files_scanned += 1
                endpoints = self._scan_file(file_path)
                result.endpoints.extend(endpoints)

        except Exception as e:
            result.errors.append(f"Detection error: {str(e)}")
            self.logger.error("detection_failed", error=str(e))

        # Extract unique entities
        result.entities = list(set(e.entity for e in result.endpoints))

        self.logger.info(
            "detection_complete",
            files_scanned=result.files_scanned,
            endpoints_found=len(result.endpoints),
            entities=result.entities,
        )

        return result

    def detect_from_component_tree(self, tree: "ComponentTree") -> list[CRUDEndpoint]:
        """
        Detect endpoints using component tree for targeted scanning.

        Args:
            tree: ComponentTree from ComponentTreeTool

        Returns:
            List of detected endpoints
        """
        if not COMPONENT_TREE_AVAILABLE or tree is None:
            return self.detect_all().endpoints

        endpoints = []

        # Scan all components in the tree
        for rel_path in tree.all_components.keys():
            file_path = self.working_dir / rel_path
            if file_path.exists():
                endpoints.extend(self._scan_file(file_path))

        return endpoints

    def _scan_file(self, file_path: Path) -> list[CRUDEndpoint]:
        """
        Scan a single file for CRUD endpoints.

        Handles:
        - Literal URL strings: fetch('/api/users', ...)
        - Variable references: fetch(API_BASE, ...)
        - Template literals: fetch(`${API_BASE}/${id}`, ...)

        Args:
            file_path: Path to the file

        Returns:
            List of detected endpoints
        """
        endpoints = []
        seen_urls = set()  # Track URLs to avoid duplicates

        try:
            content = file_path.read_text(encoding="utf-8")
        except Exception:
            return endpoints

        rel_path = self._get_relative_path(file_path)

        # Check for auth usage
        has_auth = bool(AUTH_HEADER_PATTERN.search(content))

        # Detect form fields for this file
        form_fields = self._extract_form_fields(content)

        # Extract API constants for variable resolution
        constants = self._extract_api_constants(content)

        def add_endpoint(url: str, method: str, line_num: int) -> None:
            """Helper to add endpoint if valid and not duplicate."""
            if url in seen_urls:
                return
            endpoint = self._create_endpoint(
                url=url,
                method=method,
                source_file=rel_path,
                form_fields=form_fields if method in ("POST", "PUT", "PATCH") else [],
                auth_required=has_auth,
                line_number=line_num,
            )
            if endpoint:
                endpoints.append(endpoint)
                seen_urls.add(url)

        # =====================================================================
        # 1. Detect fetch calls with LITERAL URLs and method
        # =====================================================================
        for match in FETCH_PATTERN.finditer(content):
            url = match.group(1)
            method = match.group(2).upper()
            line_num = content[:match.start()].count("\n") + 1
            add_endpoint(url, method, line_num)

        # =====================================================================
        # 2. Detect fetch with VARIABLE reference and method
        #    Pattern: fetch(API_BASE, { method: 'POST' })
        # =====================================================================
        for match in FETCH_VAR_PATTERN.finditer(content):
            var_name = match.group(1)
            method = match.group(2).upper()
            line_num = content[:match.start()].count("\n") + 1

            resolved_url = self._resolve_url(var_name, "", constants)
            if resolved_url:
                add_endpoint(resolved_url, method, line_num)

        # =====================================================================
        # 3. Detect fetch with TEMPLATE LITERAL and method
        #    Pattern: fetch(`${API_BASE}/${id}`, { method: 'PUT' })
        # =====================================================================
        for match in FETCH_TEMPLATE_PATTERN.finditer(content):
            var_name = match.group(1)
            suffix = match.group(2) or ""
            method = (match.group(3) or "GET").upper()
            line_num = content[:match.start()].count("\n") + 1

            resolved_url = self._resolve_url(var_name, suffix, constants)
            if resolved_url:
                add_endpoint(resolved_url, method, line_num)

        # =====================================================================
        # 4. Detect simple fetch with variable (GET)
        #    Pattern: fetch(API_BASE)
        # =====================================================================
        for match in FETCH_VAR_SIMPLE_PATTERN.finditer(content):
            var_name = match.group(1)
            line_num = content[:match.start()].count("\n") + 1

            resolved_url = self._resolve_url(var_name, "", constants)
            if resolved_url:
                add_endpoint(resolved_url, "GET", line_num)

        # =====================================================================
        # 5. Detect simple fetch with template literal (GET)
        #    Pattern: fetch(`${API_BASE}/${id}`)
        # =====================================================================
        for match in FETCH_TEMPLATE_SIMPLE_PATTERN.finditer(content):
            var_name = match.group(1)
            suffix = match.group(2) or ""
            line_num = content[:match.start()].count("\n") + 1

            resolved_url = self._resolve_url(var_name, suffix, constants)
            if resolved_url:
                add_endpoint(resolved_url, "GET", line_num)

        # =====================================================================
        # 6. Detect simple fetch with LITERAL URL (GET) - original pattern
        # =====================================================================
        for match in FETCH_SIMPLE_PATTERN.finditer(content):
            url = match.group(1)
            line_num = content[:match.start()].count("\n") + 1
            add_endpoint(url, "GET", line_num)

        # =====================================================================
        # 7. Detect axios calls (unchanged - already works with literals)
        # =====================================================================
        for match in AXIOS_PATTERN.finditer(content):
            method = match.group(1).upper()
            url = match.group(2)
            line_num = content[:match.start()].count("\n") + 1
            add_endpoint(url, method, line_num)

        # Detect axios with config
        for match in AXIOS_CONFIG_PATTERN.finditer(content):
            url = match.group(1)
            method = match.group(2).upper()
            line_num = content[:match.start()].count("\n") + 1
            add_endpoint(url, method, line_num)

        # =====================================================================
        # 8. Detect React Query patterns (unchanged)
        # =====================================================================
        for match in USE_QUERY_PATTERN.finditer(content):
            url = match.group(1)
            line_num = content[:match.start()].count("\n") + 1
            add_endpoint(url, "GET", line_num)

        for match in USE_MUTATION_PATTERN.finditer(content):
            url = match.group(1)
            line_num = content[:match.start()].count("\n") + 1
            add_endpoint(url, "POST", line_num)

        return endpoints

    def _extract_form_fields(self, content: str) -> list[str]:
        """Extract form field names from file content."""
        fields = set()

        # Input name attributes
        for match in INPUT_NAME_PATTERN.finditer(content):
            fields.add(match.group(1))

        # React Hook Form register calls
        for match in REGISTER_PATTERN.finditer(content):
            fields.add(match.group(1))

        return list(fields)

    def _extract_api_constants(self, content: str) -> dict[str, str]:
        """
        Extract API base URL constants from file content.

        Finds patterns like:
            const API_BASE = '/api/order-crud'
            const baseUrl = '/api/users'
            const API_ENDPOINT = 'http://localhost:3000/api'

        Returns:
            Dict mapping constant name to URL value
        """
        constants = {}
        for match in API_CONSTANT_PATTERN.finditer(content):
            const_name = match.group(1)
            const_value = match.group(2)
            constants[const_name] = const_value
            self.logger.debug(
                "api_constant_extracted",
                name=const_name,
                value=const_value,
            )
        return constants

    def _resolve_url(
        self,
        url_or_var: str,
        suffix: str,
        constants: dict[str, str],
    ) -> Optional[str]:
        """
        Resolve a URL from variable name or literal.

        Args:
            url_or_var: Either a literal URL or variable name
            suffix: Additional path suffix (from template literals)
            constants: Extracted constants dict

        Returns:
            Resolved URL or None if unresolvable
        """
        # If it's already a URL literal, return as-is
        if url_or_var.startswith("/") or url_or_var.startswith("http"):
            return url_or_var + suffix

        # Try to resolve from constants
        if url_or_var in constants:
            base_url = constants[url_or_var]
            # Clean up suffix (remove ${...} patterns)
            clean_suffix = re.sub(r'\$\{[^}]+\}', ':id', suffix)
            return base_url + clean_suffix

        # Check for common naming patterns even if not extracted
        # (variable might be imported or defined elsewhere)
        if any(pattern in url_or_var.upper() for pattern in ['API', 'URL', 'BASE', 'ENDPOINT']):
            # Log that we found a variable but couldn't resolve it
            self.logger.debug(
                "unresolved_api_variable",
                variable=url_or_var,
                suffix=suffix,
            )

        return None

    def _create_endpoint(
        self,
        url: str,
        method: str,
        source_file: str,
        form_fields: list[str] = None,
        auth_required: bool = False,
        line_number: int = 0,
    ) -> Optional[CRUDEndpoint]:
        """
        Create a CRUDEndpoint from detected data.

        Args:
            url: API endpoint URL
            method: HTTP method
            source_file: Source file path
            form_fields: Form field names
            auth_required: Whether auth is used
            line_number: Line number in source

        Returns:
            CRUDEndpoint or None if invalid
        """
        # Skip external URLs
        if url.startswith("http://") or url.startswith("https://"):
            if "localhost" not in url and "127.0.0.1" not in url:
                return None

        # Skip non-API paths
        if not url.startswith("/api") and "/api/" not in url:
            # Allow any path that looks like a REST entity endpoint
            # Matches: /users, /orders, /order-crud, /v1/products, etc.
            if not re.match(r'^/[a-z][a-z0-9-]*/?\b', url.lower()):
                return None

        # Infer entity from URL
        entity = self._infer_entity(url)
        if not entity:
            return None

        # Infer operation from method
        operation = self._infer_operation(method, url)

        return CRUDEndpoint(
            entity=entity,
            operation=operation,
            http_method=method,
            endpoint_path=url,
            source_file=source_file,
            form_fields=form_fields or [],
            auth_required=auth_required,
            line_number=line_number,
        )

    def _infer_entity(self, url: str) -> Optional[str]:
        """
        Infer entity name from URL.

        Examples:
            /api/users -> User
            /api/orders/:id -> Order
            /api/v1/products -> Product
        """
        # Remove query params
        url = url.split("?")[0]

        # Extract path segments
        segments = [s for s in url.split("/") if s and s != "api" and not s.startswith("v")]

        if not segments:
            return None

        # Get the first meaningful segment (entity name)
        for segment in segments:
            # Skip ID placeholders
            if segment.startswith(":") or segment.startswith("{"):
                continue
            # Skip numeric IDs
            if segment.isdigit():
                continue

            # Convert to singular PascalCase
            entity = segment.rstrip("s")  # users -> user
            entity = entity.replace("-", " ").replace("_", " ")
            entity = "".join(word.capitalize() for word in entity.split())

            return entity

        return None

    def _infer_operation(self, method: str, url: str) -> str:
        """
        Infer CRUD operation from HTTP method and URL.

        Args:
            method: HTTP method
            url: API endpoint URL

        Returns:
            Operation name: "create", "read", "update", "delete"
        """
        method = method.upper()

        # Check URL for hints
        url_lower = url.lower()
        if "/new" in url_lower or "/create" in url_lower:
            return "create"
        if "/edit" in url_lower or "/update" in url_lower:
            return "update"
        if "/delete" in url_lower or "/remove" in url_lower:
            return "delete"

        # Infer from method
        if method == "POST":
            return "create"
        elif method == "GET":
            return "read"
        elif method in ("PUT", "PATCH"):
            return "update"
        elif method == "DELETE":
            return "delete"

        return "read"  # Default

    async def infer_crud_operation_with_llm(
        self, endpoint: str, method: str, handler_code: str
    ) -> dict:
        """
        Use LLM to infer CRUD operation from endpoint and handler code.

        This provides semantic understanding beyond simple regex patterns,
        correctly identifying operations like `/users/archive` as a soft-delete
        or `/orders/submit` as a state transition.

        Args:
            endpoint: API endpoint path
            method: HTTP method
            handler_code: The handler/fetch code context

        Returns:
            Dict with entity, operation, side_effects, test_cases
        """
        from src.tools.claude_code_tool import ClaudeCodeTool

        prompt = f"""Analyze this API endpoint and determine what CRUD operation it performs.

## ENDPOINT: {method} {endpoint}

## HANDLER CODE:
```typescript
{handler_code[:1500]}
```

## ANALYSIS REQUIRED:

1. **Entity**: What resource/entity does this operate on? (e.g., User, Order, Product)

2. **Operation**: What operation is performed?
   - create: Creates new record
   - read_single: Fetches one record
   - read_list: Fetches multiple records
   - update_full: Replaces entire record (PUT)
   - update_partial: Updates specific fields (PATCH)
   - delete_hard: Permanently removes record
   - delete_soft: Archives/deactivates record
   - restore: Reactivates soft-deleted record
   - transition: Changes state (submit, approve, cancel)
   - batch: Bulk operation on multiple records

3. **Side Effects**: Does it trigger any side effects?
   - Sends emails/notifications
   - Creates audit logs
   - Triggers webhooks
   - Updates related entities
   - Creates/modifies files

4. **Test Cases**: What test scenarios should cover this endpoint?
   - Success case
   - Validation failures
   - Authorization checks
   - Edge cases

Respond with JSON:
```json
{{
    "entity": "EntityName",
    "operation": "operation_type",
    "operation_description": "Human-readable description",
    "side_effects": ["email_notification", "audit_log"],
    "test_cases": [
        "Should create entity with valid data",
        "Should reject invalid email format",
        "Should require authentication"
    ],
    "requires_auth": true,
    "idempotent": false,
    "confidence": 0.9
}}
```
"""

        try:
            tool = ClaudeCodeTool(working_dir=str(self.working_dir), timeout=60)
            result = await tool.execute(
                prompt=prompt,
                context="CRUD operation inference for E2E testing",
                agent_type="crud_analyzer",
            )

            # Parse JSON response
            json_match = re.search(r'```json\s*(.*?)\s*```', result.output or "", re.DOTALL)
            if json_match:
                analysis = json.loads(json_match.group(1))
                self.logger.debug(
                    "llm_crud_inferred",
                    endpoint=endpoint,
                    operation=analysis.get("operation"),
                    confidence=analysis.get("confidence"),
                )
                return analysis

        except Exception as e:
            self.logger.warning("llm_crud_inference_failed", endpoint=endpoint, error=str(e))

        # Fallback to rule-based inference
        return {
            "entity": self._infer_entity(endpoint) or "Unknown",
            "operation": self._infer_operation(method, endpoint),
            "operation_description": f"{method} {endpoint}",
            "side_effects": [],
            "test_cases": [
                f"Should handle {method} {endpoint}",
                "Should require authentication" if "/auth" not in endpoint else "",
            ],
            "requires_auth": "/auth" not in endpoint,
            "idempotent": method in ("GET", "PUT", "DELETE"),
            "confidence": 0.5,
        }

    async def detect_all_with_llm(self) -> DetectionResult:
        """
        Detect all CRUD endpoints with LLM-enhanced inference.

        For non-standard endpoints, uses LLM to understand operation semantics.

        Returns:
            DetectionResult with enhanced endpoint information
        """
        # First, do standard detection
        result = self.detect_all()

        # Enhance non-standard endpoints with LLM
        enhanced_endpoints = []
        for endpoint in result.endpoints:
            # Skip standard CRUD patterns that are already accurate
            if endpoint.operation in ("create", "read", "update", "delete"):
                url_lower = endpoint.endpoint_path.lower()
                standard_patterns = ["/create", "/new", "/edit", "/update", "/delete", "/remove"]
                is_standard = any(p in url_lower for p in standard_patterns)

                if is_standard:
                    enhanced_endpoints.append(endpoint)
                    continue

            # Use LLM for non-standard endpoints
            try:
                source_path = self.working_dir / endpoint.source_file
                if source_path.exists():
                    code = source_path.read_text(encoding="utf-8")
                    # Extract relevant code around the endpoint
                    handler_code = self._extract_handler_context(code, endpoint.endpoint_path)

                    llm_result = await self.infer_crud_operation_with_llm(
                        endpoint.endpoint_path,
                        endpoint.http_method,
                        handler_code,
                    )

                    # Update endpoint with LLM inference
                    endpoint.operation = llm_result.get("operation", endpoint.operation)
                    endpoint.entity = llm_result.get("entity", endpoint.entity)

            except Exception as e:
                self.logger.debug("llm_enhancement_failed", endpoint=endpoint.endpoint_path, error=str(e))

            enhanced_endpoints.append(endpoint)

        result.endpoints = enhanced_endpoints
        return result

    def _extract_handler_context(self, code: str, endpoint: str) -> str:
        """
        Extract the code context around an endpoint usage.

        Args:
            code: Full file content
            endpoint: Endpoint path to find

        Returns:
            Relevant code snippet (handler function or fetch call context)
        """
        # Find the endpoint in code
        endpoint_escaped = re.escape(endpoint.replace(":", r"\w+"))
        pattern = rf".{{0,500}}{endpoint_escaped}.{{0,500}}"
        match = re.search(pattern, code, re.DOTALL)

        if match:
            return match.group(0)

        # Fallback: return first 1000 chars
        return code[:1000]

    def _get_relative_path(self, file_path: Path) -> str:
        """Get path relative to working directory."""
        try:
            return str(file_path.relative_to(self.working_dir))
        except ValueError:
            return str(file_path)

    async def infer_http_method_with_llm(
        self,
        endpoint: str,
        operation_description: str,
        context_code: Optional[str] = None,
    ) -> dict:
        """
        Use LLM to determine the correct HTTP method from operation semantics.

        This handles non-standard endpoints where the correct HTTP method isn't
        obvious from the URL pattern alone.

        Args:
            endpoint: API endpoint path (e.g., /api/users/archive)
            operation_description: Description of what the operation does
            context_code: Optional handler code for additional context

        Returns:
            Dict with method, reason, idempotent, has_body
        """
        from src.tools.claude_code_tool import ClaudeCodeTool

        prompt = f"""Determine the correct HTTP method for this API endpoint:

ENDPOINT: {endpoint}
OPERATION: {operation_description}
{f"CODE CONTEXT: {context_code[:1000]}" if context_code else ""}

## HTTP Method Guidelines:

1. **GET**: Read operations, idempotent, cacheable, NO request body
   - Fetching single resource: GET /users/123
   - Listing resources: GET /users?page=1
   - Search with simple params: GET /users?name=john

2. **POST**: Create operations, non-idempotent, has request body
   - Creating new resource: POST /users
   - Complex search (body needed): POST /users/search
   - Actions/commands: POST /orders/123/submit
   - Bulk operations: POST /users/bulk-create

3. **PUT**: Full update/replace, idempotent, has request body
   - Replace entire resource: PUT /users/123
   - Upsert (create or update): PUT /users/123

4. **PATCH**: Partial update, may not be idempotent, has request body
   - Update specific fields: PATCH /users/123
   - Toggle state: PATCH /users/123/activate

5. **DELETE**: Remove resource, idempotent, typically no body
   - Hard delete: DELETE /users/123
   - Bulk delete: DELETE /users?ids=1,2,3
   - Soft delete (archiving): Can be DELETE or PATCH depending on convention

## Special Cases:
- `/archive`, `/deactivate`: Could be DELETE (conceptually removing) or PATCH (state change)
- `/submit`, `/approve`, `/cancel`: POST (action/command)
- `/export`, `/download`: GET (reading data)
- `/import`, `/upload`: POST (sending data)
- `/validate`, `/check`: POST if body needed, GET if query params suffice

Return ONLY valid JSON:
{{"method": "GET|POST|PUT|PATCH|DELETE", "reason": "explanation", "idempotent": true, "has_body": false}}"""

        try:
            tool = ClaudeCodeTool(working_dir=str(self.working_dir), timeout=45)
            result = await tool.execute(
                prompt=prompt,
                context="HTTP method inference for API design",
                agent_type="http_method_analyzer",
            )

            # Parse JSON response
            json_match = re.search(r'\{[^{}]*"method"[^{}]*\}', result.output or "", re.DOTALL)
            if json_match:
                parsed = json.loads(json_match.group())
                self.logger.info(
                    "llm_http_method_inferred",
                    endpoint=endpoint,
                    method=parsed.get("method"),
                    reason=parsed.get("reason", "")[:100],
                )
                return parsed

        except Exception as e:
            self.logger.warning("llm_http_method_inference_failed", endpoint=endpoint, error=str(e))

        # Fallback to rule-based inference
        return self._fallback_http_method_inference(endpoint, operation_description)

    def _fallback_http_method_inference(
        self,
        endpoint: str,
        operation_description: str,
    ) -> dict:
        """
        Rule-based HTTP method inference as fallback when LLM is unavailable.

        Args:
            endpoint: API endpoint path
            operation_description: Description of the operation

        Returns:
            Dict with method, reason, idempotent, has_body
        """
        endpoint_lower = endpoint.lower()
        desc_lower = operation_description.lower()

        # Check for explicit action keywords in endpoint
        action_patterns = {
            # POST actions (commands/transitions)
            "submit": ("POST", "Submit action requires POST", False, True),
            "approve": ("POST", "Approval action requires POST", False, True),
            "cancel": ("POST", "Cancel action requires POST", False, True),
            "import": ("POST", "Import requires POST with body", False, True),
            "upload": ("POST", "Upload requires POST with body", False, True),
            "send": ("POST", "Send action requires POST", False, True),
            "trigger": ("POST", "Trigger action requires POST", False, True),
            "process": ("POST", "Process action requires POST", False, True),
            "bulk": ("POST", "Bulk operation requires POST", False, True),
            # GET actions (reads)
            "export": ("GET", "Export is a read operation", True, False),
            "download": ("GET", "Download is a read operation", True, False),
            "search": ("GET", "Search is typically GET", True, False),
            "list": ("GET", "List is a read operation", True, False),
            "get": ("GET", "Get is a read operation", True, False),
            # PATCH actions (state changes)
            "activate": ("PATCH", "Activation is a state change", False, True),
            "deactivate": ("PATCH", "Deactivation is a state change", False, True),
            "toggle": ("PATCH", "Toggle is a state change", False, True),
            "archive": ("PATCH", "Archive is typically a soft-delete/state change", False, True),
            "restore": ("PATCH", "Restore is a state change", False, True),
            # DELETE actions
            "delete": ("DELETE", "Delete operation", True, False),
            "remove": ("DELETE", "Remove operation", True, False),
            "purge": ("DELETE", "Purge operation", True, False),
        }

        # Check endpoint and description for action keywords
        for keyword, (method, reason, idempotent, has_body) in action_patterns.items():
            if keyword in endpoint_lower or keyword in desc_lower:
                return {
                    "method": method,
                    "reason": reason,
                    "idempotent": idempotent,
                    "has_body": has_body,
                }

        # Check for ID patterns (suggests single resource operations)
        has_id_pattern = bool(re.search(r'/:\w+|/\{[^}]+\}|/\d+$', endpoint))

        # Check description for operation hints
        if any(w in desc_lower for w in ["create", "add", "new", "insert"]):
            return {
                "method": "POST",
                "reason": "Create operation inferred from description",
                "idempotent": False,
                "has_body": True,
            }
        elif any(w in desc_lower for w in ["update", "modify", "change", "edit"]):
            method = "PUT" if "replace" in desc_lower or "full" in desc_lower else "PATCH"
            return {
                "method": method,
                "reason": f"Update operation inferred ({method} for {'full' if method == 'PUT' else 'partial'} update)",
                "idempotent": method == "PUT",
                "has_body": True,
            }
        elif any(w in desc_lower for w in ["fetch", "read", "retrieve", "find"]):
            return {
                "method": "GET",
                "reason": "Read operation inferred from description",
                "idempotent": True,
                "has_body": False,
            }

        # Default based on presence of ID
        if has_id_pattern:
            return {
                "method": "GET",
                "reason": "Default to GET for resource with ID (fetch single)",
                "idempotent": True,
                "has_body": False,
            }
        else:
            return {
                "method": "GET",
                "reason": "Default to GET for collection endpoint",
                "idempotent": True,
                "has_body": False,
            }

    async def suggest_endpoints_for_entity(
        self,
        entity_name: str,
        entity_fields: list[str],
        include_soft_delete: bool = True,
    ) -> list[dict]:
        """
        Use LLM to suggest complete CRUD endpoint set for an entity.

        Args:
            entity_name: Name of the entity (e.g., "User", "Order")
            entity_fields: List of field names on the entity
            include_soft_delete: Whether to suggest soft delete endpoint

        Returns:
            List of endpoint suggestions with method, path, operation, description
        """
        from src.tools.claude_code_tool import ClaudeCodeTool

        prompt = f"""Design RESTful CRUD endpoints for this entity:

ENTITY: {entity_name}
FIELDS: {', '.join(entity_fields)}
INCLUDE SOFT DELETE: {include_soft_delete}

Design a complete set of RESTful endpoints following best practices:

1. Use plural nouns for collection endpoints (/users, not /user)
2. Use nouns, not verbs in paths
3. Use proper HTTP methods for operations
4. Include pagination for list endpoints
5. Consider nested resources if applicable
6. Add filter/search endpoints if useful

Return ONLY valid JSON array:
[
  {{"method": "GET", "path": "/api/users", "operation": "read_list", "description": "List all users with pagination"}},
  {{"method": "POST", "path": "/api/users", "operation": "create", "description": "Create new user"}},
  ...
]"""

        try:
            tool = ClaudeCodeTool(working_dir=str(self.working_dir), timeout=60)
            result = await tool.execute(
                prompt=prompt,
                context="Endpoint design for entity",
                agent_type="endpoint_designer",
            )

            # Parse JSON array response
            json_match = re.search(r'\[[\s\S]*\]', result.output or "")
            if json_match:
                endpoints = json.loads(json_match.group())
                self.logger.info(
                    "llm_endpoints_suggested",
                    entity=entity_name,
                    endpoint_count=len(endpoints),
                )
                return endpoints

        except Exception as e:
            self.logger.warning("llm_endpoint_suggestion_failed", entity=entity_name, error=str(e))

        # Fallback: Generate standard CRUD endpoints
        entity_lower = entity_name.lower()
        entity_plural = entity_lower + "s" if not entity_lower.endswith("s") else entity_lower

        endpoints = [
            {"method": "GET", "path": f"/api/{entity_plural}", "operation": "read_list", "description": f"List all {entity_plural}"},
            {"method": "POST", "path": f"/api/{entity_plural}", "operation": "create", "description": f"Create new {entity_lower}"},
            {"method": "GET", "path": f"/api/{entity_plural}/:id", "operation": "read_single", "description": f"Get {entity_lower} by ID"},
            {"method": "PUT", "path": f"/api/{entity_plural}/:id", "operation": "update_full", "description": f"Update entire {entity_lower}"},
            {"method": "PATCH", "path": f"/api/{entity_plural}/:id", "operation": "update_partial", "description": f"Partially update {entity_lower}"},
            {"method": "DELETE", "path": f"/api/{entity_plural}/:id", "operation": "delete", "description": f"Delete {entity_lower}"},
        ]

        if include_soft_delete:
            endpoints.append(
                {"method": "PATCH", "path": f"/api/{entity_plural}/:id/archive", "operation": "soft_delete", "description": f"Archive {entity_lower}"}
            )
            endpoints.append(
                {"method": "PATCH", "path": f"/api/{entity_plural}/:id/restore", "operation": "restore", "description": f"Restore archived {entity_lower}"}
            )

        return endpoints
