"""
Ollama Tool - Local LLM inference using Ollama.

This tool provides a similar interface to ClaudeCodeTool but uses
a local Ollama model instead of Claude API.

Key differences:
- Runs locally (no API costs, no rate limits)
- Supports any Ollama model (codellama, deepseek-coder, mistral, etc.)
- No external API calls (works offline)
- Faster inference for local hardware with GPUs

Usage:
    tool = OllamaTool(model="codellama:34b")
    result = await tool.execute("Generate a Python script that...")
"""

import asyncio
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Any
import structlog

logger = structlog.get_logger(__name__)


@dataclass
class GeneratedFile:
    """A file generated by the LLM."""
    path: str
    content: str
    language: str = ""


@dataclass
class OllamaGenerationResult:
    """Result from Ollama code generation."""
    success: bool
    files: list[GeneratedFile] = field(default_factory=list)
    response: str = ""
    output: str = ""
    error: Optional[str] = None
    execution_time_ms: int = 0
    model: str = ""
    tokens_evaluated: int = 0
    tokens_generated: int = 0

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "files": [{"path": f.path, "language": f.language, "lines": len(f.content.splitlines())} for f in self.files],
            "response": self.response[:500] if self.response else "",
            "output": self.output[:500] if self.output else "",
            "error": self.error,
            "execution_time_ms": self.execution_time_ms,
            "model": self.model,
            "tokens_evaluated": self.tokens_evaluated,
            "tokens_generated": self.tokens_generated,
        }


class OllamaTool:
    """
    Tool that wraps Ollama API for local LLM inference.

    This provides a similar interface to ClaudeCodeTool but uses
    a local Ollama model. Perfect for:
    - Offline development
    - Cost-free inference
    - Privacy-sensitive operations
    - Fast local iteration

    Recommended models for code:
    - codellama:34b - Best for code generation
    - deepseek-coder:33b - Great for complex tasks
    - mistral:7b - Fast, good for simple tasks
    - qwen2.5-coder:32b - Excellent code understanding
    """

    # Default Ollama API endpoint
    DEFAULT_BASE_URL = "http://localhost:11434"

    def __init__(
        self,
        model: str = "codellama:34b",
        base_url: Optional[str] = None,
        working_dir: Optional[str] = None,
        timeout: int = 300,  # 5 minutes for large generations
        temperature: float = 0.1,  # Low temp for deterministic code
        num_ctx: int = 8192,  # Context window
        num_predict: int = 4096,  # Max tokens to generate
        top_p: float = 0.9,
        repeat_penalty: float = 1.1,
    ):
        """
        Initialize Ollama Tool.

        Args:
            model: Ollama model name (e.g., "codellama:34b", "deepseek-coder:33b")
            base_url: Ollama API base URL (default: http://localhost:11434)
            working_dir: Working directory for file operations
            timeout: Request timeout in seconds
            temperature: Sampling temperature (lower = more deterministic)
            num_ctx: Context window size
            num_predict: Maximum tokens to generate
            top_p: Top-p sampling parameter
            repeat_penalty: Penalty for repetition
        """
        self.model = model
        self.base_url = (base_url or self.DEFAULT_BASE_URL).rstrip("/")
        self.working_dir = working_dir
        self.timeout = timeout
        self.temperature = temperature
        self.num_ctx = num_ctx
        self.num_predict = num_predict
        self.top_p = top_p
        self.repeat_penalty = repeat_penalty

        self.logger = logger.bind(tool="ollama", model=model)

        # Lazy import aiohttp
        self._aiohttp = None

    async def _get_aiohttp(self):
        """Lazy import aiohttp."""
        if self._aiohttp is None:
            try:
                import aiohttp
                self._aiohttp = aiohttp
            except ImportError:
                raise ImportError(
                    "aiohttp is required for OllamaTool. "
                    "Install with: pip install aiohttp"
                )
        return self._aiohttp

    async def check_available(self) -> bool:
        """
        Check if Ollama is available and the model is loaded.

        Returns:
            True if Ollama is running and model is available
        """
        aiohttp = await self._get_aiohttp()

        try:
            async with aiohttp.ClientSession() as session:
                # Check if Ollama is running
                async with session.get(
                    f"{self.base_url}/api/tags",
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    if resp.status != 200:
                        return False

                    data = await resp.json()
                    models = [m.get("name", "") for m in data.get("models", [])]

                    # Check if our model is available
                    model_base = self.model.split(":")[0]
                    for m in models:
                        if m.startswith(model_base):
                            return True

                    self.logger.warning(
                        "model_not_found",
                        model=self.model,
                        available=models,
                    )
                    return False
        except Exception as e:
            self.logger.error("ollama_check_failed", error=str(e))
            return False

    async def pull_model(self) -> bool:
        """
        Pull the model if not available locally.

        Returns:
            True if model is now available
        """
        aiohttp = await self._get_aiohttp()

        self.logger.info("pulling_model", model=self.model)

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self.base_url}/api/pull",
                    json={"name": self.model},
                    timeout=aiohttp.ClientTimeout(total=3600),  # 1 hour for large models
                ) as resp:
                    if resp.status != 200:
                        return False

                    # Stream progress
                    async for line in resp.content:
                        if line:
                            try:
                                data = json.loads(line)
                                status = data.get("status", "")
                                if "pulling" in status.lower():
                                    self.logger.info("pull_progress", status=status)
                            except json.JSONDecodeError:
                                pass

                    return True
        except Exception as e:
            self.logger.error("model_pull_failed", error=str(e))
            return False

    async def execute(
        self,
        prompt: str,
        context: Optional[str] = None,
        agent_type: str = "general",
        system_prompt: Optional[str] = None,
    ) -> OllamaGenerationResult:
        """
        Execute code generation via Ollama.

        Args:
            prompt: The code generation prompt
            context: Additional context (contracts, types, etc.)
            agent_type: Type of agent for specialized prompts
            system_prompt: Custom system prompt (overrides agent_type)

        Returns:
            OllamaGenerationResult with generated files
        """
        import time
        start_time = time.time()

        # Build full prompt
        full_prompt = self._build_prompt(prompt, context, agent_type)

        # Get system prompt
        if system_prompt is None:
            system_prompt = self._get_system_prompt(agent_type)

        self.logger.info(
            "executing_generation",
            agent_type=agent_type,
            prompt_length=len(full_prompt),
        )

        try:
            aiohttp = await self._get_aiohttp()

            async with aiohttp.ClientSession() as session:
                payload = {
                    "model": self.model,
                    "prompt": full_prompt,
                    "system": system_prompt,
                    "stream": False,
                    "options": {
                        "temperature": self.temperature,
                        "num_ctx": self.num_ctx,
                        "num_predict": self.num_predict,
                        "top_p": self.top_p,
                        "repeat_penalty": self.repeat_penalty,
                    },
                }

                async with session.post(
                    f"{self.base_url}/api/generate",
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=self.timeout),
                ) as resp:
                    if resp.status != 200:
                        error_text = await resp.text()
                        return OllamaGenerationResult(
                            success=False,
                            error=f"Ollama API error: {resp.status} - {error_text}",
                            model=self.model,
                        )

                    data = await resp.json()
                    response_text = data.get("response", "")

                    # Parse files from response
                    files = self._parse_files_from_response(response_text)

                    # Write files if working_dir is set
                    if self.working_dir and files:
                        await self._write_files(files)

                    execution_time = int((time.time() - start_time) * 1000)

                    result = OllamaGenerationResult(
                        success=True,
                        files=files,
                        response=response_text,
                        output=response_text,
                        execution_time_ms=execution_time,
                        model=self.model,
                        tokens_evaluated=data.get("prompt_eval_count", 0),
                        tokens_generated=data.get("eval_count", 0),
                    )

                    self.logger.info(
                        "generation_complete",
                        success=True,
                        files_generated=len(files),
                        tokens_in=result.tokens_evaluated,
                        tokens_out=result.tokens_generated,
                        time_ms=execution_time,
                    )

                    return result

        except asyncio.TimeoutError:
            return OllamaGenerationResult(
                success=False,
                error=f"Timeout after {self.timeout}s",
                model=self.model,
                execution_time_ms=int((time.time() - start_time) * 1000),
            )
        except Exception as e:
            self.logger.error("generation_failed", error=str(e))
            return OllamaGenerationResult(
                success=False,
                error=str(e),
                model=self.model,
                execution_time_ms=int((time.time() - start_time) * 1000),
            )

    async def chat(
        self,
        messages: list[dict[str, str]],
        system_prompt: Optional[str] = None,
    ) -> OllamaGenerationResult:
        """
        Chat completion with message history.

        Args:
            messages: List of {"role": "user/assistant", "content": "..."}
            system_prompt: Optional system prompt

        Returns:
            OllamaGenerationResult
        """
        import time
        start_time = time.time()

        try:
            aiohttp = await self._get_aiohttp()

            async with aiohttp.ClientSession() as session:
                payload = {
                    "model": self.model,
                    "messages": messages,
                    "stream": False,
                    "options": {
                        "temperature": self.temperature,
                        "num_ctx": self.num_ctx,
                        "num_predict": self.num_predict,
                    },
                }

                if system_prompt:
                    payload["messages"] = [
                        {"role": "system", "content": system_prompt}
                    ] + messages

                async with session.post(
                    f"{self.base_url}/api/chat",
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=self.timeout),
                ) as resp:
                    if resp.status != 200:
                        error_text = await resp.text()
                        return OllamaGenerationResult(
                            success=False,
                            error=f"Ollama chat error: {resp.status} - {error_text}",
                            model=self.model,
                        )

                    data = await resp.json()
                    message = data.get("message", {})
                    response_text = message.get("content", "")

                    # Parse files from response
                    files = self._parse_files_from_response(response_text)

                    return OllamaGenerationResult(
                        success=True,
                        files=files,
                        response=response_text,
                        output=response_text,
                        execution_time_ms=int((time.time() - start_time) * 1000),
                        model=self.model,
                        tokens_evaluated=data.get("prompt_eval_count", 0),
                        tokens_generated=data.get("eval_count", 0),
                    )

        except Exception as e:
            return OllamaGenerationResult(
                success=False,
                error=str(e),
                model=self.model,
                execution_time_ms=int((time.time() - start_time) * 1000),
            )

    def _get_system_prompt(self, agent_type: str) -> str:
        """Get system prompt based on agent type."""
        system_prompts = {
            "docker_fixer": """You are a Docker expert. Your task is to analyze Docker-related errors and provide fixes.

When you identify code that needs to be created or modified, output it in this format:
```language:path/to/file
// code here
```

Focus on:
- Dockerfile optimization
- Docker Compose configuration
- Container networking
- Volume management
- Security best practices""",

            "docker_debugger": """You are a Docker debugging expert. Analyze container logs and system information to identify issues.

When providing fixes, use this format for files:
```language:path/to/file
// code here
```

Consider:
- Container startup issues
- Network connectivity
- Resource constraints
- Environment variables
- Volume mounts""",

            "docker_architect": """You are a Docker deployment architect. Design robust, secure, and scalable Docker deployments.

Output files in this format:
```language:path/to/file
// code here
```

Best practices:
- Multi-stage builds
- Health checks
- Resource limits
- Secret management (never hardcode!)
- Logging configuration""",

            "docker_generator": """You are a Dockerfile and Docker Compose expert. Generate optimized Docker configurations.

Output format:
```dockerfile:Dockerfile
# dockerfile content
```

```yaml:docker-compose.yml
# compose content
```

Always include:
- Multi-stage builds for smaller images
- Non-root user for security
- Health checks
- Proper layer caching""",

            "security_analyzer": """You are a container security expert. Analyze Docker images and configurations for vulnerabilities.

Provide:
1. Vulnerability summary
2. Risk assessment
3. Remediation steps

Output fixes as:
```language:path/to/file
// code here
```""",

            "frontend": """You are a frontend expert specializing in React and TypeScript.
Create React functional components with TypeScript.
Use modern React patterns (hooks, context).
Output format: ```tsx:src/components/Component.tsx""",

            "backend": """You are a backend expert specializing in Python and FastAPI.
Create FastAPI routes and Pydantic models.
Output format: ```python:src/api/route.py""",

            "general": """You are a helpful coding assistant.
When generating code, output files in this format:
```language:path/to/file
// code here
```""",
        }

        return system_prompts.get(agent_type, system_prompts["general"])

    def _build_prompt(
        self,
        prompt: str,
        context: Optional[str],
        agent_type: str,
    ) -> str:
        """Build the full prompt with context."""
        parts = []

        if context:
            parts.append(f"## Context\n\n{context}\n\n")

        parts.append(f"## Task\n\n{prompt}\n\n")

        parts.append("""## Output Format

For each file you create or modify, use this format:

```language:path/to/file.ext
// file content here
```

Create complete, production-ready code.""")

        return "".join(parts)

    def _parse_files_from_response(self, response: str) -> list[GeneratedFile]:
        """
        Parse generated files from response text.

        Looks for code blocks in format:
        ```language:path/to/file
        content
        ```
        """
        files = []

        # Pattern: ```language:path\ncontent\n```
        pattern = r"```(\w+):([^\n]+)\n(.*?)```"
        matches = re.findall(pattern, response, re.DOTALL)

        for language, path, content in matches:
            # Clean up the path and content
            path = path.strip()
            content = content.strip()

            if path and content:
                files.append(GeneratedFile(
                    path=path,
                    content=content,
                    language=language,
                ))

        # Also try standard code block with filename comment
        # ```language
        # // filename: path/to/file
        # content
        # ```
        if not files:
            alt_pattern = r"```(\w+)\n(?://|#)\s*(?:filename:|file:)\s*([^\n]+)\n(.*?)```"
            alt_matches = re.findall(alt_pattern, response, re.DOTALL)
            for language, path, content in alt_matches:
                path = path.strip()
                content = content.strip()
                if path and content:
                    files.append(GeneratedFile(
                        path=path,
                        content=content,
                        language=language,
                    ))

        return files

    async def _write_files(self, files: list[GeneratedFile]) -> None:
        """Write generated files to disk."""
        if not self.working_dir:
            return

        for file in files:
            try:
                file_path = Path(self.working_dir) / file.path
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.write_text(file.content, encoding="utf-8")
                self.logger.info("file_written", path=str(file_path))
            except Exception as e:
                self.logger.error("file_write_failed", path=file.path, error=str(e))


# =========================================================================
# Convenience functions
# =========================================================================

async def ollama_generate(
    prompt: str,
    model: str = "codellama:34b",
    context: Optional[str] = None,
    working_dir: Optional[str] = None,
) -> OllamaGenerationResult:
    """
    Convenience function for quick code generation.

    Args:
        prompt: What to generate
        model: Ollama model to use
        context: Additional context
        working_dir: Directory for file output

    Returns:
        OllamaGenerationResult
    """
    tool = OllamaTool(model=model, working_dir=working_dir)
    return await tool.execute(prompt, context)


async def check_ollama_available(
    base_url: str = "http://localhost:11434",
) -> tuple[bool, list[str]]:
    """
    Check if Ollama is available and list models.

    Returns:
        (is_available, list_of_models)
    """
    try:
        import aiohttp

        async with aiohttp.ClientSession() as session:
            async with session.get(
                f"{base_url}/api/tags",
                timeout=aiohttp.ClientTimeout(total=5),
            ) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    models = [m.get("name", "") for m in data.get("models", [])]
                    return True, models
                return False, []
    except Exception:
        return False, []
