"""
Base Agent - Foundation for all specialized agents.

This module provides:
1. Base agent class with Claude SDK integration
2. Tool registration and execution system
3. Conversation management
4. Response parsing and artifact extraction
"""
import json
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, Any, Callable
from enum import Enum

import anthropic
import structlog

from src.config import get_settings
from src.llm_config import get_model
from src.services.rate_limiter import get_rate_limiter
from src.services.retry_strategy import get_retry_strategy

logger = structlog.get_logger()


class AgentType(str, Enum):
    """Types of specialized agents."""
    FRONTEND = "frontend"
    BACKEND = "backend"
    TESTING = "testing"
    SECURITY = "security"
    DEVOPS = "devops"
    DOCUMENTATION = "documentation"
    GENERAL = "general"


@dataclass
class AgentConfig:
    """Configuration for an agent instance."""
    agent_type: AgentType = AgentType.GENERAL
    model: str = field(default_factory=lambda: get_model("primary"))
    max_tokens: int = 4096
    temperature: float = 0.7
    system_prompt: Optional[str] = None
    tools: list[dict] = field(default_factory=list)
    timeout: Optional[int] = None  # Uses get_settings().cli_timeout if not specified


@dataclass
class GeneratedFile:
    """A file generated by an agent."""
    path: str
    content: str
    language: str
    description: Optional[str] = None


@dataclass
class AgentResponse:
    """Response from an agent execution."""
    success: bool
    content: str
    files: list[GeneratedFile] = field(default_factory=list)
    tool_calls: list[dict] = field(default_factory=list)
    tokens_used: int = 0
    execution_time_ms: int = 0
    cost_usd: float = 0.0
    error: Optional[str] = None
    metadata: dict = field(default_factory=dict)


class BaseAgent(ABC):
    """
    Base class for all specialized agents.

    Provides:
    - Claude SDK integration
    - Tool registration and execution
    - Conversation management
    - Response parsing
    """

    def __init__(self, config: Optional[AgentConfig] = None):
        self.config = config or AgentConfig()
        self.settings = get_settings()
        self.logger = logger.bind(
            component="agent",
            agent_type=self.config.agent_type.value,
        )

        # Initialize Anthropic client
        self.client = anthropic.Anthropic(
            api_key=self.settings.anthropic_api_key,
        )

        # Conversation history
        self.messages: list[dict] = []

        # Tool handlers
        self._tool_handlers: dict[str, Callable] = {}

        # Register default tools
        self._register_default_tools()

        # Register specialized tools
        self._register_tools()

    @abstractmethod
    def _register_tools(self):
        """Register agent-specific tools. Override in subclasses."""
        pass

    @abstractmethod
    def get_system_prompt(self) -> str:
        """Get the system prompt for this agent. Override in subclasses."""
        pass

    def _register_default_tools(self):
        """Register tools available to all agents."""
        # Write file tool
        self.register_tool(
            name="write_file",
            description="Write content to a file. Use this to create source code files.",
            input_schema={
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "The file path (relative to project root)",
                    },
                    "content": {
                        "type": "string",
                        "description": "The file content",
                    },
                    "language": {
                        "type": "string",
                        "description": "Programming language (e.g., python, typescript, rust)",
                    },
                },
                "required": ["path", "content", "language"],
            },
            handler=self._handle_write_file,
        )

        # Read file tool (for context)
        self.register_tool(
            name="read_file",
            description="Read content from an existing file for context.",
            input_schema={
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "The file path to read",
                    },
                },
                "required": ["path"],
            },
            handler=self._handle_read_file,
        )

    def register_tool(
        self,
        name: str,
        description: str,
        input_schema: dict,
        handler: Callable,
    ):
        """Register a tool for this agent."""
        tool_def = {
            "name": name,
            "description": description,
            "input_schema": input_schema,
        }

        # Add to config tools
        self.config.tools.append(tool_def)

        # Register handler
        self._tool_handlers[name] = handler

        self.logger.debug("tool_registered", tool_name=name)

    async def execute(self, prompt: str, context: Optional[dict] = None) -> AgentResponse:
        """
        Execute the agent with a given prompt.

        Args:
            prompt: The task prompt
            context: Optional context (project info, previous outputs, etc.)

        Returns:
            AgentResponse with results
        """
        start_time = time.time()
        generated_files: list[GeneratedFile] = []
        tool_calls: list[dict] = []

        # Build system prompt
        system_prompt = self.get_system_prompt()
        if context:
            system_prompt += f"\n\n## Context\n{json.dumps(context, indent=2)}"

        # Add user message
        self.messages.append({
            "role": "user",
            "content": prompt,
        })

        try:
            # Call Claude API
            total_tokens = 0
            iterations = 0
            max_iterations = 10  # Prevent infinite loops

            while iterations < max_iterations:
                iterations += 1

                # Rate-limited LLM call
                response = await self._rate_limited_llm_call(
                    system_prompt=system_prompt,
                )

                total_tokens += response.usage.input_tokens + response.usage.output_tokens

                # Record actual usage with rate limiter
                try:
                    rate_limiter = get_rate_limiter()
                    rate_limiter.record_usage(
                        self.config.agent_type.value,
                        actual_tokens=response.usage.input_tokens + response.usage.output_tokens,
                    )
                except Exception:
                    pass  # Rate limiter not initialized yet

                # Process response
                assistant_content = []
                has_tool_use = False

                for block in response.content:
                    if block.type == "text":
                        assistant_content.append({
                            "type": "text",
                            "text": block.text,
                        })
                    elif block.type == "tool_use":
                        has_tool_use = True
                        assistant_content.append({
                            "type": "tool_use",
                            "id": block.id,
                            "name": block.name,
                            "input": block.input,
                        })

                        # Execute tool
                        tool_result = await self._execute_tool(
                            block.name,
                            block.input,
                            generated_files,
                        )

                        tool_calls.append({
                            "name": block.name,
                            "input": block.input,
                            "result": tool_result,
                        })

                # Add assistant response to messages
                self.messages.append({
                    "role": "assistant",
                    "content": assistant_content,
                })

                # If tool was used, add tool results and continue
                if has_tool_use:
                    tool_results = []
                    for block in assistant_content:
                        if block.get("type") == "tool_use":
                            # Find the corresponding tool call result
                            for tc in tool_calls:
                                if tc["name"] == block["name"]:
                                    tool_results.append({
                                        "type": "tool_result",
                                        "tool_use_id": block["id"],
                                        "content": json.dumps(tc["result"]),
                                    })
                                    break

                    self.messages.append({
                        "role": "user",
                        "content": tool_results,
                    })
                else:
                    # No more tool use, we're done
                    break

            # Extract final text response
            final_content = ""
            for block in response.content:
                if block.type == "text":
                    final_content += block.text

            # Calculate cost (approximate)
            cost_usd = self._calculate_cost(total_tokens)

            execution_time = int((time.time() - start_time) * 1000)

            self.logger.info(
                "agent_execution_complete",
                tokens=total_tokens,
                files_generated=len(generated_files),
                tool_calls=len(tool_calls),
                execution_time_ms=execution_time,
            )

            return AgentResponse(
                success=True,
                content=final_content,
                files=generated_files,
                tool_calls=tool_calls,
                tokens_used=total_tokens,
                execution_time_ms=execution_time,
                cost_usd=cost_usd,
            )

        except anthropic.APIError as e:
            self.logger.error("api_error", error=str(e))
            return AgentResponse(
                success=False,
                content="",
                error=f"API error: {str(e)}",
                execution_time_ms=int((time.time() - start_time) * 1000),
            )
        except Exception as e:
            self.logger.error("execution_error", error=str(e))
            return AgentResponse(
                success=False,
                content="",
                error=f"Execution error: {str(e)}",
                execution_time_ms=int((time.time() - start_time) * 1000),
            )

    async def _rate_limited_llm_call(self, system_prompt: str):
        """Make an LLM API call with rate limiting and retry logic."""
        agent_name = self.config.agent_type.value
        estimated_tokens = self.config.max_tokens // 2  # Rough estimate

        async def _do_call():
            """Inner call function wrapped by retry strategy."""
            try:
                rate_limiter = get_rate_limiter()
                async with rate_limiter.acquire(agent_name, estimated_tokens=estimated_tokens):
                    return self.client.messages.create(
                        model=self.config.model,
                        max_tokens=self.config.max_tokens,
                        system=system_prompt,
                        tools=self.config.tools if self.config.tools else None,
                        messages=self.messages,
                    )
            except Exception as e:
                # If rate limiter itself failed (not initialized), call directly
                if "rate_limiter" in str(type(e).__name__).lower() or "not initialized" in str(e).lower():
                    return self.client.messages.create(
                        model=self.config.model,
                        max_tokens=self.config.max_tokens,
                        system=system_prompt,
                        tools=self.config.tools if self.config.tools else None,
                        messages=self.messages,
                    )
                raise  # Re-raise API errors for retry strategy to handle

        try:
            retry = get_retry_strategy()
            return await retry.execute(_do_call)
        except Exception:
            # Ultimate fallback: direct call without retry or rate limiting
            self.logger.warning("retry_and_ratelimit_bypass", agent=agent_name)
            return self.client.messages.create(
                model=self.config.model,
                max_tokens=self.config.max_tokens,
                system=system_prompt,
                tools=self.config.tools if self.config.tools else None,
                messages=self.messages,
            )

    async def _execute_tool(
        self,
        tool_name: str,
        tool_input: dict,
        generated_files: list[GeneratedFile],
    ) -> dict:
        """Execute a tool and return the result."""
        handler = self._tool_handlers.get(tool_name)

        if not handler:
            return {"error": f"Unknown tool: {tool_name}"}

        try:
            result = handler(tool_input, generated_files)
            return result
        except Exception as e:
            self.logger.error("tool_error", tool=tool_name, error=str(e))
            return {"error": str(e)}

    def _handle_write_file(
        self,
        input_data: dict,
        generated_files: list[GeneratedFile],
    ) -> dict:
        """Handle write_file tool calls."""
        path = input_data.get("path", "")
        content = input_data.get("content", "")
        language = input_data.get("language", "text")

        # Create GeneratedFile
        file = GeneratedFile(
            path=path,
            content=content,
            language=language,
        )
        generated_files.append(file)

        return {
            "success": True,
            "message": f"File written: {path}",
            "size": len(content),
        }

    def _handle_read_file(
        self,
        input_data: dict,
        generated_files: list[GeneratedFile],
    ) -> dict:
        """Handle read_file tool calls (placeholder)."""
        # In production, this would read from the actual filesystem or git
        return {
            "success": False,
            "message": "File reading not implemented in sandbox",
        }

    def _calculate_cost(self, tokens: int) -> float:
        """Calculate approximate cost in USD."""
        # Approximate pricing for Claude Sonnet
        # Input: $3 per 1M tokens, Output: $15 per 1M tokens
        # Using average for simplicity
        return (tokens / 1_000_000) * 9.0

    def reset_conversation(self):
        """Reset the conversation history."""
        self.messages = []


class GeneralAgent(BaseAgent):
    """General-purpose agent for miscellaneous tasks."""

    def _register_tools(self):
        """No additional tools for general agent."""
        pass

    def get_system_prompt(self) -> str:
        return """You are a skilled software engineer working on a coding project.

Your task is to implement requirements as specified. Follow these guidelines:

1. Write clean, well-structured code
2. Use appropriate design patterns
3. Include error handling
4. Add comments for complex logic
5. Follow language-specific best practices

Use the write_file tool to create source code files. Each file should be complete
and ready to use.

When you're done, provide a summary of what you implemented."""
