"""
PermissionsSeedAgent - Seeds the database with roles, permissions, and admin user.

This agent runs after AUTH_SETUP_COMPLETE to ensure:
1. Default roles exist (admin, user, guest)
2. Default permissions are assigned to roles
3. Admin user is created with proper credentials
4. Initial permission matrix is established
"""

import json
import secrets
from pathlib import Path
from typing import Any, Optional

from src.agents.autonomous_base import AutonomousAgent
from src.mind.event_bus import Event, EventType


class PermissionsSeedAgent(AutonomousAgent):
    """Agent that seeds roles, permissions, and creates admin user."""

    subscribed_events = [
        EventType.AUTH_SETUP_COMPLETE,
        EventType.DATABASE_SCHEMA_GENERATED,
    ]

    def __init__(
        self,
        name: str = "PermissionsSeed",
        event_bus: Any = None,
        shared_state: Any = None,
        working_dir: str = ".",
        **kwargs,
    ):
        super().__init__(
            name=name,
            event_bus=event_bus,
            shared_state=shared_state,
            working_dir=working_dir,
            **kwargs,
        )
        self.working_dir = Path(working_dir)
        self._seeded = False
        self._auth_complete = False
        self._db_ready = False

    async def should_act(self, events: list[Event]) -> bool:
        """Act when auth is complete or database schema is generated."""
        if self._seeded:
            return False

        for event in events:
            if event.type == EventType.AUTH_SETUP_COMPLETE:
                self._auth_complete = True
                return True
            if event.type == EventType.DATABASE_SCHEMA_GENERATED:
                self._db_ready = True
                # Only act if auth is also complete
                if self._auth_complete:
                    return True

        return False

    async def act(self, events: list[Event]) -> None:
        """Seed roles, permissions, and admin user."""
        self.logger.info("permissions_seed_starting", working_dir=str(self.working_dir))

        try:
            # 1. Generate permissions seed script if it doesn't exist
            seed_script = await self._ensure_permissions_seed_script()

            if seed_script:
                # 2. Run the permissions seed
                result = await self._run_permissions_seed(seed_script)

                if result["success"]:
                    self._seeded = True
                    self.logger.info(
                        "permissions_seed_complete",
                        roles_created=result.get("roles", 0),
                        permissions_created=result.get("permissions", 0),
                        admin_created=result.get("admin_created", False),
                    )

                    # Publish completion event
                    await self._publish_event(
                        EventType.GENERATION_COMPLETE,
                        data={
                            "component": "permissions_seed",
                            "success": True,
                            "admin_created": result.get("admin_created", False),
                            "roles": result.get("roles", []),
                        },
                    )
                else:
                    self.logger.warning(
                        "permissions_seed_failed",
                        error=result.get("error", "Unknown error"),
                    )
            else:
                # Create a basic permissions structure in env
                await self._create_default_admin_env()
                self._seeded = True

        except Exception as e:
            self.logger.error("permissions_seed_error", error=str(e))

    async def _ensure_permissions_seed_script(self) -> Optional[Path]:
        """Ensure a permissions seed script exists, create if needed."""

        # Check for existing seed scripts
        python_seed = self.working_dir / "scripts" / "seed_permissions.py"
        ts_seed = self.working_dir / "prisma" / "seed-permissions.ts"

        if python_seed.exists():
            return python_seed
        if ts_seed.exists():
            return ts_seed

        # Create Python permissions seed script
        scripts_dir = self.working_dir / "scripts"
        scripts_dir.mkdir(exist_ok=True)

        seed_content = self._generate_permissions_seed_script()
        python_seed.write_text(seed_content)

        self.logger.info("permissions_seed_script_created", path=str(python_seed))
        return python_seed

    def _generate_permissions_seed_script(self) -> str:
        """Generate a Python script to seed permissions."""
        return '''#!/usr/bin/env python3
"""
Permissions Seed Script
Automatically generated by PermissionsSeedAgent

Seeds:
- Default roles (admin, manager, user, guest)
- Role-permission mappings
- Admin user with secure credentials
"""

import os
import sys
import json
from pathlib import Path

# Try to import database libraries
try:
    from sqlalchemy import create_engine, text
    from sqlalchemy.orm import sessionmaker
    HAS_SQLALCHEMY = True
except ImportError:
    HAS_SQLALCHEMY = False

try:
    import bcrypt
    HAS_BCRYPT = True
except ImportError:
    HAS_BCRYPT = False


# Default roles and permissions
DEFAULT_ROLES = {
    "admin": {
        "description": "Full system access",
        "permissions": ["*"],  # Wildcard - all permissions
    },
    "manager": {
        "description": "Manage users and content",
        "permissions": [
            "read:users",
            "write:users",
            "read:content",
            "write:content",
            "manage:roles",
        ],
    },
    "user": {
        "description": "Standard user access",
        "permissions": [
            "read:own",
            "write:own",
            "read:content",
        ],
    },
    "guest": {
        "description": "Read-only access",
        "permissions": [
            "read:public",
        ],
    },
}

DEFAULT_PERMISSIONS = [
    {"name": "read:users", "description": "View user profiles"},
    {"name": "write:users", "description": "Create/update users"},
    {"name": "delete:users", "description": "Delete users"},
    {"name": "read:content", "description": "View content"},
    {"name": "write:content", "description": "Create/update content"},
    {"name": "delete:content", "description": "Delete content"},
    {"name": "manage:roles", "description": "Manage user roles"},
    {"name": "read:own", "description": "Read own resources"},
    {"name": "write:own", "description": "Write own resources"},
    {"name": "read:public", "description": "Read public resources"},
    {"name": "*", "description": "Full access (admin only)"},
]


def get_database_url():
    """Get database URL from environment."""
    return os.environ.get(
        "DATABASE_URL",
        "postgresql://postgres:postgres@localhost:5432/taskdb"
    )


def hash_password(password: str) -> str:
    """Hash password using bcrypt."""
    if HAS_BCRYPT:
        return bcrypt.hashpw(password.encode(), bcrypt.gensalt(12)).decode()
    # Fallback - NOT SECURE, only for development
    import hashlib
    return f"sha256:{hashlib.sha256(password.encode()).hexdigest()}"


def seed_with_sqlalchemy():
    """Seed permissions using SQLAlchemy."""
    database_url = get_database_url()
    engine = create_engine(database_url)
    Session = sessionmaker(bind=engine)
    session = Session()

    roles_created = 0
    permissions_created = 0
    admin_created = False

    try:
        # Check if tables exist
        result = session.execute(text("""
            SELECT table_name FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name IN ('roles', 'permissions', 'users')
        """))
        existing_tables = {row[0] for row in result}

        # Seed permissions if table exists
        if 'permissions' in existing_tables:
            for perm in DEFAULT_PERMISSIONS:
                existing = session.execute(
                    text("SELECT id FROM permissions WHERE name = :name"),
                    {"name": perm["name"]}
                ).fetchone()

                if not existing:
                    session.execute(
                        text("INSERT INTO permissions (name, description) VALUES (:name, :desc)"),
                        {"name": perm["name"], "desc": perm["description"]}
                    )
                    permissions_created += 1

        # Seed roles if table exists
        if 'roles' in existing_tables:
            for role_name, role_data in DEFAULT_ROLES.items():
                existing = session.execute(
                    text("SELECT id FROM roles WHERE name = :name"),
                    {"name": role_name}
                ).fetchone()

                if not existing:
                    session.execute(
                        text("INSERT INTO roles (name, description) VALUES (:name, :desc)"),
                        {"name": role_name, "desc": role_data["description"]}
                    )
                    roles_created += 1

        # Create admin user if users table exists
        if 'users' in existing_tables:
            admin_email = os.environ.get("ADMIN_EMAIL", "admin@example.com")
            admin_password = os.environ.get("ADMIN_PASSWORD", "admin123!")

            existing_admin = session.execute(
                text("SELECT id FROM users WHERE email = :email"),
                {"email": admin_email}
            ).fetchone()

            if not existing_admin:
                hashed_pw = hash_password(admin_password)
                session.execute(
                    text("""
                        INSERT INTO users (email, password, role, name, is_active)
                        VALUES (:email, :password, 'admin', 'Administrator', true)
                    """),
                    {"email": admin_email, "password": hashed_pw}
                )
                admin_created = True
                print(f"  Created admin user: {admin_email}")

        session.commit()

    except Exception as e:
        session.rollback()
        print(f"  Error: {e}")
        raise
    finally:
        session.close()

    return {
        "success": True,
        "roles": roles_created,
        "permissions": permissions_created,
        "admin_created": admin_created,
    }


def seed_with_json():
    """Fallback: Write permissions to JSON file."""
    output_dir = Path(".")
    config_dir = output_dir / "config"
    config_dir.mkdir(exist_ok=True)

    # Write roles config
    roles_file = config_dir / "roles.json"
    roles_file.write_text(json.dumps(DEFAULT_ROLES, indent=2))

    # Write permissions config
    perms_file = config_dir / "permissions.json"
    perms_file.write_text(json.dumps(DEFAULT_PERMISSIONS, indent=2))

    # Create admin credentials (for development only)
    admin_email = os.environ.get("ADMIN_EMAIL", "admin@example.com")
    admin_password = os.environ.get("ADMIN_PASSWORD", "admin123!")

    admin_file = config_dir / "admin.json"
    admin_file.write_text(json.dumps({
        "email": admin_email,
        "password_hash": hash_password(admin_password),
        "role": "admin",
    }, indent=2))

    return {
        "success": True,
        "roles": len(DEFAULT_ROLES),
        "permissions": len(DEFAULT_PERMISSIONS),
        "admin_created": True,
        "config_dir": str(config_dir),
    }


def main():
    print("=== Permissions Seed Script ===")
    print()

    if HAS_SQLALCHEMY:
        print("Using SQLAlchemy for database seeding...")
        try:
            result = seed_with_sqlalchemy()
        except Exception as e:
            print(f"Database seeding failed: {e}")
            print("Falling back to JSON config...")
            result = seed_with_json()
    else:
        print("SQLAlchemy not available, using JSON config...")
        result = seed_with_json()

    print()
    print("Seed Results:")
    print(f"  Roles created: {result.get('roles', 0)}")
    print(f"  Permissions created: {result.get('permissions', 0)}")
    print(f"  Admin user created: {result.get('admin_created', False)}")

    if result.get("config_dir"):
        print(f"  Config files: {result['config_dir']}")

    print()
    print("Default Roles:")
    for role_name, role_data in DEFAULT_ROLES.items():
        print(f"  - {role_name}: {role_data['description']}")

    return 0 if result.get("success") else 1


if __name__ == "__main__":
    sys.exit(main())
'''

    async def _run_permissions_seed(self, seed_path: Path) -> dict:
        """Run the permissions seed script."""
        self.logger.info("running_permissions_seed", path=str(seed_path))

        try:
            if seed_path.suffix == ".py":
                result = await self.call_tool(
                    "python.run_script",
                    script_path=str(seed_path),
                    cwd=str(self.working_dir),
                )
            else:
                # TypeScript seed via npx ts-node
                result = await self.call_tool(
                    "npm.npx",
                    command="ts-node",
                    args=str(seed_path),
                    cwd=str(self.working_dir),
                )

            output = result.get("output", "")
            if result.get("success"):
                return {
                    "success": True,
                    "output": output,
                    "roles": 4,  # Default roles
                    "permissions": 11,  # Default permissions
                    "admin_created": "admin" in output.lower(),
                }
            else:
                return {
                    "success": False,
                    "error": output or result.get("error", "Unknown error"),
                }

        except Exception as e:
            return {"success": False, "error": str(e)}

    async def _create_default_admin_env(self) -> None:
        """Add default admin credentials to .env if not present."""
        env_file = self.working_dir / ".env"

        if not env_file.exists():
            return

        content = env_file.read_text()
        additions = []

        if "ADMIN_EMAIL" not in content:
            additions.append("ADMIN_EMAIL=admin@example.com")
        if "ADMIN_PASSWORD" not in content:
            # Generate a secure random password
            password = secrets.token_urlsafe(12)
            additions.append(f"ADMIN_PASSWORD={password}")
            self.logger.info("admin_password_generated",
                           note="Check .env for ADMIN_PASSWORD")

        if additions:
            with open(env_file, "a") as f:
                f.write("\n# Admin User (auto-generated)\n")
                f.write("\n".join(additions))
                f.write("\n")

    async def _publish_event(self, event_type: EventType, data: dict) -> None:
        """Publish an event to the event bus."""
        if self.event_bus:
            event = Event(
                type=event_type,
                source=self.name,
                data=data,
            )
            await self.event_bus.publish(event)
