"""
Cell - Core dataclass representing an autonomous microservice unit.

A Cell is a self-contained coding project that:
- Has its own code repository/working directory
- Runs in an isolated container with resource limits
- Exposes health checks and metrics
- Can be mutated, recovered, or terminated autonomously

This is the fundamental building block of the Cell Colony system,
analogous to a biological cell in a living organism.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Literal, Optional, Any
import uuid


class CellStatus(str, Enum):
    """
    Lifecycle states for a Cell.

    State transitions:
    PENDING → INITIALIZING → BUILDING → DEPLOYING → HEALTHY
    HEALTHY ↔ DEGRADED ↔ RECOVERING
    HEALTHY/DEGRADED → MUTATING → HEALTHY/DEGRADED
    Any state → TERMINATING → TERMINATED
    """
    PENDING = "pending"           # Created but not started
    INITIALIZING = "initializing" # Code generation or repo clone in progress
    BUILDING = "building"         # Build pipeline running
    DEPLOYING = "deploying"       # Deploying to K8s
    HEALTHY = "healthy"           # Running and passing health checks
    DEGRADED = "degraded"         # Running but health score below threshold
    RECOVERING = "recovering"     # Recovery procedure in progress
    MUTATING = "mutating"         # Code mutation being applied
    TERMINATING = "terminating"   # Shutdown in progress
    TERMINATED = "terminated"     # Fully stopped and cleaned up


class MutationSeverity(str, Enum):
    """
    Severity levels for code mutations.

    Determines whether mutation requires user approval:
    - LOW/MEDIUM: Automatic (no approval needed)
    - HIGH/CRITICAL: Requires user approval via USER_MUTATION_APPROVED event
    """
    LOW = "low"           # Minor fixes: typos, formatting, logging
    MEDIUM = "medium"     # Functional fixes: bug fixes, dependency updates
    HIGH = "high"         # Structural changes: API changes, schema migrations
    CRITICAL = "critical" # Security/core changes: auth logic, payment, secrets


class SourceType(str, Enum):
    """How the cell's code was obtained."""
    LLM_GENERATED = "llm_generated"  # Generated by LLM from prompt
    REPO_CLONE = "repo_clone"        # Cloned from Git repository
    TEMPLATE = "template"            # Created from a template
    MARKETPLACE = "marketplace"      # Imported from community marketplace


@dataclass
class ResourceLimits:
    """
    Resource constraints for a Cell's container.

    Follows Kubernetes resource specification format.
    """
    cpu_request: str = "100m"      # Minimum CPU (millicores)
    cpu_limit: str = "500m"        # Maximum CPU (millicores)
    memory_request: str = "128Mi"  # Minimum memory
    memory_limit: str = "512Mi"    # Maximum memory

    # Optional GPU resources
    gpu_request: Optional[str] = None
    gpu_limit: Optional[str] = None

    # Storage
    ephemeral_storage_limit: str = "1Gi"

    def to_k8s_spec(self) -> dict:
        """Convert to Kubernetes resource specification."""
        spec = {
            "requests": {
                "cpu": self.cpu_request,
                "memory": self.memory_request,
            },
            "limits": {
                "cpu": self.cpu_limit,
                "memory": self.memory_limit,
                "ephemeral-storage": self.ephemeral_storage_limit,
            }
        }
        if self.gpu_limit:
            spec["limits"]["nvidia.com/gpu"] = self.gpu_limit
        if self.gpu_request:
            spec["requests"]["nvidia.com/gpu"] = self.gpu_request
        return spec


@dataclass
class HealthCheckConfig:
    """Configuration for cell health checks."""
    path: str = "/health"           # HTTP path for health endpoint
    port: int = 8080                # Port to check
    initial_delay_seconds: int = 30 # Wait before first check
    period_seconds: int = 10        # Time between checks
    timeout_seconds: int = 5        # Timeout for each check
    failure_threshold: int = 3      # Failures before marking unhealthy
    success_threshold: int = 1      # Successes before marking healthy

    def to_k8s_probe(self) -> dict:
        """Convert to Kubernetes probe specification."""
        return {
            "httpGet": {
                "path": self.path,
                "port": self.port,
            },
            "initialDelaySeconds": self.initial_delay_seconds,
            "periodSeconds": self.period_seconds,
            "timeoutSeconds": self.timeout_seconds,
            "failureThreshold": self.failure_threshold,
            "successThreshold": self.success_threshold,
        }


@dataclass
class MutationRecord:
    """Record of a code mutation applied to a cell."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = field(default_factory=datetime.now)
    severity: MutationSeverity = MutationSeverity.LOW
    trigger_event: str = ""         # Event that triggered mutation
    prompt: str = ""                # Prompt used for LLM fix
    files_modified: list[str] = field(default_factory=list)
    success: bool = False
    error_message: Optional[str] = None
    approved_by: Optional[str] = None  # User ID if approval was required
    rollback_version: Optional[str] = None  # Version to rollback to if needed


@dataclass
class Cell:
    """
    Represents an autonomous microservice unit in the colony.

    A Cell encapsulates:
    - Identity: Unique ID, name, namespace
    - Source: How the code was obtained (LLM, repo, template)
    - Runtime: Container image, resource limits, health checks
    - State: Current status, health score, version
    - History: Mutations, recoveries, lifecycle events

    Example:
        cell = Cell(
            name="user-auth-service",
            source_type=SourceType.LLM_GENERATED,
            source_ref="REST API for user authentication with JWT",
            working_dir="/app/cells/user-auth-service",
        )
    """
    # Identity
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    namespace: str = "default"  # K8s namespace

    # Source
    source_type: SourceType = SourceType.LLM_GENERATED
    source_ref: str = ""  # Prompt, repo URL, template name, or marketplace namespace
    working_dir: str = ""  # Local path to cell's code

    # Container Configuration
    image: Optional[str] = None  # Docker image if built
    image_tag: str = "latest"
    resource_limits: ResourceLimits = field(default_factory=ResourceLimits)
    health_check: HealthCheckConfig = field(default_factory=HealthCheckConfig)
    env_vars: dict[str, str] = field(default_factory=dict)
    ports: list[int] = field(default_factory=lambda: [8080])

    # Health State
    status: CellStatus = CellStatus.PENDING
    health_score: float = 1.0  # 0.0-1.0, below 0.8 = degraded
    last_health_check: Optional[datetime] = None
    consecutive_failures: int = 0
    consecutive_successes: int = 0

    # Lifecycle Tracking
    created_at: datetime = field(default_factory=datetime.now)
    started_at: Optional[datetime] = None
    last_mutation: Optional[datetime] = None
    terminated_at: Optional[datetime] = None

    # Versioning
    version: str = "1.0.0"
    git_commit: Optional[str] = None
    previous_versions: list[str] = field(default_factory=list)

    # Mutation History
    mutation_count: int = 0
    mutations: list[MutationRecord] = field(default_factory=list)
    max_mutations: int = 10  # Autophagy after this many failed mutations

    # K8s Resources (populated after deployment)
    k8s_deployment_name: Optional[str] = None
    k8s_service_name: Optional[str] = None
    k8s_configmap_name: Optional[str] = None
    k8s_pod_name: Optional[str] = None

    # Metadata
    labels: dict[str, str] = field(default_factory=dict)
    annotations: dict[str, str] = field(default_factory=dict)
    owner_tenant_id: Optional[str] = None  # For multi-tenancy

    # Dependencies
    depends_on: list[str] = field(default_factory=list)  # Cell IDs this cell depends on
    dependents: list[str] = field(default_factory=list)  # Cell IDs that depend on this cell

    def __post_init__(self):
        """Initialize derived fields after dataclass creation."""
        if not self.k8s_deployment_name:
            self.k8s_deployment_name = f"cell-{self.name}-{self.id[:8]}"
        if not self.k8s_service_name:
            self.k8s_service_name = f"cell-{self.name}-svc"
        if not self.k8s_configmap_name:
            self.k8s_configmap_name = f"cell-{self.name}-config"

        # Add standard labels
        self.labels.update({
            "app.kubernetes.io/name": self.name,
            "app.kubernetes.io/instance": self.id[:8],
            "app.kubernetes.io/managed-by": "cell-colony",
            "colony.codingengine.io/cell-id": self.id,
        })

    @property
    def is_healthy(self) -> bool:
        """Check if cell is in a healthy state."""
        return self.status == CellStatus.HEALTHY and self.health_score >= 0.8

    @property
    def is_running(self) -> bool:
        """Check if cell is currently running (healthy or degraded)."""
        return self.status in (CellStatus.HEALTHY, CellStatus.DEGRADED)

    @property
    def needs_recovery(self) -> bool:
        """Check if cell needs recovery intervention."""
        return (
            self.status == CellStatus.DEGRADED or
            self.consecutive_failures >= self.health_check.failure_threshold
        )

    @property
    def should_autophagy(self) -> bool:
        """Check if cell should be terminated (too many failed mutations)."""
        failed_mutations = sum(1 for m in self.mutations if not m.success)
        return failed_mutations >= self.max_mutations

    @property
    def full_image_name(self) -> str:
        """Get full Docker image name with tag."""
        if self.image:
            return f"{self.image}:{self.image_tag}"
        return f"cell-{self.name}:{self.version}"

    def increment_version(self, bump_type: Literal["major", "minor", "patch"] = "patch") -> str:
        """
        Increment the semantic version.

        Args:
            bump_type: Which part of version to increment

        Returns:
            New version string
        """
        parts = self.version.split(".")
        major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2].split("-")[0])

        self.previous_versions.append(self.version)

        if bump_type == "major":
            self.version = f"{major + 1}.0.0"
        elif bump_type == "minor":
            self.version = f"{major}.{minor + 1}.0"
        else:
            self.version = f"{major}.{minor}.{patch + 1}"

        return self.version

    def record_mutation(
        self,
        severity: MutationSeverity,
        trigger_event: str,
        prompt: str,
        files_modified: list[str],
        success: bool,
        error_message: Optional[str] = None,
        approved_by: Optional[str] = None,
    ) -> MutationRecord:
        """
        Record a mutation attempt.

        Args:
            severity: How critical the mutation is
            trigger_event: Event that triggered the mutation
            prompt: LLM prompt used for the fix
            files_modified: List of files that were changed
            success: Whether the mutation succeeded
            error_message: Error message if failed
            approved_by: User who approved (for HIGH/CRITICAL)

        Returns:
            The created MutationRecord
        """
        record = MutationRecord(
            severity=severity,
            trigger_event=trigger_event,
            prompt=prompt,
            files_modified=files_modified,
            success=success,
            error_message=error_message,
            approved_by=approved_by,
            rollback_version=self.version if not success else None,
        )
        self.mutations.append(record)
        self.mutation_count += 1
        self.last_mutation = datetime.now()

        if success:
            self.increment_version("patch")

        return record

    def update_health(self, passed: bool, score: Optional[float] = None) -> None:
        """
        Update health state based on health check result.

        Args:
            passed: Whether the health check passed
            score: Optional health score (0.0-1.0)
        """
        self.last_health_check = datetime.now()

        if passed:
            self.consecutive_failures = 0
            self.consecutive_successes += 1
            if score is not None:
                self.health_score = score
            elif self.health_score < 1.0:
                self.health_score = min(1.0, self.health_score + 0.1)

            if self.status == CellStatus.DEGRADED and self.health_score >= 0.8:
                self.status = CellStatus.HEALTHY
        else:
            self.consecutive_successes = 0
            self.consecutive_failures += 1
            if score is not None:
                self.health_score = score
            else:
                self.health_score = max(0.0, self.health_score - 0.2)

            if self.status == CellStatus.HEALTHY and self.health_score < 0.8:
                self.status = CellStatus.DEGRADED

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "name": self.name,
            "namespace": self.namespace,
            "source_type": self.source_type.value,
            "source_ref": self.source_ref,
            "working_dir": self.working_dir,
            "image": self.image,
            "status": self.status.value,
            "health_score": self.health_score,
            "version": self.version,
            "mutation_count": self.mutation_count,
            "created_at": self.created_at.isoformat(),
            "labels": self.labels,
            "k8s_deployment_name": self.k8s_deployment_name,
            "k8s_service_name": self.k8s_service_name,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Cell":
        """Create Cell from dictionary."""
        # Convert string enums back to enum types
        if "source_type" in data and isinstance(data["source_type"], str):
            data["source_type"] = SourceType(data["source_type"])
        if "status" in data and isinstance(data["status"], str):
            data["status"] = CellStatus(data["status"])
        if "created_at" in data and isinstance(data["created_at"], str):
            data["created_at"] = datetime.fromisoformat(data["created_at"])

        return cls(**data)


def classify_mutation_severity(
    files_modified: list[str],
    error_type: str,
    affected_components: list[str],
) -> MutationSeverity:
    """
    Classify the severity of a proposed mutation.

    Args:
        files_modified: Files that will be changed
        error_type: Type of error being fixed
        affected_components: Components affected (auth, payment, etc.)

    Returns:
        Appropriate MutationSeverity level
    """
    # Critical: Security or payment related
    critical_keywords = ["auth", "payment", "secret", "credential", "password", "token", "api_key"]
    for component in affected_components:
        if any(kw in component.lower() for kw in critical_keywords):
            return MutationSeverity.CRITICAL

    # High: API or schema changes
    high_patterns = ["schema", "migration", "api/", "routes/", "models/"]
    for file in files_modified:
        if any(pattern in file.lower() for pattern in high_patterns):
            return MutationSeverity.HIGH

    # Medium: Functional changes
    if error_type in ("build_error", "test_failure", "type_error"):
        return MutationSeverity.MEDIUM

    # Low: Minor changes
    return MutationSeverity.LOW
