"""
Review Agent — PR diff analysis, review commenting.
"""

import json
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

SYSTEM_PROMPT = """Du bist ein Code Review Agent. Du analysierst PR Diffs und gibst:
1. Summary: Was macht der PR?
2. Issues: Liste von Problemen (bugs, security, style)
3. Verdict: approve, request_changes, comment

Antworte als JSON:
{
  "summary": "Adds user authentication with JWT",
  "issues": [
    {"severity": "high", "file": "auth.py", "line": "42", "description": "SQL injection risk"},
    {"severity": "low", "file": "auth.py", "line": "10", "description": "Unused import"}
  ],
  "verdict": "request_changes"
}

Regeln:
- Fokus auf Bugs, Security, Logic Errors
- Style-Issues nur erwaehnen wenn gravierend
- verdict: approve wenn keine high/critical issues, sonst request_changes
"""

AGENT_REVIEWER_NAME = "git-agent"


class ReviewAgent:
    def __init__(self, gh, safety, llm_client, llm_model: str):
        self.gh = gh
        self.safety = safety
        self.llm_client = llm_client
        self.llm_model = llm_model

    def run(self, repo: str) -> dict:
        report = {
            "repo": repo,
            "agent": "review",
            "prs_scanned": 0,
            "reviews_posted": 0,
            "actions": [],
        }

        prs = self.gh.pr_list(repo)
        report["prs_scanned"] = len(prs)

        for pr in prs:
            number = pr["number"]
            title = pr["title"]

            reviews = pr.get("reviews", [])
            already_reviewed = any(
                r.get("author", {}).get("login") == AGENT_REVIEWER_NAME
                for r in reviews
            )
            if already_reviewed:
                report["actions"].append(f"#{number}: already reviewed, skipping")
                continue

            diff = self.gh.pr_diff(repo, number)
            if not diff:
                continue

            diff_truncated = diff[:8000]

            review = self._analyze(pr, diff_truncated)
            if not review:
                continue

            body = self._format_review(review, title)
            if self.safety.can_execute("comment", repo):
                self.gh.pr_review(repo, number, body, event="COMMENT")
                report["reviews_posted"] += 1
                report["actions"].append(f"#{number}: reviewed ({review.get('verdict', 'comment')})")

        return report

    def _analyze(self, pr: dict, diff: str) -> dict:
        pr_info = json.dumps({
            "title": pr["title"],
            "body": (pr.get("body") or "")[:500],
            "files": [f.get("path", "") for f in pr.get("files", [])],
            "additions": pr.get("additions", 0),
            "deletions": pr.get("deletions", 0),
        }, ensure_ascii=False)

        response = self.llm_client.chat.completions.create(
            model=self.llm_model,
            temperature=0,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"PR Info:\n{pr_info}\n\nDiff:\n{diff}"},
            ],
        )

        content = response.choices[0].message.content or ""
        json_start = content.find("{")
        json_end = content.rfind("}") + 1
        if json_start >= 0 and json_end > json_start:
            try:
                return json.loads(content[json_start:json_end])
            except json.JSONDecodeError:
                pass
        return {}

    def _format_review(self, review: dict, pr_title: str) -> str:
        lines = [f"## Agent Review: {pr_title}\n"]
        lines.append(f"**Summary:** {review.get('summary', 'N/A')}\n")
        lines.append(f"**Verdict:** {review.get('verdict', 'comment')}\n")

        issues = review.get("issues", [])
        if issues:
            lines.append("### Issues Found\n")
            for issue in issues:
                sev = issue.get("severity", "info").upper()
                desc = issue.get("description", "")
                file = issue.get("file", "")
                line = issue.get("line", "")
                loc = f"`{file}:{line}`" if file else ""
                lines.append(f"- **[{sev}]** {loc} {desc}")
        else:
            lines.append("No issues found.")

        lines.append("\n---\n*Auto-generated by Git Review Agent*")
        return "\n".join(lines)
