"""
Adaptive CTM Hint Generator - Phase 3
Proactive background thinking with confidence-based hint delivery

Key concept: "The more confident we are, the less thinking is necessary"
- Novice (confidence < 0.3): Heavy background thinking, frequent hints
- Intermediate (0.3 <= confidence < 0.7): Balanced thinking, hints on demand
- Expert (confidence >= 0.7): Minimal thinking, hints only when stuck

Like throwing a ball: we think constantly when learning, less when expert.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from enum import Enum
import time
import threading
from queue import Queue, Empty, Full
import random

from core.context_aligned_state import ContextAlignedState, ActionMetadata


class HintType(Enum):
    """Types of hints the CTM can provide"""
    NEXT_ACTION = "next_action"           # Suggest next best action
    AVOID_MISTAKE = "avoid_mistake"       # Warn about potential error
    CHECKPOINT_AHEAD = "checkpoint_ahead" # Indicate upcoming checkpoint
    STUCK_DETECTION = "stuck_detection"   # Detect repetitive loops
    CONFIDENCE_BOOST = "confidence_boost" # Encourage after success
    ALTERNATIVE_PATH = "alternative_path" # Suggest different approach


class ThinkingIntensity(Enum):
    """How intensely CTM should think"""
    MINIMAL = "minimal"       # confidence >= 0.7 (expert)
    MODERATE = "moderate"     # 0.3 <= confidence < 0.7 (intermediate)
    INTENSIVE = "intensive"   # confidence < 0.3 (novice)


@dataclass
class CTMHint:
    """Hint generated by CTM background thinking"""
    hint_type: HintType
    confidence: float  # CTM's confidence in this hint (0-1)
    message: str
    suggested_action: Optional[str] = None
    reasoning: str = ""
    timestamp: float = field(default_factory=time.time)

    def is_actionable(self) -> bool:
        """Check if hint requires immediate action"""
        return self.hint_type in [
            HintType.NEXT_ACTION,
            HintType.AVOID_MISTAKE,
            HintType.STUCK_DETECTION
        ]

    def is_encouraging(self) -> bool:
        """Check if hint is encouraging (not critical)"""
        return self.hint_type in [
            HintType.CONFIDENCE_BOOST,
            HintType.CHECKPOINT_AHEAD
        ]


@dataclass
class ThinkingState:
    """Current thinking state of CTM"""
    is_thinking: bool = False
    thinking_duration: float = 0.0
    last_hint_time: float = 0.0
    total_hints_generated: int = 0
    successful_hints: int = 0
    intensity: ThinkingIntensity = ThinkingIntensity.MODERATE


class AdaptiveCTMHintGenerator:
    """
    Proactive background thinking system

    Continuously thinks about the problem in background thread, providing hints
    based on confidence level:

    - Low confidence (novice): Think constantly, provide frequent hints
    - Medium confidence (intermediate): Think periodically, provide hints on demand
    - High confidence (expert): Think minimally, provide hints only when stuck

    Inspired by human learning: beginners need constant guidance, experts
    only need help when encountering novel situations.
    """

    def __init__(
        self,
        hint_cooldown_novice: float = 2.0,      # Min seconds between hints (novice)
        hint_cooldown_intermediate: float = 5.0, # Min seconds between hints (intermediate)
        hint_cooldown_expert: float = 10.0,      # Min seconds between hints (expert)
        thinking_interval: float = 0.5,          # Background thinking frequency (seconds)
        max_queue_size: int = 10,                # Max hints to queue
        enable_proactive: bool = True,           # Enable proactive hints (vs on-demand only)
        seed: int = 42
    ):
        """
        Args:
            hint_cooldown_novice: Min seconds between hints for low confidence
            hint_cooldown_intermediate: Min seconds between hints for medium confidence
            hint_cooldown_expert: Min seconds between hints for high confidence
            thinking_interval: How often to run background thinking loop
            max_queue_size: Maximum hints to store in queue
            enable_proactive: If True, generate hints proactively; if False, only on-demand
            seed: Random seed for reproducibility
        """
        self.hint_cooldown_novice = hint_cooldown_novice
        self.hint_cooldown_intermediate = hint_cooldown_intermediate
        self.hint_cooldown_expert = hint_cooldown_expert
        self.thinking_interval = thinking_interval
        self.enable_proactive = enable_proactive
        self.random = random.Random(seed)

        # Background thinking state
        self.thinking_state = ThinkingState()
        self.hint_queue: Queue[CTMHint] = Queue(maxsize=max_queue_size)

        # Background thread
        self._thinking_thread: Optional[threading.Thread] = None
        self._stop_thinking = threading.Event()
        self._current_state: Optional[ContextAlignedState] = None
        self._history: List[ContextAlignedState] = []
        self._lock = threading.Lock()

        # Statistics
        self.total_thinking_time = 0.0
        self.hints_by_type: Dict[HintType, int] = {ht: 0 for ht in HintType}
        self.hints_accepted: int = 0
        self.hints_rejected: int = 0

    def start_thinking(
        self,
        initial_state: ContextAlignedState,
        history: List[ContextAlignedState] = None
    ):
        """Start background thinking thread"""
        if self._thinking_thread and self._thinking_thread.is_alive():
            return  # Already thinking

        with self._lock:
            self._current_state = initial_state
            self._history = history or []
            self._stop_thinking.clear()

        # Update intensity based on initial state
        self._update_thinking_intensity(initial_state.confidence_level)

        self.thinking_state.is_thinking = True
        self._thinking_thread = threading.Thread(
            target=self._background_thinking_loop,
            daemon=True
        )
        self._thinking_thread.start()

    def stop_thinking(self):
        """Stop background thinking thread"""
        self._stop_thinking.set()
        self.thinking_state.is_thinking = False

        if self._thinking_thread:
            self._thinking_thread.join(timeout=2.0)
            self._thinking_thread = None

    def update_state(
        self,
        new_state: ContextAlignedState,
        append_to_history: bool = True
    ):
        """Update current state being thought about"""
        with self._lock:
            if append_to_history and self._current_state:
                self._history.append(self._current_state)
            self._current_state = new_state

            # Update thinking intensity based on confidence
            self._update_thinking_intensity(new_state.confidence_level)

    def get_hint(
        self,
        timeout: float = 0.1,
        force_generate: bool = False
    ) -> Optional[CTMHint]:
        """
        Get next hint from queue

        Args:
            timeout: Max seconds to wait for hint
            force_generate: If True and queue empty, immediately generate hint

        Returns:
            Next hint or None if queue empty
        """
        try:
            hint = self.hint_queue.get(timeout=timeout)
            return hint
        except Empty:
            if force_generate:
                # Generate hint immediately (synchronous)
                with self._lock:
                    if self._current_state:
                        return self._generate_hint(
                            self._current_state,
                            self._history
                        )
            return None

    def get_all_hints(self) -> List[CTMHint]:
        """Get all hints currently in queue"""
        hints = []
        while not self.hint_queue.empty():
            try:
                hints.append(self.hint_queue.get_nowait())
            except Empty:
                break
        return hints

    def mark_hint_outcome(self, hint: CTMHint, accepted: bool):
        """Mark whether hint was accepted/helpful"""
        if accepted:
            self.hints_accepted += 1
            self.thinking_state.successful_hints += 1
        else:
            self.hints_rejected += 1

    def should_provide_hint(self, confidence: float) -> bool:
        """
        Determine if hint should be provided now based on confidence and cooldown

        Args:
            confidence: Current confidence level (0-1)

        Returns:
            True if enough time has passed since last hint
        """
        time_since_last = time.time() - self.thinking_state.last_hint_time

        # Determine cooldown based on confidence
        if confidence < 0.3:  # Novice
            cooldown = self.hint_cooldown_novice
        elif confidence < 0.7:  # Intermediate
            cooldown = self.hint_cooldown_intermediate
        else:  # Expert
            cooldown = self.hint_cooldown_expert

        return time_since_last >= cooldown

    # ============================================
    # Background Thinking Loop
    # ============================================

    def _background_thinking_loop(self):
        """Main background thinking loop (runs in separate thread)"""
        while not self._stop_thinking.is_set():
            think_start = time.time()

            with self._lock:
                current_state = self._current_state
                history = self._history.copy()

            if current_state and self.enable_proactive:
                # Check if we should provide hint
                if self.should_provide_hint(current_state.confidence_level):
                    hint = self._generate_hint(current_state, history)

                    if hint and not self.hint_queue.full():
                        try:
                            self.hint_queue.put_nowait(hint)
                            self.thinking_state.last_hint_time = time.time()
                            self.thinking_state.total_hints_generated += 1
                            self.hints_by_type[hint.hint_type] += 1
                        except (Full, RuntimeError):
                            pass  # Queue full, skip this hint

            # Update thinking duration
            think_duration = time.time() - think_start
            self.thinking_state.thinking_duration += think_duration
            self.total_thinking_time += think_duration

            # Sleep based on thinking intensity
            sleep_time = self._get_sleep_time()
            self._stop_thinking.wait(sleep_time)

    def _generate_hint(
        self,
        state: ContextAlignedState,
        history: List[ContextAlignedState]
    ) -> Optional[CTMHint]:
        """
        Generate hint based on current state

        This is where CTM reasoning happens. For now, uses heuristics.
        Later: integrate with actual CTM iterative reasoning.
        """
        # Detect stuck in loop
        if self._is_stuck_in_loop(state, history):
            return CTMHint(
                hint_type=HintType.STUCK_DETECTION,
                confidence=0.85,
                message="Detected repetitive pattern. Consider alternative approach.",
                suggested_action="try_different_action",
                reasoning="Last 3 actions similar, no progress made"
            )

        # Suggest next action based on context
        if state.confidence_level < 0.4:  # Novice needs guidance
            next_action = self._predict_next_action(state, history)
            if next_action:
                return CTMHint(
                    hint_type=HintType.NEXT_ACTION,
                    confidence=0.7,
                    message=f"Consider trying: {next_action}",
                    suggested_action=next_action,
                    reasoning="Based on successful patterns in history"
                )

        # Warn about potential mistakes
        if self._might_make_mistake(state, history):
            return CTMHint(
                hint_type=HintType.AVOID_MISTAKE,
                confidence=0.75,
                message="Current action might lead to error. Double-check parameters.",
                reasoning="Similar action failed recently"
            )

        # Indicate checkpoint ahead
        if self._checkpoint_nearby(state, history):
            return CTMHint(
                hint_type=HintType.CHECKPOINT_AHEAD,
                confidence=0.8,
                message="Checkpoint reachable in 1-2 actions. Keep going!",
                reasoning="Pattern matches successful checkpoint approach"
            )

        # Boost confidence after success
        if state.last_action and state.last_action.success and state.is_checkpoint:
            return CTMHint(
                hint_type=HintType.CONFIDENCE_BOOST,
                confidence=0.9,
                message="Great progress! Checkpoint reached.",
                reasoning="Successful action completed"
            )

        # Suggest alternative if low context alignment
        if history and state.calculate_context_alignment(history) < 0.3:
            return CTMHint(
                hint_type=HintType.ALTERNATIVE_PATH,
                confidence=0.65,
                message="Exploring unfamiliar territory. Alternative approaches available.",
                reasoning="Low context alignment indicates novel situation"
            )

        return None

    # ============================================
    # Heuristic Helper Methods
    # ============================================

    def _is_stuck_in_loop(
        self,
        state: ContextAlignedState,
        history: List[ContextAlignedState]
    ) -> bool:
        """Detect if agent is stuck in repetitive loop"""
        if len(history) < 3:
            return False

        # Check last 3 actions
        recent = history[-3:]
        action_names = [
            s.last_action.action_name for s in recent
            if s.last_action
        ]

        # All same action = stuck
        if len(set(action_names)) == 1:
            return True

        # Check if progress stalled
        progress_changes = [
            abs(recent[i+1].path_progress - recent[i].path_progress)
            for i in range(len(recent) - 1)
        ]

        # No progress in last 3 steps = stuck
        return all(change < 0.05 for change in progress_changes)

    def _predict_next_action(
        self,
        state: ContextAlignedState,
        history: List[ContextAlignedState]
    ) -> Optional[str]:
        """Predict best next action based on patterns"""
        if not history:
            return "start_with_read_file"

        # Find most successful action type in history
        successful_actions = [
            s.last_action.action_name for s in history
            if s.last_action and s.last_action.success and s.is_checkpoint
        ]

        if successful_actions:
            # Return most common successful action
            from collections import Counter
            most_common = Counter(successful_actions).most_common(1)
            return most_common[0][0] if most_common else None

        return None

    def _might_make_mistake(
        self,
        state: ContextAlignedState,
        history: List[ContextAlignedState]
    ) -> bool:
        """Check if current pattern suggests potential mistake"""
        if not history or not state.last_action:
            return False

        # Check if similar action failed recently
        recent_failures = [
            s for s in history[-5:]
            if s.last_action and not s.last_action.success
        ]

        for failure in recent_failures:
            if (failure.last_action.action_type == state.last_action.action_type):
                return True

        return False

    def _checkpoint_nearby(
        self,
        state: ContextAlignedState,
        history: List[ContextAlignedState]
    ) -> bool:
        """Check if checkpoint is likely nearby"""
        # If progress > 0.7 and trending up, checkpoint likely ahead
        if state.path_progress >= 0.7:
            return True

        # If last action was checkpoint, next might be too
        if history and history[-1].is_checkpoint:
            return self.random.random() < 0.6  # 60% chance

        return False

    def _update_thinking_intensity(self, confidence: float):
        """Update thinking intensity based on confidence"""
        if confidence < 0.3:
            self.thinking_state.intensity = ThinkingIntensity.INTENSIVE
        elif confidence < 0.7:
            self.thinking_state.intensity = ThinkingIntensity.MODERATE
        else:
            self.thinking_state.intensity = ThinkingIntensity.MINIMAL

    def _get_sleep_time(self) -> float:
        """Get sleep time based on thinking intensity"""
        if self.thinking_state.intensity == ThinkingIntensity.INTENSIVE:
            return self.thinking_interval * 0.5  # Think more frequently
        elif self.thinking_state.intensity == ThinkingIntensity.MODERATE:
            return self.thinking_interval
        else:  # MINIMAL
            return self.thinking_interval * 2.0  # Think less frequently

    # ============================================
    # Statistics
    # ============================================

    def get_statistics(self) -> Dict:
        """Get hint generator statistics"""
        total_hints = self.hints_accepted + self.hints_rejected
        acceptance_rate = (self.hints_accepted / total_hints) if total_hints > 0 else 0.0

        return {
            'total_thinking_time': self.total_thinking_time,
            'total_hints_generated': self.thinking_state.total_hints_generated,
            'hints_accepted': self.hints_accepted,
            'hints_rejected': self.hints_rejected,
            'acceptance_rate': acceptance_rate,
            'hints_by_type': {
                ht.value: count for ht, count in self.hints_by_type.items()
            },
            'current_intensity': self.thinking_state.intensity.value,
            'is_thinking': self.thinking_state.is_thinking
        }
