"""
Moltbook Thinking Layer — Continuous Background Thought System

Provides:
  - ThoughtStream:       Continuous background micro-thought generation
  - ThoughtBuffer:       Circular buffer of recent thoughts (Global Workspace)
  - AssociativeThinking: Semantic chain hopping through Moltbook knowledge
  - EmotionalThinking:   Affect-modulated thought generation (Broaden-and-Build)
  - MetaThinking:        Monitoring thought quality and productivity

Architecture Inspirations:
  - Global Workspace Theory (Baars) — conscious thoughts compete for broadcast
  - Broaden-and-Build (Fredrickson) — positive affect → broader associations
  - Predictive Processing (Friston) — thought as active inference
  - Default Mode Network — spontaneous, self-referential thought
"""

from __future__ import annotations

import logging
import math
import random
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

logger = logging.getLogger('brain.moltbook.thinking')


# ═══════════════════════════════════════════════════════════════════
# Thought Data Types
# ═══════════════════════════════════════════════════════════════════

@dataclass
class MicroThought:
    """
    Single micro-thought — the atomic unit of the ThoughtStream.

    Each micro-thought is a brief internal reflection, association,
    or observation generated by the background thinking process.
    """
    content: str = ""
    relevance_to_current_task: float = 0.0     # 0-1
    emotional_charge: float = 0.0              # -1 (negative) to +1 (positive)
    arousal: float = 0.0                       # 0 (calm) to 1 (excited)
    source_entry_ids: List[str] = field(default_factory=list)
    thought_type: str = "association"          # association/reflection/prediction/memory
    activation: float = 1.0                     # Current activation level (decays)
    created_at: float = field(default_factory=time.time)
    was_conscious: bool = False                 # Was this thought broadcast to GW?

    def decay(self, rate: float = 0.01) -> None:
        """Decay activation over time."""
        age = time.time() - self.created_at
        self.activation = max(0.0, self.activation * math.exp(-rate * age))

    def to_dict(self) -> Dict[str, Any]:
        return {
            'content': self.content,
            'relevance': self.relevance_to_current_task,
            'emotional_charge': self.emotional_charge,
            'arousal': self.arousal,
            'source_entries': self.source_entry_ids,
            'type': self.thought_type,
            'activation': self.activation,
            'created_at': self.created_at,
            'was_conscious': self.was_conscious,
        }


@dataclass
class ThoughtQuality:
    """Assessment of thought stream quality from MetaThinking."""
    productivity: float = 0.5       # How productive are current thoughts (0-1)
    creativity: float = 0.5         # How creative/novel are they (0-1)
    circularity: float = 0.0        # Are thoughts repeating? (0=no, 1=very circular)
    coherence: float = 0.5          # How coherent is the thought chain (0-1)
    value_of_control: float = 0.5   # Is more thinking worth it? (EVC)
    recommendation: str = "continue"  # continue/redirect/pause/deepen

    def to_dict(self) -> Dict[str, Any]:
        return {
            'productivity': self.productivity,
            'creativity': self.creativity,
            'circularity': self.circularity,
            'coherence': self.coherence,
            'evc': self.value_of_control,
            'recommendation': self.recommendation,
        }


# ═══════════════════════════════════════════════════════════════════
# [12] ThoughtBuffer — Circular Buffer (Global Workspace)
# ═══════════════════════════════════════════════════════════════════

class ThoughtBuffer:
    """
    Circular buffer of recent micro-thoughts.

    Implements Baars' Global Workspace: thoughts compete for "conscious"
    broadcast. Only the most activated thoughts reach the workspace
    and influence response generation.

    Capacity follows Lisman-Jensen: ~7±2 simultaneously active thoughts.
    """

    def __init__(self, capacity: int = 100, workspace_size: int = 7):
        self._buffer: deque = deque(maxlen=capacity)
        self._workspace_size = workspace_size
        self._lock = threading.Lock()
        self._total_thoughts = 0
        self._total_conscious = 0
        logger.info(f"ThoughtBuffer initialized (capacity={capacity}, ws={workspace_size})")

    @property
    def size(self) -> int:
        """Number of thoughts in buffer."""
        return len(self._buffer)

    def add(self, thought: MicroThought) -> None:
        """Add a thought to the buffer."""
        with self._lock:
            self._buffer.append(thought)
            self._total_thoughts += 1

    def get_workspace(self, context: Optional[str] = None) -> List[MicroThought]:
        """
        Get the current Global Workspace — the most activated thoughts.

        If context is provided, boosts relevance of thoughts matching it.
        Returns up to workspace_size thoughts sorted by activation.
        """
        with self._lock:
            thoughts = list(self._buffer)

        if not thoughts:
            return []

        # Decay all thoughts
        for t in thoughts:
            t.decay()

        # If context provided, boost relevance of matching thoughts
        if context:
            context_words = set(context.lower().split())
            for t in thoughts:
                thought_words = set(t.content.lower().split())
                overlap = len(context_words & thought_words)
                if overlap > 0:
                    t.activation += 0.1 * overlap

        # Sort by activation * relevance
        thoughts.sort(
            key=lambda t: t.activation * (0.5 + 0.5 * t.relevance_to_current_task),
            reverse=True
        )

        # Top-K become "conscious"
        workspace = thoughts[:self._workspace_size]
        for t in workspace:
            if not t.was_conscious:
                t.was_conscious = True
                self._total_conscious += 1

        return workspace

    def get_recent(self, n: int = 10) -> List[MicroThought]:
        """Get the N most recent thoughts."""
        with self._lock:
            items = list(self._buffer)
        return items[-n:] if len(items) >= n else items

    def get_by_type(self, thought_type: str) -> List[MicroThought]:
        """Get all thoughts of a given type."""
        with self._lock:
            return [t for t in self._buffer if t.thought_type == thought_type]

    def clear(self) -> None:
        """Clear all thoughts."""
        with self._lock:
            self._buffer.clear()

    def get_stats(self) -> Dict[str, Any]:
        """Get buffer statistics."""
        return {
            'size': self.size,
            'total_thoughts': self._total_thoughts,
            'total_conscious': self._total_conscious,
            'consciousness_rate': (self._total_conscious / max(1, self._total_thoughts)),
        }


# ═══════════════════════════════════════════════════════════════════
# [13] AssociativeThinking — Semantic Chain Hopping
# ═══════════════════════════════════════════════════════════════════

class AssociativeThinking:
    """
    Associative thinking through semantic chain hopping in the Moltbook.

    Takes current context, searches semantically, then follows
    association chains (A → B → C) with relevance decay per hop.

    Integration:
      - EntorhinalCortex.cognitive_map_distance() for conceptual distances
      - LocusCoeruleus.explore_exploit_balance() for creativity temperature
    """

    def __init__(self, moltbook=None, entorhinal=None, locus_coeruleus=None,
                 max_hops: int = 3, decay_per_hop: float = 0.5):
        self._moltbook = moltbook            # MoltbookStore
        self._entorhinal = entorhinal        # EntorhinalCortex (optional)
        self._locus_coeruleus = locus_coeruleus  # LocusCoeruleus (optional)
        self._max_hops = max_hops
        self._decay_per_hop = decay_per_hop
        self._total_chains = 0
        self._total_hops = 0
        logger.info("AssociativeThinking initialized")

    def associate(self, seed_text: str, temperature: float = 0.5,
                  max_results: int = 5) -> List[MicroThought]:
        """
        Generate associative thoughts from a seed text.

        Args:
            seed_text: Starting point for association chain
            temperature: Creativity level (0=focused, 1=wild associations)
            max_results: Maximum thoughts to generate

        Returns:
            List of MicroThought representing the association chain
        """
        if not self._moltbook:
            return []

        # Get creativity temperature from LC if available
        if self._locus_coeruleus:
            try:
                lc_state = self._locus_coeruleus.process({'task_type': 'creative'})
                if isinstance(lc_state, dict):
                    temperature = lc_state.get('explore_exploit_balance', temperature)
            except Exception:
                pass

        thoughts: List[MicroThought] = []
        visited_ids: set = set()
        current_text = seed_text
        relevance = 1.0

        for hop in range(self._max_hops):
            if relevance < 0.1:
                break

            # Search Moltbook for associations
            try:
                # Adjust top_k based on temperature (higher temp = more candidates)
                top_k = max(3, int(5 + temperature * 10))
                results = self._moltbook.query_semantic(
                    current_text, top_k=top_k,
                    threshold=max(0.1, 0.5 - temperature * 0.3)
                )
            except Exception:
                break

            if not results:
                break

            # Filter already visited
            candidates = [r for r in results if r.id not in visited_ids]
            if not candidates:
                break

            # Select next hop (temperature controls randomness)
            if temperature > 0.5 and len(candidates) > 1:
                # Higher temperature → more random selection
                idx = random.randint(0, min(len(candidates) - 1, int(temperature * len(candidates))))
                selected = candidates[idx]
            else:
                selected = candidates[0]

            visited_ids.add(selected.id)

            # Create thought from this hop
            thought = MicroThought(
                content=f"[hop_{hop}] {selected.content[:200]}",
                relevance_to_current_task=relevance,
                emotional_charge=selected.emotional_valence,
                arousal=selected.emotional_arousal,
                source_entry_ids=[selected.id],
                thought_type="association",
                activation=relevance,
            )
            thoughts.append(thought)

            # Prepare next hop
            current_text = selected.content
            relevance *= self._decay_per_hop
            self._total_hops += 1

        self._total_chains += 1
        return thoughts[:max_results]

    def find_creative_bridge(self, concept_a: str, concept_b: str,
                              max_bridge_length: int = 3) -> List[MicroThought]:
        """
        Find a creative bridge between two concepts via association chain.

        Useful for analogy generation: "A is to B as C is to D".
        """
        if not self._moltbook:
            return []

        # Get associations from both endpoints
        thoughts_a = self.associate(concept_a, temperature=0.7, max_results=max_bridge_length)
        thoughts_b = self.associate(concept_b, temperature=0.7, max_results=max_bridge_length)

        # Find overlap (concepts reachable from both sides)
        ids_a = set()
        for t in thoughts_a:
            ids_a.update(t.source_entry_ids)

        bridge = []
        for t in thoughts_b:
            for eid in t.source_entry_ids:
                if eid in ids_a:
                    bridge_thought = MicroThought(
                        content=f"[bridge] {t.content}",
                        relevance_to_current_task=0.8,
                        thought_type="association",
                        source_entry_ids=t.source_entry_ids,
                    )
                    bridge.append(bridge_thought)

        return bridge

    def get_stats(self) -> Dict[str, Any]:
        return {
            'total_chains': self._total_chains,
            'total_hops': self._total_hops,
            'avg_hops_per_chain': self._total_hops / max(1, self._total_chains),
        }


# ═══════════════════════════════════════════════════════════════════
# [14] EmotionalThinking — Affect-Modulated Thought Generation
# ═══════════════════════════════════════════════════════════════════

class EmotionalThinking:
    """
    Emotion-modulated thought generation.

    Based on Fredrickson's Broaden-and-Build theory:
      - Positive affect → broader associations (exploration)
      - Negative affect → narrower, focused thinking (threat focus)

    Integration:
      - CoreAffectSpace for valence × arousal
      - AmygdalaComplex for threat-relevant thinking
    """

    def __init__(self, core_affect=None, amygdala=None):
        self._core_affect = core_affect    # CoreAffectSpace (optional)
        self._amygdala = amygdala          # AmygdalaComplex (optional)
        self._current_valence = 0.0
        self._current_arousal = 0.5
        logger.info("EmotionalThinking initialized")

    def update_affect(self, valence: float = 0.0, arousal: float = 0.5) -> None:
        """Update current emotional state."""
        self._current_valence = max(-1.0, min(1.0, valence))
        self._current_arousal = max(0.0, min(1.0, arousal))

    def get_search_breadth(self) -> float:
        """
        Compute search breadth based on current affect.

        Positive valence → broader search (Broaden-and-Build)
        Negative valence → narrower search (threat focus)

        Returns: breadth factor (0.3 = very narrow, 1.0 = very broad)
        """
        # Map valence from [-1,1] to breadth [0.3, 1.0]
        breadth = 0.65 + 0.35 * self._current_valence
        return max(0.3, min(1.0, breadth))

    def get_similarity_threshold(self) -> float:
        """
        Compute similarity threshold based on affect.

        Positive → lower threshold (accept more distant associations)
        Negative → higher threshold (only close matches)
        """
        base = 0.5
        adjustment = -0.2 * self._current_valence  # positive valence lowers threshold
        return max(0.2, min(0.9, base + adjustment))

    def modulate_thought(self, thought: MicroThought) -> MicroThought:
        """
        Apply emotional modulation to a thought.

        Adjusts the thought's emotional charge and activation based
        on current affect state.
        """
        # Emotional coloring
        thought.emotional_charge = (
            0.7 * thought.emotional_charge + 0.3 * self._current_valence
        )
        thought.arousal = (
            0.7 * thought.arousal + 0.3 * self._current_arousal
        )

        # High arousal → higher activation (more salient)
        thought.activation *= (0.8 + 0.4 * self._current_arousal)

        # Threat-relevant boost via amygdala
        if self._amygdala and self._current_valence < -0.3:
            try:
                threat = self._amygdala.process({
                    'stimulus': thought.content,
                    'stimulus_type': 'thought'
                })
                if isinstance(threat, dict):
                    threat_level = threat.get('threat_level', 0)
                    if threat_level > 0.5:
                        thought.activation *= 1.5  # Threat-relevant thoughts get boosted
                        thought.thought_type = "threat_assessment"
            except Exception:
                pass

        return thought

    def get_state(self) -> Dict[str, Any]:
        return {
            'valence': self._current_valence,
            'arousal': self._current_arousal,
            'search_breadth': self.get_search_breadth(),
            'similarity_threshold': self.get_similarity_threshold(),
        }


# ═══════════════════════════════════════════════════════════════════
# [11] ThoughtStream — Continuous Background Thinking
# ═══════════════════════════════════════════════════════════════════

class ThoughtStream:
    """
    Continuous background micro-thought generator.

    Runs as a background process, generating internal thoughts every
    100-500ms by combining:
      - Current task context
      - Moltbook knowledge (semantic retrieval)
      - DMN spontaneous associations
      - Emotional modulation

    Thoughts flow into the ThoughtBuffer where they compete for
    conscious broadcast (Global Workspace).
    """

    def __init__(self, moltbook=None, dmn=None, core_affect=None,
                 buffer: Optional[ThoughtBuffer] = None,
                 interval_ms: int = 200):
        self._moltbook = moltbook           # MoltbookStore
        self._dmn = dmn                     # DefaultModeNetwork (optional)
        self._core_affect = core_affect     # CoreAffectSpace (optional)
        self._buffer = buffer or ThoughtBuffer()
        self._interval_ms = interval_ms

        # Thinking components
        self._associative = AssociativeThinking(moltbook=moltbook)
        self._emotional = EmotionalThinking(core_affect=core_affect)

        # State
        self._current_context: str = ""
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._total_ticks = 0

        # Thought seeds (topics to think about)
        self._seeds: List[str] = []
        self._seed_lock = threading.Lock()

        logger.info(f"ThoughtStream initialized (interval={interval_ms}ms)")

    @property
    def buffer(self) -> ThoughtBuffer:
        """Access the thought buffer."""
        return self._buffer

    @property
    def is_running(self) -> bool:
        return self._running

    def set_context(self, context: str) -> None:
        """Set the current task context for thought generation."""
        self._current_context = context

    def add_seed(self, seed: str) -> None:
        """Add a thought seed — a topic to think about."""
        with self._seed_lock:
            self._seeds.append(seed)
            # Keep last 20 seeds
            if len(self._seeds) > 20:
                self._seeds = self._seeds[-20:]

    def background_tick(self) -> Optional[MicroThought]:
        """
        Generate one micro-thought. Called by AgentLoop during idle,
        or by the background thread.

        Returns the generated thought, or None if nothing to think about.
        """
        self._total_ticks += 1

        # Pick a seed to think about
        seed = self._pick_seed()
        if not seed:
            return None

        # Generate thought via association
        thoughts = self._associative.associate(seed, temperature=0.5, max_results=1)

        if thoughts:
            thought = thoughts[0]
        else:
            # Fallback: simple context-echo thought
            thought = MicroThought(
                content=f"Thinking about: {seed[:100]}",
                relevance_to_current_task=0.3,
                thought_type="reflection",
            )

        # DMN spontaneous association (if available)
        if self._dmn:
            try:
                dmn_result = self._dmn.process({
                    'mode': 'mind_wandering',
                    'seed': seed[:50]
                })
                if isinstance(dmn_result, dict):
                    wandering = dmn_result.get('mind_wandering', {})
                    if isinstance(wandering, dict):
                        novel = wandering.get('novel_combination', '')
                        if novel:
                            thought.content += f" → {str(novel)[:100]}"
            except Exception:
                pass

        # Emotional modulation
        thought = self._emotional.modulate_thought(thought)

        # Add to buffer
        self._buffer.add(thought)
        return thought

    def _pick_seed(self) -> Optional[str]:
        """Pick a seed for thought generation."""
        with self._seed_lock:
            seeds = list(self._seeds)

        candidates = []

        # Current context is always a candidate
        if self._current_context:
            candidates.append(self._current_context)

        # Recent seeds
        candidates.extend(seeds[-5:])

        if not candidates:
            return None

        # Weighted random: current context gets higher weight
        if len(candidates) == 1:
            return candidates[0]

        weights = [2.0] + [1.0] * (len(candidates) - 1)  # Context gets 2x weight
        total = sum(weights)
        r = random.random() * total
        cumulative = 0.0
        for i, w in enumerate(weights):
            cumulative += w
            if r <= cumulative:
                return candidates[i]
        return candidates[0]

    def start(self) -> None:
        """Start background thought generation thread."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(
            target=self._run_loop, daemon=True, name="ThoughtStream"
        )
        self._thread.start()
        logger.info("ThoughtStream started")

    def stop(self) -> None:
        """Stop background thought generation."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=2.0)
            self._thread = None
        logger.info("ThoughtStream stopped")

    def _run_loop(self) -> None:
        """Background loop generating thoughts at configured interval."""
        while self._running:
            try:
                self.background_tick()
            except Exception as e:
                logger.warning(f"ThoughtStream tick error: {e}")
            time.sleep(self._interval_ms / 1000.0)

    def get_relevant_thoughts(self, context: str, top_k: int = 5) -> List[MicroThought]:
        """Get the most relevant thoughts for a given context."""
        return self._buffer.get_workspace(context)[:top_k]

    def get_stats(self) -> Dict[str, Any]:
        return {
            'running': self._running,
            'total_ticks': self._total_ticks,
            'interval_ms': self._interval_ms,
            'buffer': self._buffer.get_stats(),
            'associative': self._associative.get_stats(),
            'emotional': self._emotional.get_state(),
            'seed_count': len(self._seeds),
        }

    @classmethod
    def from_yaml(cls, yaml_config: Dict[str, Any]) -> 'ThoughtStream':
        """Create from YAML config."""
        mb = yaml_config.get('moltbook', {})
        return cls(interval_ms=mb.get('thought_stream_interval_ms', 200))


# ═══════════════════════════════════════════════════════════════════
# [15] MetaThinking — Thinking About Thinking
# ═══════════════════════════════════════════════════════════════════

class MetaThinking:
    """
    Meta-cognitive monitoring of the thought stream.

    Monitors:
      - Are thoughts productive? (leading toward task resolution)
      - Are thoughts circular? (repeating same patterns)
      - Should we continue thinking? (Expected Value of Control)
      - What's the quality of the thought chain?

    Integration:
      - ACC.expected_value_of_control() for EVC
      - WisdomModule.record_reflection() for wisdom accumulation
    """

    def __init__(self, acc=None, wisdom=None,
                 circularity_threshold: float = 0.7):
        self._acc = acc                    # AnteriorCingulateCortex (optional)
        self._wisdom = wisdom              # WisdomModule (optional)
        self._circularity_threshold = circularity_threshold

        # History for circularity detection
        self._recent_thought_hashes: deque = deque(maxlen=50)
        self._total_evaluations = 0
        self._redirects = 0

        logger.info("MetaThinking initialized")

    def evaluate(self, thoughts: Optional[List[MicroThought]] = None,
                 unified_thought: Optional[Any] = None) -> ThoughtQuality:
        """
        Evaluate the quality of current thoughts.

        Can evaluate either a list of micro-thoughts (from buffer)
        or a unified thought (from InternalMonologue).

        Returns ThoughtQuality assessment with recommendation.
        """
        self._total_evaluations += 1

        if thoughts is None and unified_thought is None:
            return ThoughtQuality(recommendation="continue")

        quality = ThoughtQuality()

        # Evaluate list of micro-thoughts
        if thoughts:
            quality = self._evaluate_thought_list(thoughts, quality)

        # Evaluate unified thought (from thinker)
        if unified_thought:
            quality = self._evaluate_unified(unified_thought, quality)

        # Get EVC from ACC if available
        if self._acc:
            try:
                evc_result = self._acc.process({
                    'task_type': 'thinking',
                    'effort': 0.5,
                    'expected_reward': quality.productivity,
                })
                if isinstance(evc_result, dict):
                    evc = evc_result.get('evc', evc_result.get('expected_value_of_control', 0.5))
                    quality.value_of_control = float(evc) if isinstance(evc, (int, float)) else 0.5
            except Exception:
                pass

        # Record reflection in wisdom module
        if self._wisdom and quality.productivity > 0.7:
            try:
                self._wisdom.record_reflection({
                    'type': 'meta_thinking',
                    'quality': quality.to_dict(),
                })
            except Exception:
                pass

        # Generate recommendation
        quality.recommendation = self._generate_recommendation(quality)

        return quality

    def _evaluate_thought_list(self, thoughts: List[MicroThought],
                                quality: ThoughtQuality) -> ThoughtQuality:
        """Evaluate a list of micro-thoughts."""
        if not thoughts:
            return quality

        # Productivity: average relevance to task
        quality.productivity = sum(
            t.relevance_to_current_task for t in thoughts
        ) / len(thoughts)

        # Creativity: diversity of source entries
        all_sources = set()
        for t in thoughts:
            all_sources.update(t.source_entry_ids)
        quality.creativity = min(1.0, len(all_sources) / max(1, len(thoughts) * 2))

        # Circularity: detect repeated content patterns
        current_hashes = []
        for t in thoughts:
            h = hash(t.content[:50])
            current_hashes.append(h)

        # Check overlap with recent thought hashes
        recent = set(self._recent_thought_hashes)
        if current_hashes:
            overlap = sum(1 for h in current_hashes if h in recent) / len(current_hashes)
            quality.circularity = overlap

        # Update history
        for h in current_hashes:
            self._recent_thought_hashes.append(h)

        # Coherence: how well do thoughts relate to each other?
        if len(thoughts) >= 2:
            type_consistency = len(set(t.thought_type for t in thoughts)) / len(thoughts)
            quality.coherence = 1.0 - type_consistency * 0.5  # More consistent → higher coherence

        return quality

    def _evaluate_unified(self, unified_thought: Any,
                           quality: ThoughtQuality) -> ThoughtQuality:
        """Evaluate a unified thought from InternalMonologue."""
        # If unified_thought is a dict or has attributes
        if isinstance(unified_thought, dict):
            quality.productivity = unified_thought.get('confidence', 0.5)
            quality.coherence = unified_thought.get('coherence', 0.5)
        elif hasattr(unified_thought, 'confidence'):
            quality.productivity = getattr(unified_thought, 'confidence', 0.5)
            quality.coherence = getattr(unified_thought, 'coherence', 0.5)

        return quality

    def _generate_recommendation(self, quality: ThoughtQuality) -> str:
        """Generate a recommendation based on quality assessment."""
        if quality.circularity > self._circularity_threshold:
            self._redirects += 1
            return "redirect"  # Thoughts are circular, need redirection

        if quality.value_of_control < 0.3:
            return "pause"  # Not worth continuing to think

        if quality.productivity < 0.3 and quality.creativity < 0.3:
            return "redirect"  # Neither productive nor creative

        if quality.productivity > 0.7:
            return "deepen"  # Productive thoughts, go deeper

        return "continue"  # Default: keep going

    def should_redirect(self) -> bool:
        """Quick check: should the thought stream be redirected?"""
        recent = list(self._recent_thought_hashes)[-10:]
        if len(recent) < 5:
            return False
        unique = len(set(recent))
        return unique / len(recent) < 0.5  # >50% duplicates → redirect

    def get_stats(self) -> Dict[str, Any]:
        return {
            'total_evaluations': self._total_evaluations,
            'redirects': self._redirects,
            'recent_thought_hash_count': len(self._recent_thought_hashes),
        }
