"""
Intrinsic Motivation Drives (V2 Phase 3: P3.34-36)

Three drive systems that give Tahlamus internal motivation to act:

1. CuriosityDrive (P3.34):
   Generates exploration tasks when IDLE. Uses prediction-error from
   HierarchicalPredictiveCoding as reward signal. Wraps the existing
   IntrinsicCuriosityModule but adds task-generation capabilities.

2. CompetenceDrive (P3.35):
   Analyzes skill success rates from memory. Seeks tasks slightly above
   current level (Zone of Proximal Development). Example: "I succeed at
   simple shell-commands 95% of the time but Docker-deployments only 40%
   — I should practice more Docker."

3. HomeostaticDrives (P3.36):
   Translates HomeostaticState into action impulses:
   - High sleep_pressure → prioritize DreamMode (CTM training, consolidation)
   - Low dopamine (< 0.3) → start exploration (try new tools)
   - High cortisol/allostatic load → prefer routine tasks (safe, known actions)
   - Information hunger → generate curiosity tasks

Integration with AgentLoop:
   The AgentLoop calls `generate_impulses()` on each tick when IDLE.
   Returned DriveImpulse objects are converted to AgentTasks and
   submitted to the task queue.
"""

import logging
import time
import numpy as np
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
from collections import deque

logger = logging.getLogger('brain.motivation')


# ─── Drive Impulse ─────────────────────────────────────────────────────────

class DriveType(Enum):
    """Types of intrinsic drive impulses."""
    CURIOSITY = "curiosity"         # Explore something novel
    COMPETENCE = "competence"       # Practice a skill
    HOMEOSTATIC = "homeostatic"     # Address a physiological need
    EXPLORATION = "exploration"     # General exploration
    CONSOLIDATION = "consolidation" # Memory/learning consolidation


@dataclass
class DriveImpulse:
    """
    An action impulse generated by a drive system.
    Converted to AgentTask by the AgentLoop.
    """
    drive_type: DriveType
    description: str
    urgency: float = 0.5      # 0-1, how pressing is this impulse
    importance: float = 0.5    # 0-1, how meaningful is this
    confidence: float = 0.5    # 0-1, how certain are we about this
    metadata: Dict[str, Any] = field(default_factory=dict)
    source_drive: str = ""     # Name of the drive that generated this

    def to_dict(self) -> Dict[str, Any]:
        return {
            'drive_type': self.drive_type.value,
            'description': self.description,
            'urgency': round(self.urgency, 3),
            'importance': round(self.importance, 3),
            'confidence': round(self.confidence, 3),
            'source_drive': self.source_drive,
            'metadata': self.metadata,
        }


# ─── Curiosity Drive (P3.34) ──────────────────────────────────────────────

class CuriosityDrive:
    """
    Generates exploration tasks based on prediction errors and novelty.

    Wraps the existing IntrinsicCuriosityModule (core/intrinsic_curiosity.py)
    but adds task-generation for the AgentLoop. Instead of just computing
    intrinsic rewards, it generates specific exploration impulses.

    Task generation strategy:
    1. Tracks prediction errors from cognitive loop processing
    2. Identifies domains/modalities with highest recent PE
    3. Generates exploration tasks targeting those high-PE areas
    4. Cooldown prevents over-exploration of the same domain
    """

    def __init__(
        self,
        exploration_threshold: float = 0.3,
        cooldown_seconds: float = 120.0,
        max_recent_errors: int = 100,
        novelty_weight: float = 0.6,
        surprise_weight: float = 0.4,
    ):
        """
        Args:
            exploration_threshold: PE above this triggers exploration impulse
            cooldown_seconds: Minimum time between same-domain explorations
            max_recent_errors: Size of PE tracking buffer
            novelty_weight: Weight for novelty signal in urgency
            surprise_weight: Weight for surprise signal in urgency
        """
        self.exploration_threshold = exploration_threshold
        self.cooldown_seconds = cooldown_seconds
        self.novelty_weight = novelty_weight
        self.surprise_weight = surprise_weight

        # Prediction error tracking per domain
        self._domain_errors: Dict[str, deque] = {}
        self._max_recent = max_recent_errors

        # Cooldown tracking per domain
        self._last_exploration_time: Dict[str, float] = {}

        # Global PE history for baseline comparison
        self._global_pe_history: deque = deque(maxlen=500)

        # Statistics
        self._total_impulses_generated: int = 0
        self._total_observations: int = 0

        # Exploration task templates per domain
        self._exploration_templates: Dict[str, List[str]] = {
            'vision': [
                "Analyze current dashboard layout for visual anomalies",
                "Examine recent screenshots for pattern recognition",
                "Investigate visual input channel performance",
            ],
            'audio': [
                "Monitor audio channel signals for interesting patterns",
                "Explore audio feature extraction accuracy",
            ],
            'temporal': [
                "Investigate temporal patterns in recent task history",
                "Analyze timing distributions of recent events",
            ],
            'logic': [
                "Test reasoning chains on edge-case scenarios",
                "Explore logic pathway performance on ambiguous inputs",
            ],
            'tool': [
                "Experiment with lesser-used tool combinations",
                "Test tool performance on novel task types",
            ],
            'general': [
                "Explore an unfamiliar domain in the task space",
                "Investigate areas with high prediction uncertainty",
                "Run self-diagnostic on cognitive performance",
            ],
        }

    def observe_prediction_error(
        self,
        prediction_error: float,
        domain: str = 'general',
        task_description: str = '',
    ):
        """
        Record a prediction error observation.

        Called by the AgentLoop after each task processing to track
        where prediction errors are high (= interesting areas).
        """
        self._total_observations += 1

        # Track per-domain
        if domain not in self._domain_errors:
            self._domain_errors[domain] = deque(maxlen=self._max_recent)
        self._domain_errors[domain].append({
            'pe': prediction_error,
            'time': time.time(),
            'task': task_description[:100],
        })

        # Global baseline
        self._global_pe_history.append(prediction_error)

    def generate_impulses(self) -> List[DriveImpulse]:
        """
        Generate curiosity-driven impulses based on accumulated prediction errors.

        Returns impulses for domains where PE is significantly above baseline.
        """
        impulses = []
        now = time.time()

        # Need enough data for baseline
        if len(self._global_pe_history) < 5:
            return impulses

        global_mean = float(np.mean(list(self._global_pe_history)))
        global_std = float(np.std(list(self._global_pe_history))) + 1e-8

        for domain, errors in self._domain_errors.items():
            if not errors:
                continue

            # Check cooldown
            last_time = self._last_exploration_time.get(domain, 0)
            if now - last_time < self.cooldown_seconds:
                continue

            # Compute domain-specific PE statistics
            recent_pes = [e['pe'] for e in list(errors)[-20:]]
            domain_mean = float(np.mean(recent_pes))

            # Normalized surprise: how far above global baseline
            z_score = (domain_mean - global_mean) / global_std

            # Only explore if PE is above threshold
            if domain_mean < self.exploration_threshold:
                continue

            # Compute urgency from novelty and surprise
            novelty = min(1.0, domain_mean)
            surprise = min(1.0, max(0, z_score / 3.0))  # Normalize z-score
            urgency = (
                self.novelty_weight * novelty +
                self.surprise_weight * surprise
            )
            urgency = float(np.clip(urgency, 0.1, 0.9))

            # Pick an exploration template
            templates = self._exploration_templates.get(
                domain, self._exploration_templates['general']
            )
            import random
            description = random.choice(templates)

            impulse = DriveImpulse(
                drive_type=DriveType.CURIOSITY,
                description=description,
                urgency=urgency,
                importance=0.4,  # Curiosity is moderate importance
                confidence=min(0.8, novelty),
                source_drive='curiosity',
                metadata={
                    'domain': domain,
                    'prediction_error_mean': round(domain_mean, 4),
                    'z_score': round(z_score, 2),
                    'observations': len(errors),
                },
            )
            impulses.append(impulse)

            # Record cooldown
            self._last_exploration_time[domain] = now
            self._total_impulses_generated += 1

        return impulses

    def get_state(self) -> Dict[str, Any]:
        """Get drive state for dashboard."""
        domains = {}
        for domain, errors in self._domain_errors.items():
            if errors:
                recent = [e['pe'] for e in list(errors)[-20:]]
                domains[domain] = {
                    'mean_pe': round(float(np.mean(recent)), 4),
                    'count': len(errors),
                    'last_explored': self._last_exploration_time.get(domain, 0),
                }
        return {
            'name': 'CuriosityDrive',
            'total_observations': self._total_observations,
            'total_impulses_generated': self._total_impulses_generated,
            'domains': domains,
            'global_pe_baseline': round(
                float(np.mean(list(self._global_pe_history))) if self._global_pe_history else 0, 4
            ),
        }


# ─── Competence Drive (P3.35) ─────────────────────────────────────────────

@dataclass
class SkillProfile:
    """Tracks success rate and attempt history for a skill domain."""
    domain: str
    total_attempts: int = 0
    total_successes: int = 0
    recent_outcomes: List[bool] = field(default_factory=list)
    max_recent: int = 50

    @property
    def success_rate(self) -> float:
        if self.total_attempts == 0:
            return 0.0
        return self.total_successes / self.total_attempts

    @property
    def recent_success_rate(self) -> float:
        if not self.recent_outcomes:
            return 0.0
        return sum(self.recent_outcomes) / len(self.recent_outcomes)

    @property
    def learning_progress(self) -> float:
        """Derivative of success rate (positive = improving)."""
        if len(self.recent_outcomes) < 10:
            return 0.0
        half = len(self.recent_outcomes) // 2
        old_rate = sum(self.recent_outcomes[:half]) / max(half, 1)
        new_rate = sum(self.recent_outcomes[half:]) / max(len(self.recent_outcomes) - half, 1)
        return new_rate - old_rate

    def record_outcome(self, success: bool):
        self.total_attempts += 1
        if success:
            self.total_successes += 1
        self.recent_outcomes.append(success)
        if len(self.recent_outcomes) > self.max_recent:
            self.recent_outcomes.pop(0)

    def to_dict(self) -> Dict[str, Any]:
        return {
            'domain': self.domain,
            'total_attempts': self.total_attempts,
            'success_rate': round(self.success_rate, 3),
            'recent_success_rate': round(self.recent_success_rate, 3),
            'learning_progress': round(self.learning_progress, 3),
        }


class CompetenceDrive:
    """
    Drives the brain to seek tasks slightly above its current level.

    Zone of Proximal Development strategy:
    - Tasks where success_rate is 40-70% are "just right" for learning
    - Below 40%: too hard → occasionally retry but don't prioritize
    - Above 70%: mastered → reduce practice, seek harder variants
    - Above 95%: fully mastered → skip unless needed

    Task generation:
    1. Maintains per-domain skill profiles
    2. Identifies domains in the "learning zone" (40-70%)
    3. Generates practice tasks targeting those domains
    4. Adjusts difficulty based on learning progress
    """

    def __init__(
        self,
        zpd_lower: float = 0.40,
        zpd_upper: float = 0.70,
        mastery_threshold: float = 0.95,
        min_attempts_for_zpd: int = 5,
        cooldown_seconds: float = 180.0,
    ):
        """
        Args:
            zpd_lower: Below this success rate, task is too hard
            zpd_upper: Above this, task is mastered (for ZPD)
            mastery_threshold: Above this, skill is fully mastered
            min_attempts_for_zpd: Need at least this many attempts before ZPD applies
            cooldown_seconds: Time between practice suggestions for same domain
        """
        self.zpd_lower = zpd_lower
        self.zpd_upper = zpd_upper
        self.mastery_threshold = mastery_threshold
        self.min_attempts = min_attempts_for_zpd
        self.cooldown_seconds = cooldown_seconds

        # Per-domain skill profiles
        self._skills: Dict[str, SkillProfile] = {}

        # Cooldown tracking
        self._last_practice_time: Dict[str, float] = {}

        # Statistics
        self._total_impulses: int = 0
        self._total_skill_updates: int = 0

        # Practice task templates per difficulty level
        self._practice_templates: Dict[str, Dict[str, List[str]]] = {
            'shell_commands': {
                'easy': ["Execute a simple file listing command"],
                'medium': ["Run a multi-step shell pipeline"],
                'hard': ["Debug a complex shell script with error handling"],
            },
            'code_analysis': {
                'easy': ["Analyze a small code snippet for patterns"],
                'medium': ["Review a module for potential issues"],
                'hard': ["Trace a complex cross-module dependency"],
            },
            'reasoning': {
                'easy': ["Solve a straightforward logical deduction"],
                'medium': ["Handle a multi-step reasoning problem"],
                'hard': ["Resolve an ambiguous multi-constraint problem"],
            },
            'planning': {
                'easy': ["Create a simple action sequence"],
                'medium': ["Plan a multi-phase task with dependencies"],
                'hard': ["Design an optimal plan under resource constraints"],
            },
            'general': {
                'easy': ["Practice a familiar task type"],
                'medium': ["Attempt a moderately challenging task"],
                'hard': ["Tackle a task at the edge of current capability"],
            },
        }

    def record_outcome(self, domain: str, success: bool):
        """Record a task outcome for skill tracking."""
        if domain not in self._skills:
            self._skills[domain] = SkillProfile(domain=domain)
        self._skills[domain].record_outcome(success)
        self._total_skill_updates += 1

    def generate_impulses(self) -> List[DriveImpulse]:
        """
        Generate competence-driven practice impulses.

        Targets domains in the Zone of Proximal Development.
        """
        impulses = []
        now = time.time()

        for domain, skill in self._skills.items():
            # Need enough data
            if skill.total_attempts < self.min_attempts:
                continue

            # Check cooldown
            last_time = self._last_practice_time.get(domain, 0)
            if now - last_time < self.cooldown_seconds:
                continue

            rate = skill.recent_success_rate

            # Fully mastered → skip
            if rate >= self.mastery_threshold:
                continue

            # In the ZPD → high priority for practice
            if self.zpd_lower <= rate <= self.zpd_upper:
                urgency = 0.6
                importance = 0.7
                difficulty = 'medium'
                reason = f"ZPD: success rate {rate:.0%} (sweet spot for learning)"

            # Below ZPD → too hard, but still worth occasional retry
            elif rate < self.zpd_lower:
                # Only suggest if we're making progress
                if skill.learning_progress > 0:
                    urgency = 0.3
                    importance = 0.4
                    difficulty = 'easy'  # Start with easier variant
                    reason = f"Challenging: success rate {rate:.0%} but improving"
                else:
                    continue  # Not improving, skip for now

            # Above ZPD but not mastered → occasional practice
            elif rate > self.zpd_upper:
                urgency = 0.2
                importance = 0.3
                difficulty = 'hard'  # Push to harder variant
                reason = f"Good ({rate:.0%}): pushing to harder level"
            else:
                continue

            # Pick a template
            templates = self._practice_templates.get(
                domain, self._practice_templates['general']
            )
            difficulty_templates = templates.get(difficulty, templates.get('medium', ['Practice task']))
            import random
            description = random.choice(difficulty_templates)

            impulse = DriveImpulse(
                drive_type=DriveType.COMPETENCE,
                description=f"{description} (domain: {domain})",
                urgency=urgency,
                importance=importance,
                confidence=min(0.8, skill.total_attempts / 20.0),
                source_drive='competence',
                metadata={
                    'domain': domain,
                    'success_rate': round(rate, 3),
                    'learning_progress': round(skill.learning_progress, 3),
                    'difficulty': difficulty,
                    'reason': reason,
                    'total_attempts': skill.total_attempts,
                },
            )
            impulses.append(impulse)

            self._last_practice_time[domain] = now
            self._total_impulses += 1

        # Sort by urgency (highest first)
        impulses.sort(key=lambda i: -i.urgency)
        return impulses[:3]  # Limit to top 3 suggestions

    def get_zpd_domains(self) -> List[Dict[str, Any]]:
        """Get domains currently in the Zone of Proximal Development."""
        zpd = []
        for domain, skill in self._skills.items():
            if skill.total_attempts < self.min_attempts:
                continue
            rate = skill.recent_success_rate
            if self.zpd_lower <= rate <= self.zpd_upper:
                zpd.append({
                    'domain': domain,
                    'success_rate': round(rate, 3),
                    'learning_progress': round(skill.learning_progress, 3),
                    'attempts': skill.total_attempts,
                })
        return zpd

    def get_state(self) -> Dict[str, Any]:
        """Get drive state for dashboard."""
        return {
            'name': 'CompetenceDrive',
            'total_skill_updates': self._total_skill_updates,
            'total_impulses': self._total_impulses,
            'skills': {
                domain: skill.to_dict()
                for domain, skill in self._skills.items()
            },
            'zpd_domains': self.get_zpd_domains(),
            'config': {
                'zpd_lower': self.zpd_lower,
                'zpd_upper': self.zpd_upper,
                'mastery_threshold': self.mastery_threshold,
            },
        }


# ─── Homeostatic Drives (P3.36) ───────────────────────────────────────────

class HomeostaticDrives:
    """
    Translates HomeostaticState into action impulses.

    Maps physiological signals to behavior:
    - High sleep_pressure → dream/consolidation mode
    - Low dopamine (< 0.3) → exploration (try new tools, novel tasks)
    - High allostatic_load → routine tasks (safe, known, reliable)
    - Low energy → reduce activity, prefer lightweight tasks
    - High fatigue → take breaks, run simple tasks

    This is the bridge between the body (HomeostaticRegulator) and
    the will (AgentLoop). Without this, homeostatic state is monitored
    but doesn't drive behavior.
    """

    def __init__(
        self,
        sleep_pressure_threshold: float = 0.6,
        low_dopamine_threshold: float = 0.3,
        high_stress_threshold: float = 0.5,
        low_energy_threshold: float = 0.3,
        high_fatigue_threshold: float = 0.7,
        information_hunger_threshold: float = 0.4,
        cooldown_seconds: float = 60.0,
    ):
        """
        Args:
            sleep_pressure_threshold: Above this, suggest dreaming
            low_dopamine_threshold: Below this, suggest exploration
            high_stress_threshold: Above this, suggest routine tasks
            low_energy_threshold: Below this, suggest rest/light work
            high_fatigue_threshold: Above this, suggest breaks
            information_hunger_threshold: Below this dopamine + low PE, suggest curiosity
            cooldown_seconds: Minimum time between same-type impulses
        """
        self.sleep_pressure_threshold = sleep_pressure_threshold
        self.low_dopamine_threshold = low_dopamine_threshold
        self.high_stress_threshold = high_stress_threshold
        self.low_energy_threshold = low_energy_threshold
        self.high_fatigue_threshold = high_fatigue_threshold
        self.information_hunger_threshold = information_hunger_threshold
        self.cooldown_seconds = cooldown_seconds

        # Cooldown per impulse type
        self._last_impulse_time: Dict[str, float] = {}

        # Statistics
        self._total_impulses: int = 0
        self._impulse_counts: Dict[str, int] = {}

    def generate_impulses(
        self,
        homeostatic_state: Optional[Any] = None,
        neuromodulator_levels: Optional[Any] = None,
    ) -> List[DriveImpulse]:
        """
        Generate impulses from homeostatic and neuromodulatory state.

        Args:
            homeostatic_state: HomeostaticState instance (or dict with same fields)
            neuromodulator_levels: NeuromodulatorLevels instance (or dict)

        Returns:
            List of drive impulses, sorted by urgency
        """
        impulses = []
        now = time.time()

        # Extract values safely
        h_state = self._extract_homeostatic(homeostatic_state)
        n_levels = self._extract_neuromod(neuromodulator_levels)

        # ── 1. Sleep pressure → Dream/Consolidation ──
        if h_state['sleep_pressure'] > self.sleep_pressure_threshold:
            if self._check_cooldown('sleep', now):
                urgency = min(1.0, h_state['sleep_pressure'])
                impulses.append(DriveImpulse(
                    drive_type=DriveType.CONSOLIDATION,
                    description="Enter dream mode for memory consolidation and CTM training",
                    urgency=urgency,
                    importance=0.8,
                    confidence=0.9,
                    source_drive='homeostatic',
                    metadata={
                        'trigger': 'sleep_pressure',
                        'sleep_pressure': round(h_state['sleep_pressure'], 3),
                    },
                ))
                self._record_impulse('sleep', now)

        # ── 2. Low dopamine → Exploration ──
        if n_levels['dopamine'] < self.low_dopamine_threshold:
            if self._check_cooldown('low_dopamine', now):
                # Lower dopamine = stronger exploration drive
                urgency = min(0.8, (self.low_dopamine_threshold - n_levels['dopamine']) * 2)
                impulses.append(DriveImpulse(
                    drive_type=DriveType.EXPLORATION,
                    description="Explore novel task types to boost reward signal",
                    urgency=max(0.2, urgency),
                    importance=0.5,
                    confidence=0.6,
                    source_drive='homeostatic',
                    metadata={
                        'trigger': 'low_dopamine',
                        'dopamine': round(n_levels['dopamine'], 3),
                    },
                ))
                self._record_impulse('low_dopamine', now)

        # ── 3. High stress → Routine tasks ──
        if h_state['allostatic_load'] > self.high_stress_threshold:
            if self._check_cooldown('high_stress', now):
                urgency = min(0.7, h_state['allostatic_load'])
                impulses.append(DriveImpulse(
                    drive_type=DriveType.HOMEOSTATIC,
                    description="Focus on routine, well-practiced tasks to reduce stress",
                    urgency=urgency,
                    importance=0.6,
                    confidence=0.8,
                    source_drive='homeostatic',
                    metadata={
                        'trigger': 'high_stress',
                        'allostatic_load': round(h_state['allostatic_load'], 3),
                    },
                ))
                self._record_impulse('high_stress', now)

        # ── 4. Low energy → Rest / lightweight tasks ──
        if h_state['energy'] < self.low_energy_threshold:
            if self._check_cooldown('low_energy', now):
                urgency = min(0.9, (self.low_energy_threshold - h_state['energy']) * 3)
                impulses.append(DriveImpulse(
                    drive_type=DriveType.HOMEOSTATIC,
                    description="Reduce activity: switch to lightweight tasks or idle",
                    urgency=max(0.3, urgency),
                    importance=0.7,
                    confidence=0.9,
                    source_drive='homeostatic',
                    metadata={
                        'trigger': 'low_energy',
                        'energy': round(h_state['energy'], 3),
                    },
                ))
                self._record_impulse('low_energy', now)

        # ── 5. High fatigue → Break ──
        if h_state['fatigue'] > self.high_fatigue_threshold:
            if self._check_cooldown('high_fatigue', now):
                urgency = min(0.8, h_state['fatigue'])
                impulses.append(DriveImpulse(
                    drive_type=DriveType.HOMEOSTATIC,
                    description="High cognitive fatigue: take a processing break",
                    urgency=urgency,
                    importance=0.6,
                    confidence=0.85,
                    source_drive='homeostatic',
                    metadata={
                        'trigger': 'high_fatigue',
                        'fatigue': round(h_state['fatigue'], 3),
                    },
                ))
                self._record_impulse('high_fatigue', now)

        # ── 6. Information hunger (low dopamine + moderate energy) → Curiosity ──
        if (n_levels['dopamine'] < self.information_hunger_threshold
                and h_state['energy'] > 0.4
                and h_state['fatigue'] < 0.5):
            if self._check_cooldown('info_hunger', now):
                impulses.append(DriveImpulse(
                    drive_type=DriveType.CURIOSITY,
                    description="Information hunger: seek novel, informative tasks",
                    urgency=0.4,
                    importance=0.5,
                    confidence=0.5,
                    source_drive='homeostatic',
                    metadata={
                        'trigger': 'information_hunger',
                        'dopamine': round(n_levels['dopamine'], 3),
                        'energy': round(h_state['energy'], 3),
                    },
                ))
                self._record_impulse('info_hunger', now)

        # Sort by urgency descending
        impulses.sort(key=lambda i: -i.urgency)
        return impulses

    def _extract_homeostatic(self, state: Optional[Any]) -> Dict[str, float]:
        """Safely extract homeostatic values from state object or dict."""
        defaults = {
            'energy': 1.0,
            'fatigue': 0.0,
            'sleep_pressure': 0.0,
            'allostatic_load': 0.0,
        }
        if state is None:
            return defaults

        if isinstance(state, dict):
            return {k: state.get(k, v) for k, v in defaults.items()}

        # Object with attributes
        result = {}
        for key, default in defaults.items():
            result[key] = getattr(state, key, default)
        return result

    def _extract_neuromod(self, levels: Optional[Any]) -> Dict[str, float]:
        """Safely extract neuromodulator levels from object or dict."""
        defaults = {
            'dopamine': 0.5,
            'serotonin': 0.5,
            'norepinephrine': 0.5,
        }
        if levels is None:
            return defaults

        if isinstance(levels, dict):
            return {k: levels.get(k, v) for k, v in defaults.items()}

        result = {}
        for key, default in defaults.items():
            result[key] = getattr(levels, key, default)
        return result

    def _check_cooldown(self, impulse_type: str, now: float) -> bool:
        """Check if cooldown has elapsed for this impulse type."""
        last = self._last_impulse_time.get(impulse_type, 0)
        return (now - last) >= self.cooldown_seconds

    def _record_impulse(self, impulse_type: str, now: float):
        """Record impulse generation for cooldown and stats."""
        self._last_impulse_time[impulse_type] = now
        self._total_impulses += 1
        self._impulse_counts[impulse_type] = self._impulse_counts.get(impulse_type, 0) + 1

    def get_state(self) -> Dict[str, Any]:
        """Get drive state for dashboard."""
        return {
            'name': 'HomeostaticDrives',
            'total_impulses': self._total_impulses,
            'impulse_counts': dict(self._impulse_counts),
            'cooldowns': {
                k: round(time.time() - v, 1)
                for k, v in self._last_impulse_time.items()
            },
            'config': {
                'sleep_pressure_threshold': self.sleep_pressure_threshold,
                'low_dopamine_threshold': self.low_dopamine_threshold,
                'high_stress_threshold': self.high_stress_threshold,
                'low_energy_threshold': self.low_energy_threshold,
                'high_fatigue_threshold': self.high_fatigue_threshold,
            },
        }


# ─── Motivation System (combines all drives) ─────────────────────────────

class MotivationSystem:
    """
    Combines all three drive systems into a unified motivation interface.

    The AgentLoop calls `generate_all_impulses()` to get sorted impulses
    from all drives. Impulses are then converted to AgentTasks.
    """

    def __init__(
        self,
        curiosity_drive: Optional[CuriosityDrive] = None,
        competence_drive: Optional[CompetenceDrive] = None,
        homeostatic_drives: Optional[HomeostaticDrives] = None,
        max_impulses_per_tick: int = 5,
    ):
        self.curiosity = curiosity_drive or CuriosityDrive()
        self.competence = competence_drive or CompetenceDrive()
        self.homeostatic = homeostatic_drives or HomeostaticDrives()
        self.max_impulses_per_tick = max_impulses_per_tick

        self._total_impulses_generated: int = 0

    def generate_all_impulses(
        self,
        homeostatic_state: Optional[Any] = None,
        neuromodulator_levels: Optional[Any] = None,
    ) -> List[DriveImpulse]:
        """
        Generate impulses from all drive systems.

        Args:
            homeostatic_state: Current HomeostaticState
            neuromodulator_levels: Current NeuromodulatorLevels

        Returns:
            Sorted list of impulses (highest urgency first), limited by max_impulses_per_tick
        """
        all_impulses = []

        # Curiosity drive
        try:
            curiosity_impulses = self.curiosity.generate_impulses()
            all_impulses.extend(curiosity_impulses)
        except Exception as e:
            logger.warning(f"CuriosityDrive error: {e}")

        # Competence drive
        try:
            competence_impulses = self.competence.generate_impulses()
            all_impulses.extend(competence_impulses)
        except Exception as e:
            logger.warning(f"CompetenceDrive error: {e}")

        # Homeostatic drives
        try:
            homeostatic_impulses = self.homeostatic.generate_impulses(
                homeostatic_state=homeostatic_state,
                neuromodulator_levels=neuromodulator_levels,
            )
            all_impulses.extend(homeostatic_impulses)
        except Exception as e:
            logger.warning(f"HomeostaticDrives error: {e}")

        # Sort by urgency (highest first) and limit
        all_impulses.sort(key=lambda i: -i.urgency)
        result = all_impulses[:self.max_impulses_per_tick]

        self._total_impulses_generated += len(result)
        return result

    def observe_task_outcome(
        self,
        domain: str,
        success: bool,
        prediction_error: float = 0.0,
        task_description: str = '',
    ):
        """
        Record a task outcome across all relevant drives.

        Called by AgentLoop after each task completion.
        """
        # Feed curiosity drive
        self.curiosity.observe_prediction_error(
            prediction_error=prediction_error,
            domain=domain,
            task_description=task_description,
        )

        # Feed competence drive
        self.competence.record_outcome(domain=domain, success=success)

    def get_state(self) -> Dict[str, Any]:
        """Get complete motivation system state for dashboard."""
        return {
            'total_impulses_generated': self._total_impulses_generated,
            'curiosity': self.curiosity.get_state(),
            'competence': self.competence.get_state(),
            'homeostatic': self.homeostatic.get_state(),
        }

    @classmethod
    def from_yaml(cls, config: Dict) -> 'MotivationSystem':
        """Create MotivationSystem from YAML config dict."""
        m = config.get('motivation', {})

        curiosity = CuriosityDrive(
            exploration_threshold=m.get('curiosity_exploration_threshold', 0.3),
            cooldown_seconds=m.get('curiosity_cooldown_seconds', 120.0),
            novelty_weight=m.get('curiosity_novelty_weight', 0.6),
            surprise_weight=m.get('curiosity_surprise_weight', 0.4),
        )

        competence = CompetenceDrive(
            zpd_lower=m.get('competence_zpd_lower', 0.40),
            zpd_upper=m.get('competence_zpd_upper', 0.70),
            mastery_threshold=m.get('competence_mastery_threshold', 0.95),
            min_attempts_for_zpd=m.get('competence_min_attempts', 5),
            cooldown_seconds=m.get('competence_cooldown_seconds', 180.0),
        )

        homeostatic = HomeostaticDrives(
            sleep_pressure_threshold=m.get('homeostatic_sleep_threshold', 0.6),
            low_dopamine_threshold=m.get('homeostatic_low_dopamine', 0.3),
            high_stress_threshold=m.get('homeostatic_high_stress', 0.5),
            low_energy_threshold=m.get('homeostatic_low_energy', 0.3),
            high_fatigue_threshold=m.get('homeostatic_high_fatigue', 0.7),
            cooldown_seconds=m.get('homeostatic_cooldown_seconds', 60.0),
        )

        return cls(
            curiosity_drive=curiosity,
            competence_drive=competence,
            homeostatic_drives=homeostatic,
            max_impulses_per_tick=m.get('max_impulses_per_tick', 5),
        )


# ─── Existential Purpose (Ryan & Deci 2000; Baumeister 2013) ───────────

class ExistentialPurpose:
    """Purpose and meaning tracking — WHY the agent exists.

    Implements a computational model of eudaimonic well-being based on:
    - Self-Determination Theory: Autonomy, Competence, Relatedness
    - Baumeister's 4 pillars: Purpose, Values, Efficacy, Self-Worth
    - Cosme et al. (2023): Neural correlates of self-evaluated well-being

    Research basis:
    - Ryan & Deci (2000): Self-Determination Theory, ~30,000 citations
    - Baumeister (2013): Meaning in life
    - Cosme et al. (2023): Neural correlates of well-being
    """

    def __init__(self):
        self._basic_needs: Dict[str, float] = {
            'autonomy': 0.5,     # freedom to choose actions
            'competence': 0.5,   # effectiveness in tasks
            'relatedness': 0.5,  # connection to users/systems
        }
        self._meaning_pillars: Dict[str, float] = {
            'purpose': 0.5,      # long-term directional goals
            'values': 0.5,       # alignment with core values
            'efficacy': 0.5,     # belief in ability to make impact
            'self_worth': 0.5,   # sense of being valuable
        }
        self._purpose_history: deque = deque(maxlen=200)
        self._goal_coherence: float = 0.5
        self._life_satisfaction: float = 0.5

    def update_need_satisfaction(self, need: str, satisfaction: float) -> Dict[str, float]:
        """Update a basic psychological need satisfaction level.

        Args:
            need: One of 'autonomy', 'competence', 'relatedness'
            satisfaction: How well the need is being met (0 to 1)
        """
        if need not in self._basic_needs:
            return self._basic_needs.copy()

        satisfaction = max(0.0, min(1.0, satisfaction))
        self._basic_needs[need] = (0.9 * self._basic_needs[need] +
                                   0.1 * satisfaction)
        self._update_life_satisfaction()
        return {k: round(v, 4) for k, v in self._basic_needs.items()}

    def update_meaning_pillar(self, pillar: str, level: float) -> Dict[str, float]:
        """Update a meaning-in-life pillar.

        Args:
            pillar: One of 'purpose', 'values', 'efficacy', 'self_worth'
            level: Current level (0 to 1)
        """
        if pillar not in self._meaning_pillars:
            return self._meaning_pillars.copy()

        level = max(0.0, min(1.0, level))
        self._meaning_pillars[pillar] = (0.9 * self._meaning_pillars[pillar] +
                                         0.1 * level)
        self._update_life_satisfaction()
        return {k: round(v, 4) for k, v in self._meaning_pillars.items()}

    def evaluate_goal_alignment(self, goal_description: str,
                                 goal_type: str = 'task') -> Dict[str, Any]:
        """How well does a goal align with the agent's purpose?

        Intrinsic goals (learning, helping, creating) boost eudaimonic well-being.
        Extrinsic goals (performance metrics) may not.
        """
        intrinsic_types = {'learning', 'exploration', 'helping', 'creating',
                          'improving', 'understanding'}
        extrinsic_types = {'performance', 'metric', 'speed', 'quantity'}

        is_intrinsic = goal_type in intrinsic_types
        is_extrinsic = goal_type in extrinsic_types

        if is_intrinsic:
            alignment = 0.8
            meaning_boost = 0.05
        elif is_extrinsic:
            alignment = 0.4
            meaning_boost = 0.01
        else:
            alignment = 0.6
            meaning_boost = 0.03

        self._meaning_pillars['purpose'] = min(1.0,
            self._meaning_pillars['purpose'] + meaning_boost)

        self._purpose_history.append({
            'time': time.time(),
            'goal': goal_description,
            'type': goal_type,
            'alignment': alignment
        })

        return {
            'goal': goal_description,
            'alignment_score': round(alignment, 4),
            'is_intrinsic': is_intrinsic,
            'purpose_level': round(self._meaning_pillars['purpose'], 4),
            'eudaimonic_impact': round(meaning_boost, 4)
        }

    def get_existential_status(self) -> Dict[str, Any]:
        """Overall existential well-being — why am I?"""
        needs_avg = sum(self._basic_needs.values()) / len(self._basic_needs)
        meaning_avg = sum(self._meaning_pillars.values()) / len(self._meaning_pillars)

        eudaimonic_wellbeing = needs_avg * 0.4 + meaning_avg * 0.6

        if eudaimonic_wellbeing > 0.7:
            existential_state = 'flourishing'
        elif eudaimonic_wellbeing > 0.5:
            existential_state = 'functioning'
        elif eudaimonic_wellbeing > 0.3:
            existential_state = 'struggling'
        else:
            existential_state = 'crisis'

        unfulfilled = [n for n, v in self._basic_needs.items() if v < 0.3]

        return {
            'basic_needs': {k: round(v, 4) for k, v in self._basic_needs.items()},
            'meaning_pillars': {k: round(v, 4) for k, v in self._meaning_pillars.items()},
            'eudaimonic_wellbeing': round(eudaimonic_wellbeing, 4),
            'life_satisfaction': round(self._life_satisfaction, 4),
            'existential_state': existential_state,
            'unfulfilled_needs': unfulfilled
        }

    def _update_life_satisfaction(self) -> None:
        """Compute overall life satisfaction from needs + meaning."""
        needs = sum(self._basic_needs.values()) / len(self._basic_needs)
        meaning = sum(self._meaning_pillars.values()) / len(self._meaning_pillars)
        self._life_satisfaction = (0.9 * self._life_satisfaction +
                                  0.1 * (needs * 0.4 + meaning * 0.6))

    def get_state(self) -> Dict[str, Any]:
        return self.get_existential_status()
