"""
Proactive Behavior System (V2 Phase 3: P3.41-43)

Three systems that give Tahlamus autonomous proactive behavior:

1. ProactiveTaskGenerator (P3.41):
   Generates tasks WITHOUT user input based on:
   - error_signal high + LogSensor errors → "Automatically analyze logs"
   - Coding_Engine job FAILED → "Diagnose error and suggest fix"
   - ServiceHealthSensor degradation → "Investigate root cause"
   Combines reactive patterns with KuroGraph-style pattern matching.

2. ScheduledActions (P3.42):
   Intelligent scheduler (not just cron):
   - Memory consolidation: every 4h (adjustable based on sleep_pressure)
   - System health check: every 15min
   - Git activity scan: every 5min (more often during active development)
   - Dream mode: overnight (22-06) or after IDLE > 30min
   Adapts intervals based on system load and experience.

3. ReactivePatterns (P3.43):
   Event-Condition-Action rules, learnable from user patterns:
   - IF error_signal > 0.8 AND process_down THEN analyze_logs AND notify_user
   - IF coding_job_completed AND test_coverage < 80% THEN suggest_more_tests
   - IF idle_time > 10min THEN run_curiosity_task
   New rules can be derived from observed user behavior patterns.

Integration with AgentLoop:
    The AgentLoop calls `ProactiveBehavior.tick()` each cycle.
    Returned ProactiveTask objects are converted to AgentTasks
    and submitted to the task queue.
"""

import logging
import time
import re
import math
import hashlib
from typing import Dict, List, Optional, Any, Tuple, Callable, Set
from dataclasses import dataclass, field
from enum import Enum
from collections import deque
from datetime import datetime

logger = logging.getLogger('brain.proactive')


# ─── Task Types & Data Structures ─────────────────────────────────────────

class ProactiveSource(Enum):
    """Source of a proactive task."""
    ERROR_SIGNAL = "error_signal"           # From error detection
    JOB_FAILURE = "job_failure"             # From job/task failure
    HEALTH_DEGRADATION = "health_degradation"  # From health monitoring
    SCHEDULED = "scheduled"                 # From scheduled actions
    REACTIVE_RULE = "reactive_rule"         # From ECA rules
    PATTERN = "pattern"                     # From observed patterns


class ScheduleType(Enum):
    """Types of scheduled actions."""
    MEMORY_CONSOLIDATION = "memory_consolidation"
    HEALTH_CHECK = "health_check"
    GIT_SCAN = "git_scan"
    DREAM_MODE = "dream_mode"
    CLEANUP = "cleanup"
    METRICS_SNAPSHOT = "metrics_snapshot"
    CUSTOM = "custom"


@dataclass
class ProactiveTask:
    """A task generated by the proactive behavior system."""
    task_id: str
    description: str
    source: ProactiveSource
    urgency: float = 0.5       # 0-1
    importance: float = 0.5    # 0-1
    domain: str = "general"
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            'task_id': self.task_id,
            'description': self.description,
            'source': self.source.value,
            'urgency': round(self.urgency, 3),
            'importance': round(self.importance, 3),
            'domain': self.domain,
            'metadata': self.metadata,
        }


# ─── Proactive Task Generator (P3.41) ──────────────────────────────────────

class ProactiveTaskGenerator:
    """
    Generates tasks WITHOUT user input from system signals.

    Monitors:
    - Error signals: High error rates → generate log analysis tasks
    - Job failures: Repeated failures → generate diagnostic tasks
    - Health degradation: Service health drops → generate investigation tasks

    Each generator has cooldowns and rate limits to prevent flooding.
    """

    def __init__(
        self,
        error_threshold: float = 0.7,
        failure_window_seconds: float = 300.0,
        failure_count_threshold: int = 2,
        health_degradation_threshold: float = 0.5,
        cooldown_seconds: float = 120.0,
        max_tasks_per_tick: int = 3,
    ):
        """
        Args:
            error_threshold: Error signal above this → generate task
            failure_window_seconds: Window for counting job failures
            failure_count_threshold: Failures within window → generate diagnostic task
            health_degradation_threshold: Health below this → generate investigation task
            cooldown_seconds: Min time between same-type task generation
            max_tasks_per_tick: Max proactive tasks per tick
        """
        self.error_threshold = error_threshold
        self.failure_window = failure_window_seconds
        self.failure_count_threshold = failure_count_threshold
        self.health_degradation_threshold = health_degradation_threshold
        self.cooldown_seconds = cooldown_seconds
        self.max_tasks_per_tick = max_tasks_per_tick

        # Tracking state
        self._task_counter: int = 0
        self._recent_errors: deque = deque(maxlen=200)
        self._recent_failures: deque = deque(maxlen=100)
        self._health_history: deque = deque(maxlen=50)
        self._cooldowns: Dict[str, float] = {}

        # Statistics
        self._total_tasks_generated: int = 0
        self._tasks_by_source: Dict[str, int] = {}

    def observe_error(self, error_signal: float, source: str = 'unknown',
                      details: str = ''):
        """Record an error observation."""
        self._recent_errors.append({
            'signal': error_signal,
            'source': source,
            'details': details[:200],
            'time': time.time(),
        })

    def observe_job_failure(self, job_name: str, error_message: str = '',
                            domain: str = 'general'):
        """Record a job/task failure."""
        self._recent_failures.append({
            'job': job_name,
            'error': error_message[:200],
            'domain': domain,
            'time': time.time(),
        })

    def observe_health(self, subsystem: str, health_score: float,
                       details: str = ''):
        """Record a health observation."""
        self._health_history.append({
            'subsystem': subsystem,
            'health': health_score,
            'details': details[:200],
            'time': time.time(),
        })

    def generate_tasks(self) -> List[ProactiveTask]:
        """
        Generate proactive tasks from accumulated observations.

        Returns list of ProactiveTask objects (max `max_tasks_per_tick`).
        """
        tasks = []
        now = time.time()

        # ── 1. Error Signal Tasks ──
        error_tasks = self._generate_error_tasks(now)
        tasks.extend(error_tasks)

        # ── 2. Job Failure Tasks ──
        failure_tasks = self._generate_failure_tasks(now)
        tasks.extend(failure_tasks)

        # ── 3. Health Degradation Tasks ──
        health_tasks = self._generate_health_tasks(now)
        tasks.extend(health_tasks)

        # Sort by urgency and limit
        tasks.sort(key=lambda t: -t.urgency)
        result = tasks[:self.max_tasks_per_tick]

        self._total_tasks_generated += len(result)
        for t in result:
            src = t.source.value
            self._tasks_by_source[src] = self._tasks_by_source.get(src, 0) + 1

        return result

    def _generate_error_tasks(self, now: float) -> List[ProactiveTask]:
        """Generate tasks from high error signals."""
        if not self._check_cooldown('error', now):
            return []

        # Aggregate recent errors (last 60 seconds)
        recent = [e for e in self._recent_errors if now - e['time'] < 60]
        if not recent:
            return []

        # Check if average error signal is above threshold
        avg_signal = sum(e['signal'] for e in recent) / len(recent)
        if avg_signal < self.error_threshold:
            return []

        # Find the most common error source
        sources = {}
        for e in recent:
            s = e['source']
            sources[s] = sources.get(s, 0) + 1
        top_source = max(sources, key=sources.get)

        self._record_cooldown('error', now)

        return [self._make_task(
            description=f"Analyze error signals from '{top_source}' "
                        f"(avg signal: {avg_signal:.2f}, count: {len(recent)})",
            source=ProactiveSource.ERROR_SIGNAL,
            urgency=min(0.95, avg_signal),
            importance=0.7,
            domain=top_source,
            metadata={
                'avg_error_signal': round(avg_signal, 3),
                'error_count': len(recent),
                'top_source': top_source,
            },
        )]

    def _generate_failure_tasks(self, now: float) -> List[ProactiveTask]:
        """Generate tasks from repeated job failures."""
        if not self._check_cooldown('failure', now):
            return []

        # Count failures within window
        cutoff = now - self.failure_window
        recent = [f for f in self._recent_failures if f['time'] > cutoff]
        if len(recent) < self.failure_count_threshold:
            return []

        # Group by job name
        job_counts = {}
        for f in recent:
            job = f['job']
            job_counts[job] = job_counts.get(job, 0) + 1

        tasks = []
        for job, count in job_counts.items():
            if count >= self.failure_count_threshold:
                last_failure = next(
                    (f for f in reversed(list(self._recent_failures)) if f['job'] == job),
                    {}
                )
                urgency = min(0.9, 0.5 + count * 0.1)

                tasks.append(self._make_task(
                    description=f"Diagnose repeated failure in '{job}' "
                                f"({count} failures in {self.failure_window/60:.0f}min)",
                    source=ProactiveSource.JOB_FAILURE,
                    urgency=urgency,
                    importance=0.8,
                    domain=last_failure.get('domain', 'general'),
                    metadata={
                        'job_name': job,
                        'failure_count': count,
                        'last_error': last_failure.get('error', ''),
                        'window_seconds': self.failure_window,
                    },
                ))

        if tasks:
            self._record_cooldown('failure', now)

        return tasks

    def _generate_health_tasks(self, now: float) -> List[ProactiveTask]:
        """Generate tasks from health degradation."""
        if not self._check_cooldown('health', now):
            return []

        # Check recent health observations (last 5 minutes)
        recent = [h for h in self._health_history if now - h['time'] < 300]
        if not recent:
            return []

        tasks = []
        # Group by subsystem, find degraded ones
        subsystems = {}
        for h in recent:
            sub = h['subsystem']
            if sub not in subsystems:
                subsystems[sub] = []
            subsystems[sub].append(h['health'])

        for sub, scores in subsystems.items():
            avg_health = sum(scores) / len(scores)
            if avg_health < self.health_degradation_threshold:
                urgency = min(0.9, 1.0 - avg_health)
                tasks.append(self._make_task(
                    description=f"Investigate health degradation in '{sub}' "
                                f"(avg health: {avg_health:.2f})",
                    source=ProactiveSource.HEALTH_DEGRADATION,
                    urgency=urgency,
                    importance=0.75,
                    domain=sub,
                    metadata={
                        'subsystem': sub,
                        'avg_health': round(avg_health, 3),
                        'sample_count': len(scores),
                    },
                ))

        if tasks:
            self._record_cooldown('health', now)

        return tasks

    def _make_task(self, description: str, source: ProactiveSource,
                   urgency: float, importance: float,
                   domain: str = 'general',
                   metadata: Optional[Dict] = None) -> ProactiveTask:
        """Create a new proactive task with unique ID."""
        self._task_counter += 1
        return ProactiveTask(
            task_id=f"proactive_{self._task_counter}_{int(time.time())}",
            description=description,
            source=source,
            urgency=urgency,
            importance=importance,
            domain=domain,
            metadata=metadata or {},
        )

    def _check_cooldown(self, category: str, now: float) -> bool:
        """Check if cooldown has elapsed."""
        last = self._cooldowns.get(category, 0)
        return (now - last) >= self.cooldown_seconds

    def _record_cooldown(self, category: str, now: float):
        """Record cooldown timestamp."""
        self._cooldowns[category] = now

    def get_state(self) -> Dict[str, Any]:
        """Get generator state for dashboard."""
        return {
            'name': 'ProactiveTaskGenerator',
            'total_tasks_generated': self._total_tasks_generated,
            'tasks_by_source': dict(self._tasks_by_source),
            'pending_errors': len(self._recent_errors),
            'pending_failures': len(self._recent_failures),
            'health_observations': len(self._health_history),
            'config': {
                'error_threshold': self.error_threshold,
                'failure_count_threshold': self.failure_count_threshold,
                'health_degradation_threshold': self.health_degradation_threshold,
                'cooldown_seconds': self.cooldown_seconds,
                'max_tasks_per_tick': self.max_tasks_per_tick,
            },
        }


# ─── Scheduled Actions (P3.42) ──────────────────────────────────────────────

@dataclass
class ScheduledAction:
    """A scheduled action with adaptive interval."""
    name: str
    schedule_type: ScheduleType
    base_interval_seconds: float
    description: str
    urgency: float = 0.3
    importance: float = 0.4
    domain: str = "system"

    # Adaptive interval state
    last_run_time: float = 0.0
    current_interval: float = 0.0  # Will be set to base_interval
    min_interval_seconds: float = 30.0
    max_interval_seconds: float = 86400.0  # 24h max

    # Time-of-day restrictions (24h format, -1 = no restriction)
    active_start_hour: int = -1  # e.g., 22 for "only after 10pm"
    active_end_hour: int = -1    # e.g., 6 for "until 6am"

    # Execution tracking
    total_runs: int = 0
    total_skipped: int = 0

    def __post_init__(self):
        if self.current_interval == 0.0:
            self.current_interval = self.base_interval_seconds

    def is_due(self, now: float) -> bool:
        """Check if this action is due to run."""
        # Check time-of-day restriction
        if self.active_start_hour >= 0 and self.active_end_hour >= 0:
            current_hour = datetime.now().hour
            if self.active_start_hour > self.active_end_hour:
                # Overnight window (e.g., 22-06)
                if not (current_hour >= self.active_start_hour or
                        current_hour < self.active_end_hour):
                    return False
            else:
                # Daytime window
                if not (self.active_start_hour <= current_hour < self.active_end_hour):
                    return False

        elapsed = now - self.last_run_time
        return elapsed >= self.current_interval

    def mark_run(self, now: float):
        """Mark this action as having been executed."""
        self.last_run_time = now
        self.total_runs += 1

    def adapt_interval(self, factor: float):
        """
        Adapt the interval by a multiplicative factor.
        factor < 1.0 → run more often
        factor > 1.0 → run less often
        """
        self.current_interval = max(
            self.min_interval_seconds,
            min(self.max_interval_seconds, self.current_interval * factor)
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            'name': self.name,
            'type': self.schedule_type.value,
            'description': self.description,
            'base_interval_seconds': self.base_interval_seconds,
            'current_interval_seconds': round(self.current_interval, 1),
            'last_run_time': self.last_run_time,
            'time_until_next': round(
                max(0, self.current_interval - (time.time() - self.last_run_time)), 1
            ),
            'total_runs': self.total_runs,
            'active_hours': (
                f"{self.active_start_hour}:00-{self.active_end_hour}:00"
                if self.active_start_hour >= 0 else "always"
            ),
        }


class ScheduledActionManager:
    """
    Intelligent scheduler with adaptive intervals.

    Unlike simple cron: intervals adapt based on system load, sleep pressure,
    and recent activity. More frequent during active periods, less during
    idle/recovery.
    """

    def __init__(
        self,
        memory_consolidation_interval: float = 14400.0,  # 4h
        health_check_interval: float = 900.0,             # 15min
        git_scan_interval: float = 300.0,                  # 5min
        dream_idle_threshold: float = 1800.0,              # 30min
        cleanup_interval: float = 3600.0,                  # 1h
        metrics_snapshot_interval: float = 600.0,          # 10min
    ):
        # Create default scheduled actions
        now = time.time()
        self._actions: Dict[str, ScheduledAction] = {}

        self._add_default_actions(
            memory_consolidation_interval,
            health_check_interval,
            git_scan_interval,
            dream_idle_threshold,
            cleanup_interval,
            metrics_snapshot_interval,
            now,
        )

        # Adaptation state
        self._system_load: float = 0.5  # 0=idle, 1=maxed out
        self._recent_activity: float = 0.5  # 0=no activity, 1=very active

        # Statistics
        self._total_scheduled_tasks: int = 0

    def _add_default_actions(
        self,
        memory_consolidation_interval: float,
        health_check_interval: float,
        git_scan_interval: float,
        dream_idle_threshold: float,
        cleanup_interval: float,
        metrics_snapshot_interval: float,
        now: float,
    ):
        """Set up the default scheduled actions."""
        defaults = [
            ScheduledAction(
                name="memory_consolidation",
                schedule_type=ScheduleType.MEMORY_CONSOLIDATION,
                base_interval_seconds=memory_consolidation_interval,
                description="Consolidate working memory into long-term storage",
                urgency=0.3,
                importance=0.6,
                domain="memory",
                last_run_time=now,
                min_interval_seconds=1800.0,     # Min 30min
                max_interval_seconds=28800.0,    # Max 8h
            ),
            ScheduledAction(
                name="health_check",
                schedule_type=ScheduleType.HEALTH_CHECK,
                base_interval_seconds=health_check_interval,
                description="Run system health diagnostics on all subsystems",
                urgency=0.4,
                importance=0.5,
                domain="system",
                last_run_time=now,
                min_interval_seconds=60.0,       # Min 1min
                max_interval_seconds=3600.0,     # Max 1h
            ),
            ScheduledAction(
                name="git_scan",
                schedule_type=ScheduleType.GIT_SCAN,
                base_interval_seconds=git_scan_interval,
                description="Scan git repositories for activity and changes",
                urgency=0.2,
                importance=0.3,
                domain="git",
                last_run_time=now,
                min_interval_seconds=60.0,       # Min 1min
                max_interval_seconds=1800.0,     # Max 30min
            ),
            ScheduledAction(
                name="dream_mode",
                schedule_type=ScheduleType.DREAM_MODE,
                base_interval_seconds=dream_idle_threshold,
                description="Enter dream mode for CTM training and consolidation",
                urgency=0.2,
                importance=0.4,
                domain="dream",
                last_run_time=now,
                min_interval_seconds=600.0,      # Min 10min
                max_interval_seconds=7200.0,     # Max 2h
                active_start_hour=22,
                active_end_hour=6,
            ),
            ScheduledAction(
                name="cleanup",
                schedule_type=ScheduleType.CLEANUP,
                base_interval_seconds=cleanup_interval,
                description="Clean up old logs, temp files, and expired caches",
                urgency=0.1,
                importance=0.2,
                domain="system",
                last_run_time=now,
                min_interval_seconds=600.0,      # Min 10min
                max_interval_seconds=14400.0,    # Max 4h
            ),
            ScheduledAction(
                name="metrics_snapshot",
                schedule_type=ScheduleType.METRICS_SNAPSHOT,
                base_interval_seconds=metrics_snapshot_interval,
                description="Capture metrics snapshot for trend analysis",
                urgency=0.2,
                importance=0.3,
                domain="metrics",
                last_run_time=now,
                min_interval_seconds=60.0,       # Min 1min
                max_interval_seconds=3600.0,     # Max 1h
            ),
        ]

        for action in defaults:
            self._actions[action.name] = action

    def add_action(self, action: ScheduledAction):
        """Add a custom scheduled action."""
        self._actions[action.name] = action

    def remove_action(self, name: str) -> bool:
        """Remove a scheduled action by name."""
        if name in self._actions:
            del self._actions[name]
            return True
        return False

    def update_system_context(
        self,
        system_load: Optional[float] = None,
        activity_level: Optional[float] = None,
        sleep_pressure: Optional[float] = None,
    ):
        """
        Update system context for interval adaptation.

        Args:
            system_load: 0-1, current CPU/memory load
            activity_level: 0-1, how active is the system
            sleep_pressure: 0-1, from homeostatic regulation
        """
        if system_load is not None:
            self._system_load = max(0.0, min(1.0, system_load))
        if activity_level is not None:
            self._recent_activity = max(0.0, min(1.0, activity_level))

        # Adapt intervals based on context
        for name, action in self._actions.items():
            factor = 1.0

            # High load → slow down non-critical actions
            if self._system_load > 0.8:
                if action.urgency < 0.5:
                    factor *= 1.5  # 50% slower for low-urgency

            # High activity → speed up monitoring
            if self._recent_activity > 0.7:
                if action.schedule_type in (
                    ScheduleType.HEALTH_CHECK,
                    ScheduleType.GIT_SCAN,
                    ScheduleType.METRICS_SNAPSHOT,
                ):
                    factor *= 0.7  # 30% faster

            # High sleep pressure → speed up consolidation
            if sleep_pressure is not None and sleep_pressure > 0.6:
                if action.schedule_type == ScheduleType.MEMORY_CONSOLIDATION:
                    factor *= 0.5  # 2x faster

            if factor != 1.0:
                action.adapt_interval(factor)

    def get_due_actions(self) -> List[ProactiveTask]:
        """
        Get all scheduled actions that are due.

        Returns ProactiveTask objects for due actions.
        """
        now = time.time()
        tasks = []

        for name, action in self._actions.items():
            if action.is_due(now):
                task = ProactiveTask(
                    task_id=f"scheduled_{name}_{int(now)}",
                    description=action.description,
                    source=ProactiveSource.SCHEDULED,
                    urgency=action.urgency,
                    importance=action.importance,
                    domain=action.domain,
                    metadata={
                        'schedule_name': name,
                        'schedule_type': action.schedule_type.value,
                        'interval_seconds': round(action.current_interval, 1),
                        'run_number': action.total_runs + 1,
                    },
                )
                tasks.append(task)
                action.mark_run(now)
                self._total_scheduled_tasks += 1

        return tasks

    def get_state(self) -> Dict[str, Any]:
        """Get scheduler state for dashboard."""
        return {
            'name': 'ScheduledActionManager',
            'total_scheduled_tasks': self._total_scheduled_tasks,
            'system_load': round(self._system_load, 3),
            'activity_level': round(self._recent_activity, 3),
            'actions': {
                name: action.to_dict()
                for name, action in self._actions.items()
            },
        }


# ─── Reactive Patterns (P3.43) ──────────────────────────────────────────────

class ConditionOperator(Enum):
    """Operators for reactive pattern conditions."""
    GT = ">"
    GTE = ">="
    LT = "<"
    LTE = "<="
    EQ = "=="
    NEQ = "!="
    CONTAINS = "contains"
    EXISTS = "exists"


@dataclass
class Condition:
    """A single condition in a reactive pattern."""
    field: str                          # e.g., 'error_signal', 'idle_time'
    operator: ConditionOperator
    threshold: Any = None               # Value to compare against
    description: str = ""

    def evaluate(self, context: Dict[str, Any]) -> bool:
        """Evaluate this condition against a context dict."""
        value = self._resolve_field(context)
        if value is None:
            return self.operator == ConditionOperator.EXISTS and self.threshold is False

        if self.operator == ConditionOperator.EXISTS:
            return (value is not None) == bool(self.threshold)
        if self.operator == ConditionOperator.CONTAINS:
            return str(self.threshold) in str(value)

        try:
            num_val = float(value)
            num_thresh = float(self.threshold)
        except (TypeError, ValueError):
            # String comparison fallback
            if self.operator == ConditionOperator.EQ:
                return str(value) == str(self.threshold)
            if self.operator == ConditionOperator.NEQ:
                return str(value) != str(self.threshold)
            return False

        if self.operator == ConditionOperator.GT:
            return num_val > num_thresh
        elif self.operator == ConditionOperator.GTE:
            return num_val >= num_thresh
        elif self.operator == ConditionOperator.LT:
            return num_val < num_thresh
        elif self.operator == ConditionOperator.LTE:
            return num_val <= num_thresh
        elif self.operator == ConditionOperator.EQ:
            return abs(num_val - num_thresh) < 1e-9
        elif self.operator == ConditionOperator.NEQ:
            return abs(num_val - num_thresh) >= 1e-9
        return False

    def _resolve_field(self, context: Dict[str, Any]) -> Any:
        """Resolve a dotted field path in context dict."""
        parts = self.field.split('.')
        current = context
        for part in parts:
            if isinstance(current, dict):
                current = current.get(part)
            elif hasattr(current, part):
                current = getattr(current, part)
            else:
                return None
            if current is None:
                return None
        return current

    def to_dict(self) -> Dict[str, Any]:
        return {
            'field': self.field,
            'operator': self.operator.value,
            'threshold': self.threshold,
            'description': self.description,
        }


@dataclass
class ReactiveAction:
    """An action to take when a reactive pattern fires."""
    action_type: str           # e.g., 'generate_task', 'notify', 'adjust_param'
    description: str           # Human-readable description of what to do
    parameters: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            'action_type': self.action_type,
            'description': self.description,
            'parameters': self.parameters,
        }


@dataclass
class ReactivePattern:
    """
    An Event-Condition-Action (ECA) rule.

    When ALL conditions are met, the actions are triggered.
    Patterns can be predefined or learned from user behavior.
    """
    pattern_id: str
    name: str
    conditions: List[Condition]
    actions: List[ReactiveAction]
    enabled: bool = True
    cooldown_seconds: float = 60.0
    priority: float = 0.5         # 0-1, higher = more important
    learned: bool = False          # True if derived from user patterns
    confidence: float = 1.0        # For learned patterns

    # Execution tracking
    last_fired_time: float = 0.0
    total_fires: int = 0
    total_suppressed: int = 0      # Times conditions met but cooldown active

    def evaluate(self, context: Dict[str, Any]) -> bool:
        """Check if all conditions are met."""
        if not self.enabled:
            return False
        return all(c.evaluate(context) for c in self.conditions)

    def is_on_cooldown(self, now: float) -> bool:
        """Check if pattern is on cooldown."""
        return (now - self.last_fired_time) < self.cooldown_seconds

    def fire(self, now: float):
        """Record a pattern firing."""
        self.last_fired_time = now
        self.total_fires += 1

    def to_dict(self) -> Dict[str, Any]:
        return {
            'pattern_id': self.pattern_id,
            'name': self.name,
            'conditions': [c.to_dict() for c in self.conditions],
            'actions': [a.to_dict() for a in self.actions],
            'enabled': self.enabled,
            'cooldown_seconds': self.cooldown_seconds,
            'priority': self.priority,
            'learned': self.learned,
            'confidence': round(self.confidence, 3),
            'total_fires': self.total_fires,
            'total_suppressed': self.total_suppressed,
            'last_fired_time': self.last_fired_time,
        }


class ReactivePatternEngine:
    """
    Event-Condition-Action rule engine.

    Manages a set of reactive patterns and evaluates them against
    the current system context. Supports both predefined and learned patterns.
    """

    def __init__(
        self,
        max_patterns: int = 100,
        max_fires_per_tick: int = 5,
        learning_enabled: bool = True,
    ):
        """
        Args:
            max_patterns: Maximum number of patterns to maintain
            max_fires_per_tick: Max patterns that can fire per tick
            learning_enabled: Whether to learn new patterns from behavior
        """
        self.max_patterns = max_patterns
        self.max_fires_per_tick = max_fires_per_tick
        self.learning_enabled = learning_enabled

        self._patterns: Dict[str, ReactivePattern] = {}
        self._observation_buffer: deque = deque(maxlen=500)
        self._pattern_counter: int = 0

        # Statistics
        self._total_evaluations: int = 0
        self._total_fires: int = 0
        self._total_learned: int = 0

        # Set up default patterns
        self._setup_default_patterns()

    def _setup_default_patterns(self):
        """Set up built-in reactive patterns from the V2 plan."""
        defaults = [
            ReactivePattern(
                pattern_id="rp_error_high",
                name="High Error Signal → Analyze Logs",
                conditions=[
                    Condition(
                        field='error_signal',
                        operator=ConditionOperator.GT,
                        threshold=0.8,
                        description="Error signal above 0.8",
                    ),
                ],
                actions=[
                    ReactiveAction(
                        action_type='generate_task',
                        description="Analyze logs for root cause of high error signals",
                        parameters={
                            'urgency': 0.8,
                            'importance': 0.7,
                            'domain': 'logs',
                        },
                    ),
                ],
                cooldown_seconds=120.0,
                priority=0.8,
            ),
            ReactivePattern(
                pattern_id="rp_process_down",
                name="Process Down → Investigate",
                conditions=[
                    Condition(
                        field='process_down',
                        operator=ConditionOperator.EQ,
                        threshold=True,
                        description="A process is down",
                    ),
                ],
                actions=[
                    ReactiveAction(
                        action_type='generate_task',
                        description="Investigate and attempt to restart downed process",
                        parameters={
                            'urgency': 0.9,
                            'importance': 0.85,
                            'domain': 'system',
                        },
                    ),
                ],
                cooldown_seconds=60.0,
                priority=0.9,
            ),
            ReactivePattern(
                pattern_id="rp_low_test_coverage",
                name="Job Complete + Low Coverage → Suggest Tests",
                conditions=[
                    Condition(
                        field='coding_job_completed',
                        operator=ConditionOperator.EQ,
                        threshold=True,
                        description="A coding job just completed",
                    ),
                    Condition(
                        field='test_coverage',
                        operator=ConditionOperator.LT,
                        threshold=80.0,
                        description="Test coverage below 80%",
                    ),
                ],
                actions=[
                    ReactiveAction(
                        action_type='generate_task',
                        description="Suggest additional tests to improve coverage",
                        parameters={
                            'urgency': 0.4,
                            'importance': 0.6,
                            'domain': 'testing',
                        },
                    ),
                ],
                cooldown_seconds=300.0,
                priority=0.5,
            ),
            ReactivePattern(
                pattern_id="rp_idle_curiosity",
                name="Long Idle → Run Curiosity Task",
                conditions=[
                    Condition(
                        field='idle_time',
                        operator=ConditionOperator.GT,
                        threshold=600.0,  # 10 minutes
                        description="System idle for over 10 minutes",
                    ),
                ],
                actions=[
                    ReactiveAction(
                        action_type='generate_task',
                        description="Run a curiosity-driven exploration task during idle time",
                        parameters={
                            'urgency': 0.2,
                            'importance': 0.3,
                            'domain': 'curiosity',
                        },
                    ),
                ],
                cooldown_seconds=600.0,
                priority=0.3,
            ),
            ReactivePattern(
                pattern_id="rp_memory_pressure",
                name="High Memory Usage → Consolidate",
                conditions=[
                    Condition(
                        field='memory_usage',
                        operator=ConditionOperator.GT,
                        threshold=0.85,
                        description="Memory usage above 85%",
                    ),
                ],
                actions=[
                    ReactiveAction(
                        action_type='generate_task',
                        description="Consolidate and clean up memory to reduce pressure",
                        parameters={
                            'urgency': 0.6,
                            'importance': 0.5,
                            'domain': 'memory',
                        },
                    ),
                ],
                cooldown_seconds=300.0,
                priority=0.6,
            ),
            ReactivePattern(
                pattern_id="rp_high_prediction_error",
                name="High PE → Deep Investigation",
                conditions=[
                    Condition(
                        field='prediction_error',
                        operator=ConditionOperator.GT,
                        threshold=0.7,
                        description="Prediction error above 0.7",
                    ),
                ],
                actions=[
                    ReactiveAction(
                        action_type='generate_task',
                        description="Deep investigation of area with high prediction error",
                        parameters={
                            'urgency': 0.5,
                            'importance': 0.6,
                            'domain': 'investigation',
                        },
                    ),
                ],
                cooldown_seconds=180.0,
                priority=0.6,
            ),
        ]

        for pattern in defaults:
            self._patterns[pattern.pattern_id] = pattern

    def add_pattern(self, pattern: ReactivePattern) -> bool:
        """Add a reactive pattern. Returns False if at capacity."""
        if len(self._patterns) >= self.max_patterns:
            return False
        self._patterns[pattern.pattern_id] = pattern
        return True

    def remove_pattern(self, pattern_id: str) -> bool:
        """Remove a pattern by ID."""
        if pattern_id in self._patterns:
            del self._patterns[pattern_id]
            return True
        return False

    def enable_pattern(self, pattern_id: str, enabled: bool = True) -> bool:
        """Enable or disable a pattern."""
        if pattern_id in self._patterns:
            self._patterns[pattern_id].enabled = enabled
            return True
        return False

    def evaluate(self, context: Dict[str, Any]) -> List[ProactiveTask]:
        """
        Evaluate all patterns against the current context.

        Returns list of ProactiveTask objects from fired patterns.
        """
        self._total_evaluations += 1
        now = time.time()
        tasks = []

        # Sort patterns by priority (highest first)
        sorted_patterns = sorted(
            self._patterns.values(),
            key=lambda p: -p.priority,
        )

        for pattern in sorted_patterns:
            if not pattern.enabled:
                continue

            if pattern.evaluate(context):
                if pattern.is_on_cooldown(now):
                    pattern.total_suppressed += 1
                    continue

                # Pattern fires - generate tasks from its actions
                for action in pattern.actions:
                    if action.action_type == 'generate_task':
                        params = action.parameters
                        self._pattern_counter += 1
                        task = ProactiveTask(
                            task_id=f"reactive_{pattern.pattern_id}_{self._pattern_counter}",
                            description=action.description,
                            source=ProactiveSource.REACTIVE_RULE,
                            urgency=params.get('urgency', 0.5),
                            importance=params.get('importance', 0.5),
                            domain=params.get('domain', 'general'),
                            metadata={
                                'pattern_id': pattern.pattern_id,
                                'pattern_name': pattern.name,
                                'learned': pattern.learned,
                                'confidence': round(pattern.confidence, 3),
                            },
                        )
                        tasks.append(task)

                pattern.fire(now)
                self._total_fires += 1

                if len(tasks) >= self.max_fires_per_tick:
                    break

        # Record observation for learning
        if self.learning_enabled:
            self._observation_buffer.append({
                'context': {k: v for k, v in context.items()
                            if isinstance(v, (int, float, str, bool))},
                'fires': [t.metadata.get('pattern_id', '') for t in tasks],
                'time': now,
            })

        return tasks

    def learn_pattern_from_observation(
        self,
        name: str,
        conditions: List[Condition],
        actions: List[ReactiveAction],
        confidence: float = 0.5,
        cooldown_seconds: float = 120.0,
    ) -> Optional[str]:
        """
        Create a learned pattern from observed user behavior.

        Returns the pattern_id if created, None if at capacity.
        """
        if not self.learning_enabled:
            return None
        if len(self._patterns) >= self.max_patterns:
            return None

        self._pattern_counter += 1
        pattern_id = f"learned_{self._pattern_counter}"

        pattern = ReactivePattern(
            pattern_id=pattern_id,
            name=name,
            conditions=conditions,
            actions=actions,
            enabled=True,
            cooldown_seconds=cooldown_seconds,
            priority=confidence * 0.5,  # Learned patterns start at lower priority
            learned=True,
            confidence=confidence,
        )

        self._patterns[pattern_id] = pattern
        self._total_learned += 1
        return pattern_id

    def get_state(self) -> Dict[str, Any]:
        """Get engine state for dashboard."""
        predefined = sum(1 for p in self._patterns.values() if not p.learned)
        learned = sum(1 for p in self._patterns.values() if p.learned)
        enabled = sum(1 for p in self._patterns.values() if p.enabled)

        return {
            'name': 'ReactivePatternEngine',
            'total_patterns': len(self._patterns),
            'predefined_patterns': predefined,
            'learned_patterns': learned,
            'enabled_patterns': enabled,
            'total_evaluations': self._total_evaluations,
            'total_fires': self._total_fires,
            'total_learned': self._total_learned,
            'learning_enabled': self.learning_enabled,
            'patterns': {
                pid: p.to_dict() for pid, p in self._patterns.items()
            },
        }


# ─── Proactive Behavior System (combines P3.41-43) ───────────────────────────

class ProactiveBehavior:
    """
    Combines all three proactive behavior systems into a unified interface.

    The AgentLoop calls `tick()` to get proactive tasks from all sources.
    Tasks are then converted to AgentTasks and submitted to the queue.
    """

    def __init__(
        self,
        task_generator: Optional[ProactiveTaskGenerator] = None,
        scheduler: Optional[ScheduledActionManager] = None,
        pattern_engine: Optional[ReactivePatternEngine] = None,
        max_tasks_per_tick: int = 5,
    ):
        self.generator = task_generator or ProactiveTaskGenerator()
        self.scheduler = scheduler or ScheduledActionManager()
        self.patterns = pattern_engine or ReactivePatternEngine()
        self.max_tasks_per_tick = max_tasks_per_tick

        self._total_tasks_generated: int = 0
        self._tasks_by_source: Dict[str, int] = {}

    def tick(
        self,
        context: Optional[Dict[str, Any]] = None,
        system_load: Optional[float] = None,
        activity_level: Optional[float] = None,
        sleep_pressure: Optional[float] = None,
    ) -> List[ProactiveTask]:
        """
        Main tick method. Collects tasks from all proactive systems.

        Args:
            context: Current system context dict for reactive pattern evaluation
            system_load: 0-1, for scheduler adaptation
            activity_level: 0-1, for scheduler adaptation
            sleep_pressure: 0-1, for scheduler adaptation

        Returns:
            List of ProactiveTask objects, sorted by urgency
        """
        all_tasks = []

        # ── 1. Proactive Task Generator (from errors, failures, health) ──
        try:
            gen_tasks = self.generator.generate_tasks()
            all_tasks.extend(gen_tasks)
        except Exception as e:
            logger.warning(f"ProactiveTaskGenerator error: {e}")

        # ── 2. Scheduled Actions (time-based) ──
        try:
            # Update scheduler context for adaptive intervals
            self.scheduler.update_system_context(
                system_load=system_load,
                activity_level=activity_level,
                sleep_pressure=sleep_pressure,
            )
            sched_tasks = self.scheduler.get_due_actions()
            all_tasks.extend(sched_tasks)
        except Exception as e:
            logger.warning(f"ScheduledActionManager error: {e}")

        # ── 3. Reactive Patterns (event-condition-action) ──
        if context:
            try:
                reactive_tasks = self.patterns.evaluate(context)
                all_tasks.extend(reactive_tasks)
            except Exception as e:
                logger.warning(f"ReactivePatternEngine error: {e}")

        # Sort by urgency and limit
        all_tasks.sort(key=lambda t: -t.urgency)
        result = all_tasks[:self.max_tasks_per_tick]

        # Statistics
        self._total_tasks_generated += len(result)
        for t in result:
            src = t.source.value
            self._tasks_by_source[src] = self._tasks_by_source.get(src, 0) + 1

        return result

    def observe_error(self, error_signal: float, source: str = 'unknown',
                      details: str = ''):
        """Forward error observation to the task generator."""
        self.generator.observe_error(error_signal, source, details)

    def observe_job_failure(self, job_name: str, error_message: str = '',
                            domain: str = 'general'):
        """Forward job failure observation to the task generator."""
        self.generator.observe_job_failure(job_name, error_message, domain)

    def observe_health(self, subsystem: str, health_score: float,
                       details: str = ''):
        """Forward health observation to the task generator."""
        self.generator.observe_health(subsystem, health_score, details)

    def get_state(self) -> Dict[str, Any]:
        """Get complete proactive behavior state for dashboard."""
        return {
            'total_tasks_generated': self._total_tasks_generated,
            'tasks_by_source': dict(self._tasks_by_source),
            'generator': self.generator.get_state(),
            'scheduler': self.scheduler.get_state(),
            'patterns': self.patterns.get_state(),
        }

    @classmethod
    def from_yaml(cls, config: Dict) -> 'ProactiveBehavior':
        """Create ProactiveBehavior from YAML config dict."""
        p = config.get('proactive_behavior', {})

        generator = ProactiveTaskGenerator(
            error_threshold=p.get('error_threshold', 0.7),
            failure_window_seconds=p.get('failure_window_seconds', 300.0),
            failure_count_threshold=p.get('failure_count_threshold', 2),
            health_degradation_threshold=p.get('health_degradation_threshold', 0.5),
            cooldown_seconds=p.get('generator_cooldown_seconds', 120.0),
            max_tasks_per_tick=p.get('generator_max_tasks_per_tick', 3),
        )

        scheduler = ScheduledActionManager(
            memory_consolidation_interval=p.get('memory_consolidation_interval', 14400.0),
            health_check_interval=p.get('health_check_interval', 900.0),
            git_scan_interval=p.get('git_scan_interval', 300.0),
            dream_idle_threshold=p.get('dream_idle_threshold', 1800.0),
            cleanup_interval=p.get('cleanup_interval', 3600.0),
            metrics_snapshot_interval=p.get('metrics_snapshot_interval', 600.0),
        )

        patterns = ReactivePatternEngine(
            max_patterns=p.get('max_patterns', 100),
            max_fires_per_tick=p.get('max_fires_per_tick', 5),
            learning_enabled=p.get('learning_enabled', True),
        )

        return cls(
            task_generator=generator,
            scheduler=scheduler,
            pattern_engine=patterns,
            max_tasks_per_tick=p.get('max_tasks_per_tick', 5),
        )
