"""Unit tests for the /api/unsubscribe one-click endpoint.

Mocks _db so the tests run without supabase. Verifies:
  * unknown email -> 'not on list'
  * already-unsubscribed -> idempotent
  * bad token -> reject (no UPDATE)
  * happy-path -> UPDATE + audit row
  * token generated by send-worker (_build_mail) matches API's expected token
"""
from __future__ import annotations

import sys
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PKG_ROOT))


from spaces.marketing.api import server as srv  # noqa: E402


_FAILS: list[str] = []


def _check(label: str, cond: bool, detail: str = ""):
    mark = "PASS" if cond else "FAIL"
    line = f"  [{mark}] {label}"
    if detail and not cond:
        line += f"  -- {detail}"
    print(line)
    if not cond:
        _FAILS.append(label)


class FakeDB:
    def __init__(self):
        self.queries: list[str] = []
        self.executes: list[str] = []
        self.row_response = None

    def query_one(self, sql, *a, **k):
        self.queries.append(sql)
        return self.row_response

    def query_via_docker(self, sql, *a, **k):
        self.queries.append(sql)
        return []

    def execute_via_docker(self, sql, *a, **k):
        self.executes.append(sql)
        return ""

    def _sql_literal(self, v):
        if v is None:
            return "NULL"
        if isinstance(v, (int, float)):
            return str(v)
        return "'" + str(v).replace("'", "''") + "'"


def _with_fake_db(test_fn):
    def wrapper():
        fake = FakeDB()
        with mock.patch("spaces.marketing.sync._db.query_one", fake.query_one), \
             mock.patch("spaces.marketing.sync._db.query_via_docker",
                        fake.query_via_docker), \
             mock.patch("spaces.marketing.sync._db.execute_via_docker",
                        fake.execute_via_docker), \
             mock.patch("spaces.marketing.sync._db._sql_literal", fake._sql_literal):
            test_fn(fake)
    wrapper.__name__ = test_fn.__name__
    return wrapper


import os as _os

# Tests run with a fixed test-secret that satisfies the >=32-char rule.
TEST_SECRET = "test-secret-" + "x" * 32          # 44 chars
_SECRET_PATCH = mock.patch.dict(
    _os.environ, {"MARKETING_UNSUB_SECRET": TEST_SECRET}, clear=False
)


def _good_token(email: str, msg: str) -> str:
    with _SECRET_PATCH:
        return srv._unsub_token(email, msg)


@_with_fake_db
def test_bad_token_rejected(fake):
    with _SECRET_PATCH:
        r = srv._do_unsubscribe("felix@vibemind.space", "abc",
                                "wrong-token-" + "a" * 50)
    no_update = not any("UPDATE marketing.emails" in s for s in fake.executes)
    _check("bad_token_rejected",
           r["success"] is False and "invalid" in r["message"] and no_update)


@_with_fake_db
def test_unknown_email_not_on_list(fake):
    fake.row_response = None  # query_one returns nothing
    msg = "abc"
    email = "ghost@vibemind.space"
    with _SECRET_PATCH:
        r = srv._do_unsubscribe(email, msg, _good_token(email, msg))
    no_update = not any("UPDATE marketing.emails" in s for s in fake.executes)
    _check("unknown_email_not_on_list",
           r["success"] is False and "not on list" in r["message"] and no_update)


@_with_fake_db
def test_already_unsubscribed_idempotent(fake):
    fake.row_response = {
        "email": "felix@vibemind.space",
        "unsubscribed_at": "2026-06-03T10:00:00+00:00",
    }
    msg = "abc"
    email = "felix@vibemind.space"
    with _SECRET_PATCH:
        r = srv._do_unsubscribe(email, msg, _good_token(email, msg))
    no_update = not any("UPDATE marketing.emails" in s for s in fake.executes)
    _check("already_unsubscribed_idempotent",
           r["success"] and r["message"] == "already_unsubscribed" and no_update)


@_with_fake_db
def test_happy_path_unsubscribes(fake):
    fake.row_response = {
        "email": "felix@vibemind.space", "unsubscribed_at": None,
    }
    msg = "abc"
    email = "felix@vibemind.space"
    with _SECRET_PATCH:
        r = srv._do_unsubscribe(email, msg, _good_token(email, msg))
    updated = any(
        "UPDATE marketing.emails SET unsubscribed_at = now()" in s
        for s in fake.executes
    )
    audit_present = any(
        "audit_log" in s and "unsubscribed" in s for s in fake.executes
    )
    _check("happy_path_unsubscribes",
           r["success"] and updated and audit_present,
           f"updated={updated} audit={audit_present}")


def test_token_matches_send_worker_format():
    """The send-worker _build_mail constructs the same token format
    that the API's _unsub_token expects. This guards against drift."""
    import os as __os
    import hmac as __hmac, hashlib as __hashlib
    with mock.patch.dict(__os.environ,
                         {"MARKETING_UNSUB_SECRET": TEST_SECRET}, clear=False):
        recipient = "felix@vibemind.space"
        msgid_core = "camp-1234-abcd5678efgh"
        # Recompute the send-worker formula independently.
        sender_token = __hmac.new(
            TEST_SECRET.encode("utf-8"),
            f"{recipient.lower()}|{msgid_core}".encode("utf-8"),
            __hashlib.sha256,
        ).hexdigest()
        api_token = srv._unsub_token(recipient, msgid_core)
    _check("token_matches_send_worker_format",
           sender_token == api_token,
           f"sender={sender_token[:16]}.. api={api_token[:16]}..")


@_with_fake_db
def test_missing_secret_refuses_verify(fake):
    """Empty / too-short MARKETING_UNSUB_SECRET => service misconfigured,
    NEVER accept the token. Guards against the original CVE."""
    # Ensure env is clean of the secret for this test
    with mock.patch.dict(_os.environ, {}, clear=False):
        _os.environ.pop("MARKETING_UNSUB_SECRET", None)
        r = srv._do_unsubscribe(
            "felix@vibemind.space", "abc",
            # An attacker's "forged token" that would match
            # sha256("felix@vibemind.space|abc|") if the old code path
            # were still active. We must refuse regardless.
            "a" * 64,
        )
    no_update = not any("UPDATE marketing.emails" in s for s in fake.executes)
    _check("missing_secret_refuses_verify",
           r["success"] is False
           and "misconfigured" in r["message"]
           and no_update,
           f"r={r!r} no_update={no_update}")


def main() -> int:
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

    tests = [
        test_bad_token_rejected,
        test_unknown_email_not_on_list,
        test_already_unsubscribed_idempotent,
        test_happy_path_unsubscribes,
        test_token_matches_send_worker_format,
        test_missing_secret_refuses_verify,
    ]
    print(f"[test_unsubscribe] running {len(tests)} tests")
    for t in tests:
        try:
            t()
        except Exception as e:
            _check(t.__name__, False, f"raised {type(e).__name__}: {e}")
    total = len(tests); fails = len(_FAILS)
    print(f"\n=== {total - fails}/{total} passed ===")
    if fails:
        for f in _FAILS: print(f"  - {f}")
        return 1
    print("test_unsubscribe: VERIFIED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
