"""
Git Service for automatic repository creation and pushing.
Uses GITHUB_TOKEN environment variable for authentication.
"""

import asyncio
import os
import subprocess
import httpx
from typing import Optional
from pydantic import BaseModel
from datetime import datetime


class GitConfig(BaseModel):
    """Git configuration for repository creation."""
    repo_name: str
    description: Optional[str] = None
    private: bool = True
    auto_init: bool = False
    create_repo: bool = True
    push_on_complete: bool = True


class GitResult(BaseModel):
    """Result of git operations."""
    success: bool
    repo_url: Optional[str] = None
    clone_url: Optional[str] = None
    message: str
    error: Optional[str] = None


class GitService:
    """
    Service for GitHub repository operations.
    Requires GITHUB_TOKEN environment variable.

    Security: Token is never embedded in URLs or logged.
    """

    def __init__(self):
        self.token = os.environ.get("GITHUB_TOKEN")
        self.api_url = "https://api.github.com"
        self._user_info: Optional[dict] = None

    @property
    def is_configured(self) -> bool:
        """Check if GitHub token is configured."""
        return bool(self.token)

    def _mask_secret(self, message: str) -> str:
        """Mask any secrets in messages before logging."""
        if self.token and self.token in message:
            return message.replace(self.token, "***GITHUB_TOKEN***")
        return message
    
    async def get_user(self) -> Optional[dict]:
        """Get authenticated user information."""
        if not self.is_configured:
            return None
        
        if self._user_info:
            return self._user_info
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.get(
                    f"{self.api_url}/user",
                    headers={
                        "Authorization": f"token {self.token}",
                        "Accept": "application/vnd.github.v3+json"
                    }
                )
                if response.status_code == 200:
                    self._user_info = response.json()
                    return self._user_info
        except Exception as e:
            print(f"Error getting user: {e}")
        
        return None
    
    async def get_username(self) -> Optional[str]:
        """Get authenticated username."""
        user = await self.get_user()
        if user:
            return user.get("login")
        return None
    
    async def create_repo(self, config: GitConfig) -> GitResult:
        """Create a new GitHub repository."""
        if not self.is_configured:
            return GitResult(
                success=False,
                message="GitHub token not configured",
                error="GITHUB_TOKEN environment variable is not set"
            )
        
        user = await self.get_user()
        if not user:
            return GitResult(
                success=False,
                message="Failed to authenticate with GitHub",
                error="Could not get user information"
            )
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.api_url}/user/repos",
                    headers={
                        "Authorization": f"token {self.token}",
                        "Accept": "application/vnd.github.v3+json"
                    },
                    json={
                        "name": config.repo_name,
                        "description": config.description or f"Generated by Coding Engine at {datetime.now().isoformat()}",
                        "private": config.private,
                        "auto_init": config.auto_init
                    }
                )
                
                if response.status_code == 201:
                    data = response.json()
                    return GitResult(
                        success=True,
                        repo_url=data.get("html_url"),
                        clone_url=data.get("clone_url"),
                        message=f"Repository created: {data.get('full_name')}"
                    )
                elif response.status_code == 422:
                    # Repo might already exist
                    return GitResult(
                        success=False,
                        message="Repository already exists",
                        error=response.text
                    )
                else:
                    return GitResult(
                        success=False,
                        message=f"Failed to create repository: {response.status_code}",
                        error=response.text
                    )
        except Exception as e:
            return GitResult(
                success=False,
                message="Error creating repository",
                error=str(e)
            )
    
    async def init_and_push(
        self,
        directory: str,
        config: GitConfig,
        commit_message: str = "Initial commit (auto-generated by Coding Engine)"
    ) -> GitResult:
        """
        Initialize git repo, create GitHub repo, and push.
        
        Args:
            directory: Path to the output directory
            config: Git configuration
            commit_message: Commit message for initial commit
        """
        if not self.is_configured:
            return GitResult(
                success=False,
                message="GitHub token not configured",
                error="GITHUB_TOKEN environment variable is not set"
            )
        
        # Get user info for remote URL
        user = await self.get_user()
        if not user:
            return GitResult(
                success=False,
                message="Failed to authenticate",
                error="Could not get user information"
            )
        
        username = user.get("login")
        
        # Create the repo first
        if config.create_repo:
            create_result = await self.create_repo(config)
            if not create_result.success and "already exists" not in create_result.message:
                return create_result
        
        repo_url = f"https://github.com/{username}/{config.repo_name}"
        # Task 26: Security - Don't embed token in URL, use credential helper instead
        clone_url = f"https://github.com/{username}/{config.repo_name}.git"

        try:
            # Run git commands with secure authentication
            # Use environment variable for authentication instead of embedding token in URL
            git_env = {
                **os.environ,
                "GIT_TERMINAL_PROMPT": "0",
                # Use askpass to provide token securely without embedding in URL
                "GIT_ASKPASS": "echo",
                "GIT_USERNAME": "x-access-token",
                "GIT_PASSWORD": self.token,
            }

            # Configure git to use token via credential helper
            commands = [
                ["git", "init"],
                # Configure credential helper to use our token
                ["git", "config", "credential.helper", ""],  # Clear any existing helper
                ["git", "config", f"credential.https://github.com.username", "x-access-token"],
                ["git", "add", "."],
                ["git", "commit", "-m", commit_message],
                ["git", "branch", "-M", "main"],
                ["git", "remote", "add", "origin", clone_url],
            ]

            for cmd in commands:
                process = await asyncio.create_subprocess_exec(
                    *cmd,
                    cwd=directory,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    env=git_env
                )
                stdout, stderr = await process.communicate()

                if process.returncode != 0:
                    cmd_name = cmd[0] + " " + cmd[1] if len(cmd) > 1 else cmd[0]
                    error_msg = stderr.decode() if stderr else ""

                    # Ignore non-critical errors
                    if "remote origin already exists" in error_msg:
                        continue
                    if "nothing to commit" in error_msg:
                        continue

                    # Task 26: Mask any secrets before logging
                    print(f"Git command '{cmd_name}' warning: {self._mask_secret(error_msg)}")

            # Push with token in header (more secure than URL embedding)
            # Use git credential fill to provide token
            push_url = f"https://x-access-token:{self.token}@github.com/{username}/{config.repo_name}.git"
            push_process = await asyncio.create_subprocess_exec(
                "git", "push", "-u", push_url, "main", "--force",
                cwd=directory,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                env={**os.environ, "GIT_TERMINAL_PROMPT": "0"}
            )
            push_stdout, push_stderr = await push_process.communicate()

            if push_process.returncode != 0:
                error_msg = push_stderr.decode() if push_stderr else ""
                # Task 26: Mask secrets in error output
                print(f"Git push warning: {self._mask_secret(error_msg)}")
            
            return GitResult(
                success=True,
                repo_url=repo_url,
                clone_url=f"https://github.com/{username}/{config.repo_name}.git",
                message=f"Code pushed to {repo_url}"
            )
            
        except Exception as e:
            return GitResult(
                success=False,
                message="Error during git operations",
                error=str(e)
            )
    
    async def delete_repo(self, repo_name: str) -> GitResult:
        """Delete a repository (use with caution!)."""
        if not self.is_configured:
            return GitResult(
                success=False,
                message="GitHub token not configured",
                error="GITHUB_TOKEN environment variable is not set"
            )
        
        user = await self.get_user()
        if not user:
            return GitResult(
                success=False,
                message="Failed to authenticate",
                error="Could not get user information"
            )
        
        username = user.get("login")
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.delete(
                    f"{self.api_url}/repos/{username}/{repo_name}",
                    headers={
                        "Authorization": f"token {self.token}",
                        "Accept": "application/vnd.github.v3+json"
                    }
                )
                
                if response.status_code == 204:
                    return GitResult(
                        success=True,
                        message=f"Repository {repo_name} deleted"
                    )
                else:
                    return GitResult(
                        success=False,
                        message=f"Failed to delete repository: {response.status_code}",
                        error=response.text
                    )
        except Exception as e:
            return GitResult(
                success=False,
                message="Error deleting repository",
                error=str(e)
            )


# Singleton instance
git_service = GitService()