-- ============================================================================
-- Canvas↔Rowboat sync (Phase A): change-tracking columns on public.canvas_nodes
-- ============================================================================
-- Mirror of 20260610_ideas_sync_columns.sql, for the canvas-node bidirectional
-- sync (Rowboat Knowledge-tab edits of canvas .md flow back to canvas_nodes).
--
--   updated_at       : bumped on every row UPDATE by a BEFORE-UPDATE trigger.
--                      The conflict key — Worker B compares it to the file's
--                      frontmatter last_synced_at to decide FS-edit vs DB-wins (LWW).
--   last_synced_at   : timestamp of the last successful DB->FS render (Worker A).
--                      NULL = never rendered.
--   reformat_pending : TRUE between a Worker-B content write and the reformat
--                      drainer regenerating content_json. While TRUE, Worker A
--                      renders from `content` (skips the lossy content_json
--                      flatten) so a forced re-render shows the user's edited
--                      text, not the stale structure — the anti-flicker contract.
--
-- canvas_nodes.id is already a stable UUID-as-text PK (init_vibemind.sql), reused
-- as the markdown frontmatter `canvas_node_id`. No second key, no backfill.
-- REPLICA IDENTITY FULL is already set (20260513_replica_identity_full.sql) —
-- DELETE payloads carry the old row.
--
-- Apply (PostgREST cannot run DDL — via docker-exec psql; MSYS_NO_PATHCONV=1 on
-- Git-Bash so the /tmp path is not mangled to a Windows path):
--   docker cp 20260611_canvas_sync_columns.sql <supabase-db>:/tmp/
--   MSYS_NO_PATHCONV=1 docker exec <supabase-db> psql -U supabase_admin -d postgres -f /tmp/20260611_canvas_sync_columns.sql

BEGIN;

ALTER TABLE public.canvas_nodes
    ADD COLUMN IF NOT EXISTS updated_at       timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS last_synced_at   timestamptz,
    ADD COLUMN IF NOT EXISTS reformat_pending boolean DEFAULT false;

-- Backfill: existing rows get updated_at from last_formatted (or now() if null).
UPDATE public.canvas_nodes
    SET updated_at = COALESCE(updated_at, last_formatted, now())
    WHERE updated_at IS NULL;

-- BEFORE-UPDATE trigger: stamp updated_at on every change. Runs before the
-- AFTER-trigger outbox emit, so the outbox payload carries the fresh timestamp.
-- Touching updated_at on an FS-applied write is harmless (the write IS a real
-- change); no GUC guard needed here.
CREATE OR REPLACE FUNCTION public.canvas_touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_canvas_touch_updated_at ON public.canvas_nodes;
CREATE TRIGGER trg_canvas_touch_updated_at
    BEFORE UPDATE ON public.canvas_nodes
    FOR EACH ROW EXECUTE FUNCTION public.canvas_touch_updated_at();

COMMENT ON COLUMN public.canvas_nodes.updated_at IS
    'Bumped on every UPDATE by trg_canvas_touch_updated_at. Conflict-ordering '
    'key for the canvas↔Rowboat bidirectional sync (LWW).';
COMMENT ON COLUMN public.canvas_nodes.last_synced_at IS
    'Timestamp of the last successful DB->FS markdown render (set by the sync '
    'worker). NULL = never rendered to ~/.rowboat/knowledge/Projects/.';
COMMENT ON COLUMN public.canvas_nodes.reformat_pending IS
    'TRUE while content has been edited via FS but content_json has not yet been '
    'regenerated by the reformat drainer. While TRUE, Worker A renders from '
    'content (skips the content_json flatten) — anti-flicker contract.';

COMMIT;

-- PostgREST schema-cache reload (run separately if applying this file alone):
NOTIFY pgrst, 'reload schema';
